### ISSUE TITLE
Raspbee isnt able to find lights

### ISSUE THREAD

**Issue by Arsur** [marthoc/docker-deconz#10]
I spend now alot work in getting this docker image run as it should but i did not succeed jet. My Osram Bulbs are not discoverable. My normal Lightify Gateway can easy pair them.
I updated the firmware of my bulbs (did also a hardwarereset and unpaired them) and the firmware of my raspbee (with gcfflasher).

The output during flashing was 

sudo GCFFlasher -f deCONZ_Rpi_0x261e0500.bin.GCF
rmmod: ERROR: Module ftdi_sio is not currently loaded
rmmod: ERROR: Module usbserial is not currently loaded
GCFFlasher V2_11 (c) dresden elektronik ingenieurtechnik gmbh 2017/12/10
no device specified use RaspBee (/dev/ttyS0)
using firmware file: deCONZ_Rpi_0x261e0500.bin.GCF
reset target

RaspBee Bootloader premium
Vers. 1.02
build 2013/08/01

flashing 126124 bytes: |==============================|
verify: ....
SUCCESS

When i open the ui (over "localip":80 or 80/pwa it tells me always i have to upgrade the firmware.
"The Version is 0000"

I used the docker-compose example from the readme, (had to open port 80 and 443 via ufw) but it seems to work anything, even the logs seem to be normal. (beside the error when i try to upgrade the firmware though the docker cointainer, which isnt supported by the image atm)

[Logs Docker Deconz.txt](https://github.com/marthoc/docker-deconz/files/1828495/Logs.Docker.Deconz.txt)

Can someone help me, how to get the bulbs communicating to my gateway?

**Comment by marthoc** [comment]
If you’re using the docker-compose example, you probably didn’t change the `device:` line, so it’s still /dev/ttyUSB0. For RaspBee, you’ll need to use /dev/ttyAMA0. There is also a section of the README to follow to enable the serial port on RaspBerry Pi so that RaspBee can use it. 

Can you verify that you have followed the README and also changed to /dev/ttyAMA0?

To check that RaspBee is found by the image, after following the steps above and starting the container, navigate to the web ui at port 80, go to the settings page, and scroll to the bottom. You should see a line that says:

“Your gateway is on channel X and has the network id 0xXXXX.”

If the device is discovered, the X’s above will be replaced by numbers/letters. If not, those X’s will be 0’s.

**Comment by Arsur** [comment]
I did mount Device dev/ttyAMA0 and i did enable serial Port (with the instruction here in the readme)
Is there a way to cross check if i had success with the things i did.

ZigBee Kanal 0
Netzwerk Id 0x0000

So i guess somehow my raspbee isn't discovered by Phoscon?

**Comment by marthoc** [comment]
Can you post the content of your compose file (just the deconz section is fine) in a code block so that I can double check it?

**Comment by Arsur** [comment]
version: "2"
services: 
  deconz:
    image: marthoc/deconz:armhf-2.05.15
    container_name: deconz
    network_mode: host
    restart: always
#    privileged: true
    volumes:
      - /home/USER/Docker/Deconz/config:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyAMA0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0

**Comment by marthoc** [comment]
That all looks good; you don’t need to specify an image tag, you can just specify marthoc/deconz and it will pull the latest version for your hardware. I’m going to have to test the latest image on my test hardware and get back to you on this.

**Comment by marthoc** [comment]
So I just noticed in your GCFlasher output this line:
`no device specified use RaspBee (/dev/ttyS0)`
Maybe your RaspBee is being picked up as /dev/ttyS0? Can you change your compose file to that device and try it?

**Comment by marthoc** [comment]
Just to double-check: what RaspBerry Pi model are you using?

**Comment by Arsur** [comment]
okay i will check this in 5 hours, iam stilll at work at the moment. 
Raspberry pi 3

**Comment by marthoc** [comment]
Hi @Arsur - I believe I've found the problem and I'll need to update the README. In addition to the raspi-config steps, you must also add the following line to the end of `/boot/config.txt`:

`dtoverlay=pi3-disable-bt`

Then reboot your Pi, specify /dev/ttyAMA0 in docker-compose.yml, and you should be all set.

Unfortunately there's a conflict between the bluetooth port and the serial port as far as device naming is concerned, so for the time being you must disable bluetooth; I'm going to investigate if it's possible to work-around this. 

(Why it's happening: it appears that when bluetooth is enabled it takes the name /dev/ttyAMA0 and RaspBee is assigned /dev/ttyS0. Inside the docker container deCONZ is expecting /dev/ttyAMA0 to be RaspBee, but fails to open the device as /dev/ttyAMA0 is the BT device.)

Please let me know if this fixes this issue; I'll close the issue when I've updated the README.

**Comment by Arsur** [comment]
ist worked! I love this image. Thank you for this!!!
