### ISSUE TITLE
Ports conflict when using Deconz and Unif-controller addons on Hass.io. 

### ISSUE THREAD

**Issue by Storkull** [marthoc/docker-deconz#102]
Hi, I'm having problems running Deconz and Unif-controller at the same time, probably because they use the same ports. Is there some way I can fix it? 
/Anders

**Comment by WhistleMaster** [comment]
Use the parameters:
```
-e DECONZ_WEB_PORT=8080
-e DECONZ_WS_PORT=8443
```
