### ISSUE TITLE
Conbee conflict with aeotec gen5 stick

### ISSUE THREAD

**Issue by cobirnm** [marthoc/docker-deconz#105]
I'm using a conbee in a raspberry pi 3b+ using your container. I have an aeotec gen5 stick and it causes conflict with conbee. I've followed your instructions on to setting the device to /dev/ttyUSB0 but never the less it has some conflicts. After some hours when i try to conect to deconz using vnc I see that it has stoped and I see that is asking for firmware update.

![image](https://user-images.githubusercontent.com/45829329/53060746-6df3df00-34b3-11e9-9d93-b5143b10e60d.png)

![image](https://user-images.githubusercontent.com/45829329/53060769-7ba96480-34b3-11e9-986d-ec957aff8d7c.png)

Have you had similar issue? Can you help me? 

P.S. conbee is at firmare 262F0500

**Comment by timpa82** [comment]
I also have a conflict using Aeotec Z-stick and Conbee with deconz in Docker (docker-compose and Portainer).
I have Home Assistant, currently 0.87.0. Conbee fw 262f0500, deconz 2.05.59.
Using Intel NUC with Ubuntu server.
I am using Home Assistant, so have that setup, and when I insert Conbee and run deconz, that is working aswell. But as soon as I update/reload the container for Home Assistant I cant reach the web ui, even thought he Hass container log says everything is normal.
As soon as I remove Conbee (and possibly have to stop the deconz container), Hass UI is working again.

Maybe the same issue?
