### ISSUE TITLE
Conbee on Synology 718+

### ISSUE THREAD

**Issue by bartje006** [marthoc/docker-deconz#106]
Hi,

I have installed the docker image on my NAS (conbee stick). I can open the Phoscon app, but at firmware is says 00000000. I can't add sensors.

Deconz is found in HA (running in Docker as well).

Any idea how I can get this working?

Thanks!

**Comment by chbndrhnns** [comment]
Not sure if this is related but my Synology with the conversation was so near to my wifi router that it interfered with the wifi signal. Using a USB extension cord helped here

**Comment by sragas** [comment]
Did you enable serial communication kernel modules on DS718+ there are disable by default.

insmod /lib/modules/usbserial.ko
insmod /lib/modules/ftdi_sio.ko
