### ISSUE TITLE
New firmware

### ISSUE THREAD

**Issue by kylegordon** [marthoc/docker-deconz#11]
The UI says I'm on 2.05.15, but I think the latest firmware is 2.06, if https://www.dresden-elektronik.de/funktechnik/products/software/pc-software/deconz/ makes sense!

Does this get baked into the Docker image or should it download and install automatically? When I hit the "update firmware" button it tells me to wait a while, but the version never changes.

**Comment by kylegordon** [comment]
Doh, I've just seen the comment in the README about how updates will fail silently. Still, maybe the docker images need updated? :-)

**Comment by Arsur** [comment]
be carefull on the release numbers, i guess dresden-electronic isnt linking the newest firmware one their webpage. You can get it here https://www.dresden-elektronik.de/rpi/deconz-firmware/
For my raspbee this is the newest version deCONZ_Rpi_0x261e0500.bin.GCF

**Comment by marthoc** [comment]
@kylegordon: it’s important to distinguish between the deCONZ software level (currently 2.05.15) and the RaspBee/Conbee firmware level (currently 0x261E0500). The image is routinely updated when a new deCONZ software level is released and you can get the new version by `docker pull`ing or using docker-compose. 

The firmware level, however, changes far less frequently and has nothing to do with updating the Docker image. It’s firmware updates that will fail from the web UI, but I will be posting a method soon to update your firmware inside the container from the command line (unfortunately it doesn’t seem like updating via the web ui will be possible in Docker at the moment).

**Comment by marthoc** [comment]
I still have to verify that it works on armhf, but I’ve tested it on amd64 and works - check the Next branch for instructions and you’ll need to build the image yourself if you’d like to test (as a bonus, it’s at 2.05.16, the newest software level):

```
git clone https://github.com/marthoc/docker-deconz
git checkout next
docker build -t "marthoc/deconz:latest" ./amd64
```

**Comment by gust1n** [comment]
Hey, thanks for your great job!

I tried flashing new firmware from a rpi3 (running resin-os a lá HASSIO) using next branch and building it locally as per your instructions but couldn't get it to work. The error I'm getting is: `docker: Error response from daemon: invalid character 'c' looking for beginning of value.`

**Comment by gust1n** [comment]
After some experimenting I actually got it to work, it was the mapping of `/dev` that messed up, but mapping it like when running it actually worked: `docker run -it --rm --device=/dev/ttyUSB0 --privileged --cap-add=ALL -v /lib/modules:/lib/modules --entrypoint "/firmware-update.sh" gust1n/deconz:local`

**Comment by marthoc** [comment]
@gust1n thanks for the info... I actually didn’t think this method would work on Hass.io at all, so I’ll keep your instructions in mind when I turn to making instructions for Hass.io.

**Comment by gust1n** [comment]
Np :) Ofc you'll need to ssh into the actual resin-os to get access to the docker daemon so I guess technically we're not inside HASSIO anymore.

**Comment by marthoc** [comment]
The firmware script (with some additional modifications) will be present in the latest release of the Docker image (2.05.16). Should be available on Docker Hub in 30 mins or so. Check README.md for updated instructions; working on both amd64 and armhf, Conbee and RaspBee.
