### ISSUE TITLE
Can't view Deconz mesh through VNC

### ISSUE THREAD

**Issue by miljume** [marthoc/docker-deconz#111]
Hello,

I have started the container with:
`docker run -d --name=deconz --net=host --restart=always     -v /etc/localtime:/etc/localtime:ro -v /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ     --device=/dev/ttyUSB0 marthoc/deconz -e DECONZ_WEB_PORT=8080 -e DECONZ_VNC_MODE=1 -e DECONZ_VNC_PORT=5901 -e DECONZ_VNC_PASSWORD=<password>`

But when I try to connect to my host machine with `<ip address>:5901` with VNC viewer I only get connection refused. What can be wrong?

**Comment by marthoc** [comment]
A firewall on your device?

**Comment by miljume** [comment]
No, it's working when I connect to the machine directly with VNC. I have tried to shutdown VNC on the host computer to make sure it doesn't conflict with the container VNC but no success

**Comment by miljume** [comment]
I am new to Docker but I found the following in the log

`[marthoc/deconz] Starting deCONZ...
[marthoc/deconz] Current deCONZ version: 2.05.60
[marthoc/deconz] Web UI port: 8080
[marthoc/deconz] Websockets port: 443
[marthoc/deconz] VNC Display: :0 on port 5900
tigervncserver: /usr/bin/Xtigervnc did not start up, please look into '/root/.vnc/<logfilename>:0.log' to determine the reason! -2 Invalid MIT-MAGIC-COOKIE-1 keyQXcbConnection: Could not connect to display :0`

But the log file doesn't exist so I can't see what's wrong. I tried setting DECONZ_VNC_DISPLAY=1 but still the same error

**Comment by miljume** [comment]
Here is my log from Docker 

`[marthoc/deconz] Starting deCONZ...,
[marthoc/deconz] Current deCONZ version: 2.05.60,
[marthoc/deconz] Web UI port: 80,
[marthoc/deconz] Websockets port: 443,
[marthoc/deconz] Starting without VNC GUI,
libpng warning: iCCP: known incorrect sRGB profile,
22:11:57:799 HTTP Server listen on address 0.0.0.0, port: 8080, root: /usr/share/deCONZ/webapp/,
22:11:57:808 CTRL. 3.16.222:11:57:821 ZCLDB init file /root/.local/share/dresden-elektronik/deCONZ/zcldb.txt,
22:11:57:855 parent process /bin/sh,
22:11:57:855 gw run mode: docker,
22:11:57:855 GW sd-card image version file does not exist: /root/.local/share/dresden-elektronik/deCONZ/gw-version,
22:11:57:855 DB sqlite version 3.16.2,
22:11:57:855 DB PRAGMA page_count: 30,
22:11:57:856 DB PRAGMA page_size: 4096,
22:11:57:856 DB PRAGMA freelist_count: 0,
22:11:57:856 DB file size 122880 bytes, free pages 0,
22:11:57:856 DB PRAGMA user_version: 6,
22:11:57:856 DB cleanup,
22:11:57:856 DB create temporary views,
22:11:57:857 don't close database yet, keep open for 900 seconds,
22:11:57:857 started websocket server at port 443,
22:11:57:858 discovery updated announce interval to 10 minutes,
22:11:57:858 GW firmware update not supported on x86 linux headless,
22:11:57:858 found node plugin: libde_rest_plugin.so - REST API Plugin,
22:11:57:859 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin,
22:11:57:861 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin,
This plugin does not support propagateSizeHints(),
This plugin does not support propagateSizeHints(),
This plugin does not support propagateSizeHints(),
22:11:57:905 Device firmware version 0x261F0500,
22:11:57:922 unlocked max nodes: 200,
22:11:58:210 Device protocol version: 0x0106,
22:11:58:228 new node - ext: 0x00212effff032e2c, nwk: 0x0000,
22:11:58:418 Current channel 25,
22:11:58:482 CTRL ANT_CTRL 0x02,
22:11:58:594 Device protocol version: 0x0106,
22:11:58:786 Current channel 25,
22:11:58:850 CTRL ANT_CTRL 0x02,
22:12:03:184 Announced to internet,
22:12:04:117 New websocket 192.168.0.178:53751 (state: 3) ,
22:12:05:498 Remove websocket 192.168.0.178:53751 after error Unknown error,
22:12:06:570 New websocket 192.168.0.178:53759 (state: 3) ,
12:22:919 scan finished,
22:12:58:013 Current channel 25,`

I am new to docker but it seems like its starting without VNC despite what I used when I started the container

**Comment by miljume** [comment]
So I solved it, it turned out to be arguments in the wrong order
Case closed
