### ISSUE TITLE
Questions about my mesh (unknown devices/bad route)

### ISSUE THREAD

**Issue by pergolafabio** [marthoc/docker-deconz#112]
ok, in my screenshot below, you see i have a verry easy mesh:
https://www.dropbox.com/s/rulw8bmpyqek4rz/meshxiaomi2.JPG?dl=0
deconz conbee FW: 262F0500

so , in phoscon i added:
3 x osram powerplug, i use them as a repeater to create better mesh, so i have them on each floor
2 x ikea remote switch
4 x xiaomi pir body sensor

the red lines are my floors
so,
ground floor (1 x xiaomi , 1 x osram)
first floor (2 x ikea , 3 x xiaomi , 1 x osram)
second floor (conbee + 1 x osram)

2 issues/questions

my xiaomi? 3 of them are paired directly with the conbee, while the osram power plug1 is verry nearby... xiamo_sensor_4 , well thats is giving me headaches, its verry close to plug1, why is it choosing the worst route ever? restarting conbee doesnt help? how can i relink it?
also took out the battery, doesnt help... (all new battery)
sensor4 isnt working reliable!

those 3 devices in the red circle, i have no clue what they are? dont have them in phoscon, what are they doing there? there is even one linked
i had 3 x ikea pir sensors before, but they sucked, so remove them from phoscon and took out batterys, maybe they are remaing stuff? but then again, why is there still 1 linked?

thnx in advance

**Comment by marthoc** [comment]
This is more of a question for the dresden electronik deconz repo, not a question for here, as this addon doesn’t have anything to do with your issue.
