### ISSUE TITLE
FW upgrade not working "unknown command"

### ISSUE THREAD

**Issue by fillilutten** [marthoc/docker-deconz#113]
I logged in with 

'ssh root@hassio.local -p 22222'

and then tried

'docker run -it --rm --device=/dev/ttyUSB0 --privileged --cap-add=ALL -v /lib/modules:/lib/modules --entrypoint "/firmware-update.sh" marthoc/hassio-addon-deconz-armhf'

But I get an error 

'FATA[0000] Error while executing rootCmd: unknown command "docker" for "hassio" '

Why is this and how do I solve it so I can upgrade the conbee?

Thanks!

**Comment by JBS5** [comment]
Before running the docker command, enter 'login'.

**Comment by fillilutten** [comment]
Well that was an easy fix, haha. Huge thanks!
