### ISSUE TITLE
ConBeeII FW upgrade

### ISSUE THREAD

**Issue by bastshoes** [marthoc/docker-deconz#117]
I'm running 2.05.63. Just received Conbee II. When trying to upgrade FW (fw file present in docker) flasher do not see device.

**Comment by manup** [comment]
Please check the following issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1440

The problem is fixed but requires rebuild locally — or wait when the next container version is pushed to Docker Hub.

**Comment by bastshoes** [comment]
Thanks already found.
