### ISSUE TITLE
2.05.64 / 22-4-2019 - Conbee (1) update error 

### ISSUE THREAD

**Issue by lubbertkramer** [marthoc/docker-deconz#120]
Not sure if this belongs here but i can update my conbee (1) but getting an error on the latest image:

19:26:26:111 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_Rpi_0x26330500.bin.GCF,
19:26:26:111 GW firmware version: 0x26320500,
19:26:26:111 GW firmware version shall be updated to: 0x26330500

![image](https://user-images.githubusercontent.com/8224586/56602450-c5badd80-65fd-11e9-8183-86793d7aca2d.png)

-------------------------------------------------------------------

       marthoc/deconz Conbee/RaspBee Firmware Flashing Script

                       Version: 0.3

-------------------------------------------------------------------

Enter C for Conbee, R for RaspBee, or press Enter now to exit: C

Listing attached devices...

GCFFlasher V3_03 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyUSB0     | 0x0403 | 0x6015  |            | ConBee

Enter the Conbee device number, or press Enter now to exit.

Device Number : 1

-------------------------------------------------------------------

Firmware available for flashing:

deCONZ_ConBeeII_0x26480700.bin.GCF
deCONZ_ConBeeII_0x26490700.bin.GCF
deCONZ_Rpi_0x261f0500.bin.GCF
deCONZ_Rpi_0x26320500.bin.GCF
deCONZ_Rpi_0x26330500.bin.GCF

Enter the firmware file name from above, including extension,
or press Enter now to exit.

File Name : deCONZ_Rpi_0x26330500.bin.GCF

-------------------------------------------------------------------

Conbee Device Number: 1

Firmware File: deCONZ_Rpi_0x26330500.bin.GCF

Are the above device and firmware values correct?
Enter Y to proceed, any other entry to exit: Y

Flashing...

GCFFlasher V3_03 (c) dresden elektronik ingenieurtechnik gmbh

Flashing Error! Please re-run this script...

lubbertkramer@nuc-1701:~/docker$

---------------------------

Have rebooted my NUC, stopped all dockers but everytime the same error -> Flashing Error! Please re-run this script...

**Comment by Oliviakrkk** [comment]
I had the same issue. Try counting from 0.  
In Conbee Device Number put 0 not 1.

**Comment by lubbertkramer** [comment]
Thanks, that did the trick! Always used 1 as far as i can remember but as you mentioned https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1459 here maybe good to show the device number :)
