### ISSUE TITLE
Get access to root/otau

### ISSUE THREAD

**Issue by lubbertkramer** [marthoc/docker-deconz#121]
Is it possible to get access to the root/otau folder by putty to place firmware images for ikea in the folder? I see the folder in the docker but i can't access it. 

Maybe combine it in line with -> https://github.com/marthoc/docker-deconz/issues/118

![image](https://user-images.githubusercontent.com/8224586/56621617-6eccfc80-662d-11e9-9c86-6145f128a86e.png)

**Comment by LightningRhino** [comment]
One problem is: after you deploy a new image the /root/otau folder is empty again and you have to start over.
If there was python installed in the image one could at least download the ikea firmware inside the container (I opened an issue for this matter).

Until then I managed to get the firmware into the right folder doing this:
- download the firmware files under Windows or MacOS and copy them with e.g. WinSCP or ForkLift over to the /tmp directory of your docker host.
- on your host stop the deconz container and copy the firmware files into your exposed volume for deconz which eventually will get the files to /root/.local/share/dresden-elektronik/deCONZ/otau (the otau directory has to be created).
- start the container again and with`docker exec –it myDeconzContainer /bin/bash`
 finally copy the files into /root/otau with `cp /root/.local/share/dresden-elektronik/deCONZ/otau/*.signed /root/otau/`

- `exit` from the container shell

But as I mentioned before the files will be gone after you updated your docker image to a new version.

**Comment by manup** [comment]
You can also mount bind a persistant otau folder on the host into the container, just like for the configuration:

```
docker run -d \
    --name=deconz \
    --net=host \
    --restart=always \
    -v /etc/localtime:/etc/localtime:ro \
    -v /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ \
    -v ~/otau:/root/otau \
    --device=/dev/ttyUSB0 \
    marthoc/deconz
```

**Comment by lubbertkramer** [comment]
Above solutions worked indeed, thanks oversaw that option to mount it.
