### ISSUE TITLE
Firmware Updating HELP: Running ConBee on a Synology NAS  with Docker

### ISSUE THREAD

**Issue by themfinger** [marthoc/docker-deconz#127]
Dear friends,

I have deCONZ running in my Nas (Synology, with 8Gb ram) controlling a ConBee.
So far it's working great. I run marthoc/deconz and oznu/homebridge.

I receive an indication that I should update the GW firmware, but in this setup the instructions  tell me to "invoke" a firmware update script, but I don't know how to do it... I use the Docker GUI, no command line here.

Can someone help me ?
Following the instructions found here:
https://hub.docker.com/r/marthoc/deconz

Many thanks in advance
Nuno

**Comment by th3cube** [comment]
You need to SSH into your Synology and follow these instructions 

https://github.com/marthoc/docker-deconz#updating-conbeeraspbee-firmware
