### ISSUE TITLE
Flashing with 2.05.64 failing

### ISSUE THREAD

**Issue by indyspike** [marthoc/docker-deconz#128]
deconz container is stopped. Run the firmware update script as per the README:

> GCFFlasher V3_03 (c) dresden elektronik ingenieurtechnik gmbh
> Path             | Vendor | Product | Serial     | Type
> -----------------+--------+---------+------------+-------
> /dev/ttyUSB0     | 0x0403 | 0x6015  |            | ConBee 
> /dev/ttyACM0     | 0x1CF1 | 0x0030  |            | ConBee II 
>  
> Enter the Conbee device number, or press Enter now to exit.

Selected Device 0 

>Firmware available for flashing:
> 
> deCONZ_ConBeeII_0x26480700.bin.GCF
> deCONZ_ConBeeII_0x26490700.bin.GCF
> deCONZ_Rpi_0x261f0500.bin.GCF
> deCONZ_Rpi_0x26320500.bin.GCF
> deCONZ_Rpi_0x26330500.bin.GCF
>  
> Enter the firmware file name from above, including extension,
> or press Enter now to exit.

Used deCONZ_Rpi_0x26330500.bin.GCF as suggested by the log file. After responding Y to confirm flashing I get

> GCFFlasher V3_03 (c) dresden elektronik ingenieurtechnik gmbh
> 
> 585: Error: (assert) expected m_dev.size() == 1
>  
> Flashing Error! Please re-run this script...

**Comment by Gnaget2** [comment]
dont select 0

use /dev/ttyUSB0 instead when it asked for device number

**Comment by indyspike** [comment]
Thanks, that worked. Saw a previous issue that said it was a zero indexed list. The prompts aren't clear. Suggest either the script output is updated,or the documentation is updated to clarify what should be entered for this step.

**Comment by wmn79** [comment]
Had the same issue, seems to work now thanks @Gnaget2

**Comment by jjanderson** [comment]
FYI, this works on Synology, however you are presented with an error. This has worked, you will however need to issue the commands before restarting the docker container

sudo insmod /lib/modules/usbserial.ko
sudo insmod /lib/modules/ftdi_sio.ko

once the upgrade has presented you with the message below:

```
rmmod: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/3.10.105/modules.builtin.bin'
rmmod: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/3.10.105/modules.builtin.bin'
GCFFlasher V3_03 (c) dresden elektronik ingenieurtechnik gmbh
reset FTDI DM00ZGS0 (dev: 0)
action: update firmware after 2 ms
flashing 125684 bytes: |=============================|
verify: ....
SUCCESS
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/3.10.105/modules.dep.bin'
modprobe: FATAL: Module usbserial not found in directory /lib/modules/3.10.105
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/3.10.105/modules.dep.bin'
modprobe: FATAL: Module ftdi_sio not found in directory /lib/modules/3.10.105
```
