### ISSUE TITLE
Improve docker hub image description

### ISSUE THREAD

**Issue by Nikola-K** [marthoc/docker-deconz#129]
So yesterday I got ConBee II and setting it up in this docker container took a bit primarily since not all environment variables are documented in the docker image overview/docs which is what I used as a reference as on the first look it seemed identical as this repo, and the instructions are a bit misleading in my opinion.

1. ConBee 2 is `/dev/ttyACM0` on the host, as it should be - https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1440#issuecomment-484196053

2. Now this might be just me but the docs for this image say "Pass the serial device at ttyUSB0 (i.e. a Conbee USB device) into the container for use by deCONZ (if using RaspBee, use /dev/ttyAMA0)." which lead me to believe that the device in the container needs to be `ttyUSB0` as just using `ttyACM0` wasn't working, or even mapping `ttyACM0` to `ttyUSB0` didn't work for me.

3. Under the "Environment Variables" section on https://hub.docker.com/r/marthoc/deconz/ the 
`DECONZ_DEVICE` environment variable is _NOT_ documented as it is in the readme in this github repo, otherwise docs seem to be more or less the same.

4. There is no indication which device should be used depending on the product (e.g. `ttyACM0` for ConBee II, `ttyUSB0` for ConBee, and `ttyAMA0` for RaspBee`

In my opinion the docs should be updated to point out these potential issues and clarify the setup. Optionally linking to https://phoscon.de/en/conbee2/install#docker https://phoscon.de/en/conbee/install#docker and https://phoscon.de/en/raspbee/install#docker might also be a good idea (those also make use of the `DECONZ_DEVICE` environment variable, but they ironically link to the docker hub for more container information)

Another thing that these docs don't mention, but official ones do is the ` sudo gpasswd -a $USER dialout` - which I'm not sure is always needed, but maybe could save some users trouble.

**Comment by marthoc** [comment]
Thanks for this. I'm pushing an update that will incorporate these suggestions and I will update Docker Hub with the latest also.
