### ISSUE TITLE
Annapurna CPU support possible?

### ISSUE THREAD

**Issue by Monnem** [marthoc/docker-deconz#135]
Hello,

is there a change to bring this deconz on annapurna ARM CPUs?
Tried armhf branch but this results in an wrong exec format error. Obviously two/too different . ;-)
My qnap 332x shows this cpu details:
[~] # cat /proc/cpuinfo 
processor	: 0
model name	: Annapurna Labs Alpine AL324 Quad-core ARM Cortex-A57 CPU @ 1.70GHz
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd07
CPU revision	: 3

Maybe you need additional info. So please give me a hint!

Thanks

**Comment by b2un0** [comment]
looks like an an `armv8`, so you should try the `arm64` build.

**Comment by Monnem** [comment]
Hi, thnaks for the hint with arm64. Unfortunately Qnaps repository shows no arm64. IS there a docker command line option to force the amd64 variant? Or do I need to refer to another repository?
Thx

**Comment by marthoc** [comment]
Unfortunately I'm not familiar with that CPU; it says it has an arm architecture, but then strange that the armhf variant won't run on it. I may need to revise my comments about the arm64 arch - it's supported to the extent that it will run armhf docker images (as the arm64 support is just a relabeled armhf image). I think I will need to explore using an actual 64-bit base image.

**Comment by marthoc** [comment]
Actually @manup - is there a reason deCONZ wouldn't run on that CPU?

**Comment by Monnem** [comment]
Don't know if this help. I can start from the repository e.g. the 
angelnu/iobroker:latest-arm64
Besides it throws a general error as this container seems to have some dependencies it starts.
So from my docker newbie side it should work in general. If I can support with my very limited docker experience please come back to me

**Comment by manup** [comment]
>Actually @manup - is there a reason deCONZ wouldn't run on that CPU?

There is a first arm64 port of deCONZ for Debian Stretch available, perhaps it works?

Packages: https://www.dresden-elektronik.de/rpi/deconz/alpha/

**Comment by Monnem** [comment]
Hi, maybe any news? If you need a tester, here I am. ;-)

**Comment by marthoc** [comment]
@manup - does the arm64 port of deCONZ still require WiringPi? If so, what version of WiringPi are you using (or are you compiling yourself)?

**Comment by manup** [comment]
The current arm64 version doesn't use WiringPi as quick workaround because it wasn't available for ODROID. 

Background: WiringPi is only needed to power-cycle the RaspBee board. As alternative a reset command is send via UART, which doesn't need any extra libraries but relies on a working firmware to be installed. 

Later on we'll add WiringPi again for arm64, it will be loaded as dynamic lib so it becomes an optional dependency.

**Comment by marthoc** [comment]
@Monnem I have built and pushed a new tag for the marthoc/deconz image: aarch64. Please test on your hardware if you are able using that image (marthoc/deconz:aarch64). 

You could also test pulling just marthoc/deconz to see if that manifest support is working properly (i.e. autodetect the proper image for your arch).

Caveats: I don't know if it works as I can't test it myself. The image builds but I can't test if it is working as I don't have aarch64/arm64 hardware. Also, support for deCONZ on this arch appears to be experimental at the moment so even if the image works, deCONZ may not completely work. Please let me know in this issue and I'm sure @manup will also be interested in the results.

**Comment by Monnem** [comment]
Hello/Hallo,
awesome :-)
pulled "latest" and it comes up and detected the conbee.
I'll paste in the terminal output. Unfortunately the output begins somewhere while booting. But maybe it's helpful also. I'll copy my files from the working and make them available to the container and will check, if the result in the web GUI seems to be the same.
Will come back with this latest tomorrows evening. If you need something else to know, please come back to me.

**Thanks/Danke for your effort!**

One last thing: I noticed on a Qnap _Intel_ NAS. If I create the container with VNC enabled the load is much higher than without. Is this normal? 

`This plugin does not support propagateSizeHints()                                                                                                                                                                                                                                                                                                                                                 
19:59:13:548 Device firmware version 0x26330500                                                                                                                                                                                                                                                                                                                                                   
19:59:13:794 Device protocol version: 0x010B                                                                                                                                                                                                                                                                                                                                                      
19:59:13:809 new node - ext: 0x00212effff02f291, nwk: 0x0000                                                                                                                                                                                                                                                                                                                                      
19:59:14:019 SensorNode 2 set node 0x00158d000252a54e                                                                                                                                                                                                                                                                                                                                             
19:59:14:028 SensorNode 5 set node 0x00158d0002730ac2                                                                                                                                                                                                                                                                                                                                             
19:59:14:028 SensorNode 6 set node 0x00158d0002730ac2                                                                                                                                                                                                                                                                                                                                             
19:59:14:028 SensorNode 4 set node 0x00158d0002730ac2                                                                                                                                                                                                                                                                                                                                             
19:59:14:036 SensorNode 10 set node 0x00158d0002772493                                                                                                                                                                                                                                                                                                                                            
19:59:14:037 SensorNode 11 set node 0x00158d0002772493                                                                                                                                                                                                                                                                                                                                            
19:59:14:037 SensorNode 12 set node 0x00158d0002772493                                                                                                                                                                                                                                                                                                                                            
19:59:14:045 SensorNode 14 set node 0x00158d000273d14c                                                                                                                                                                                                                                                                                                                                            
19:59:14:045 SensorNode 15 set node 0x00158d000273d14c                                                                                                                                                                                                                                                                                                                                            
19:59:14:045 SensorNode 13 set node 0x00158d000273d14c                                                                                                                                                                                                                                                                                                                                            
19:59:14:054 SensorNode 22 set node 0x00158d000273b975                                                                                                                                                                                                                                                                                                                                            
19:59:14:078 SensorNode 19 set node 0x00158d0002739ff1                                                                                                                                                                                                                                                                                                                                            
19:59:14:078 SensorNode 20 set node 0x00158d0002739ff1                                                                                                                                                                                                                                                                                                                                            
19:59:14:078 SensorNode 21 set node 0x00158d0002739ff1                                                                                                                                                                                                                                                                                                                                            
19:59:14:098 SensorNode 3 set node 0x00158d000252a538                                                                                                                                                                                                                                                                                                                                             
19:59:14:108 SensorNode 16 set node 0x00158d00028af263                                                                                                                                                                                                                                                                                                                                            
19:59:14:108 SensorNode 17 set node 0x00158d00028af263                                                                                                                                                                                                                                                                                                                                            
19:59:14:121 SensorNode 23 set node 0x00158d00028af252                                                                                                                                                                                                                                                                                                                                            
19:59:14:121 SensorNode 18 set node 0x00158d00028af252                                                                                                                                                                                                                                                                                                                                            
19:59:14:134 don't close database yet, keep open for 900 seconds                                                                                                                                                                                                                                                                                                                                  
19:59:14:134 LightNode 2: Light Switch SZ Fenster added                                                                                                                                                                                                                                                                                                                                           
19:59:14:144 SensorNode 7 set node 0x00158d000238a334                                                                                                                                                                                                                                                                                                                                             
19:59:14:145 SensorNode 9 set node 0x00158d000238a334                                                                                                                                                                                                                                                                                                                                             
19:59:14:145 SensorNode 8 set node 0x00158d000238a334                                                                                                                                                                                                                                                                                                                                             
19:59:14:154 don't close database yet, keep open for 900 seconds                                                                                                                                                                                                                                                                                                                                  
19:59:14:154 LightNode 1: Light Switch SZ Tür added                                                                                                                                                                                                                                                                                                                                               
19:59:14:164 don't close database yet, keep open for 900 seconds                                                                                                                                                                                                                                                                                                                                  
19:59:14:164 LightNode 3: Licht 1 RGB added                                                                                                                                                                                                                                                                                                                                                       
19:59:14:165 don't close database yet, keep open for 900 seconds                                                                                                                                                                                                                                                                                                                                  
19:59:14:165 LightNode 4: Licht 1 weiß added                                                                                                                                                                                                                                                                                                                                                      
19:59:14:177 don't close database yet, keep open for 900 seconds                                                                                                                                                                                                                                                                                                                                  
19:59:14:177 LightNode 5: Light 2 RGB added                                                                                                                                                                                                                                                                                                                                                       
19:59:14:178 don't close database yet, keep open for 900 seconds                                                                                                                                                                                                                                                                                                                                  
19:59:14:179 LightNode 6: Licht 2 weiß added                                                                                                                                                                                                                                                                                                                                                      
19:59:14:187 SensorNode 24 set node 0x00158d0002e2e8e3                                                                                                                                                                                                                                                                                                                                            
19:59:14:187 SensorNode 25 set node 0x00158d0002e2e8e3                                                                                                                                                                                                                                                                                                                                            
19:59:14:195 SensorNode 27 set node 0x00158d0002130ac4                                                                                                                                                                                                                                                                                                                                            
19:59:14:205 don't close database yet, keep open for 900 seconds                                                                                                                                                                                                                                                                                                                                  
19:59:14:206 LightNode 7: Light 7 Spiegel 1 added                                                                                                                                                                                                                                                                                                                                                 
19:59:14:221 don't close database yet, keep open for 900 seconds                                                                                                                                                                                                                                                                                                                                  
19:59:14:221 LightNode 8: Light 8 Spiegel 2 added                                                                                                                                                                                                                                                                                                                                                 
19:59:14:231 don't close database yet, keep open for 900 seconds                                                                                                                                                                                                                                                                                                                                  
19:59:14:232 LightNode 9: Light 9 Flur Tür added                                                                                                                                                                                                                                                                                                                                                  
19:59:14:241 don't close database yet, keep open for 900 seconds                                                                                                                                                                                                                                                                                                                                  
19:59:14:241 LightNode 10: Light 10 Flur Tür added                                                                                                                                                                                                                                                                                                                                                
19:59:14:249 SensorNode 28 set node 0x00158d0002131062                                                                                                                                                                                                                                                                                                                                            
19:59:14:257 SensorNode 30 set node 0x00158d0002e2e5cb                                                                                                                                                                                                                                                                                                                                            
19:59:14:257 SensorNode 29 set node 0x00158d0002e2e5cb                                                                                                                                                                                                                                                                                                                                            
19:59:14:266 SensorNode 32 set node 0x00158d000257a7a2                                                                                                                                                                                                                                                                                                                                            
19:59:14:267 SensorNode 33 set node 0x00158d000257a7a2                                                                                                                                                                                                                                                                                                                                            
19:59:14:277 don't close database yet, keep open for 900 seconds                                                                                                                                                                                                                                                                                                                                  
19:59:14:278 LightNode 11: Light 11 Schlafzimmer added                                                                                                                                                                                                                                                                                                                                            
19:59:14:289 don't close database yet, keep open for 900 seconds                                                                                                                                                                                                                                                                                                                             `

**Comment by marthoc** [comment]
Very glad to hear it works!

> One last thing: I noticed on a Qnap Intel NAS. If I create the container with VNC enabled the load is much higher than without. Is this normal?

It makes sense that the load is higher with VNC enabled as in that case there is a graphical environment and deCONZ is running in normal mode, whereas without VNC enabled deCONZ runs in _minimal_ mode which is via daemon only.

@manup - do you plan to release arm64 versions now with each release of deCONZ for other platforms? If so, I will merge this branch into master and build new images for arm64 with each deCONZ release as happens for amd64 and armhf.

**Comment by manup** [comment]
>@manup - do you plan to release arm64 versions now with each release of deCONZ for other platforms? If so, I will merge this branch into master and build new images for arm64 with each deCONZ release as happens for amd64 and armhf.

Yes it's already baked into the auto build system and a package is build for Debian Stretch arm64. 
The following snipped, adapted from the official docs should work:

```
sh -c "echo 'deb [arch=arm64] http://phoscon.de/apt/deconz \
            stretch-beta main' > \
            /etc/apt/sources.list.d/deconz.list"

apt update
apt install deconz
```

https://phoscon.de/conbee2/install#raspbian
