### ISSUE TITLE
osx docker works only with --privilege, hue bulb not found

### ISSUE THREAD

**Issue by romei777** [marthoc/docker-deconz#146]
Hi,
I've tested docker with Mac OS 10.13.6 (High Sierra)

I have to run the docker command line with --privilege and the usb port does not look like /dev/ttyACM0 but rather /dev/tty.usbmodemxxxxx
Moreover I had to create the /opt/deconz directory
After that the app work, but both on localhost and an ip adress (192.168.x.x), localhost does not allow to reset the gateway but accessing through the ip does.

What does not work is finding a hue bulb, after a factory reset.
The Hue app on IOS finds the Phoscon Hub but it says this hub has limited capacities and asks for a hub update (which obviously does not work).

It work on the same machine/network with windows, so I guess it's an os x / docker issue.
Here are the logs :

[marthoc/deconz] Starting deCONZ...
[marthoc/deconz] Current deCONZ version: 2.05.66
[marthoc/deconz] Web UI port: 80
[marthoc/deconz] Websockets port: 443
[marthoc/deconz] VNC Disabled
libpng warning: iCCP: known incorrect sRGB profile
15:49:53:575 HTTP Server listen on address 0.0.0.0, port: 80, root: /usr/share/deCONZ/webapp/
15:49:53:586 CTRL. 3.16.215:49:53:612 ZCLDB init file /root/.local/share/dresden-elektronik/deCONZ/zcldb.txt
15:49:53:655 parent process /bin/sh
15:49:53:655 gw run mode: docker
15:49:53:656 GW sd-card image version file does not exist: /root/.local/share/dresden-elektronik/deCONZ/gw-version
15:49:53:659 started websocket server at port 443
15:49:53:660 create default username and password
15:49:53:661 discovery updated announce interval to 10 minutes
15:49:53:661 GW firmware update not supported on x86 linux headless
15:49:53:662 found node plugin: libde_rest_plugin.so - REST API Plugin
15:49:53:663 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
15:49:53:670 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
15:49:53:715 scan skip host .2
15:49:58:704 Announced to internet
15:49:59:200 New websocket 172.17.0.1:53256 (state: 3) 
15:49:59:208 New websocket 172.17.0.1:53260 (state: 3) 
15:50:00:600 New websocket 172.17.0.1:53316 (state: 3) 
15:50:01:678 Websocket disconnected 172.17.0.1:53256 (state: 0) 
15:50:03:211 New websocket 172.17.0.1:53442 (state: 3) 
15:50:06:481 scan finished
15:50:11:154 Websocket disconnected 172.17.0.1:53442 (state: 0) 
15:50:12:662 New websocket 172.17.0.1:53640 (state: 3) 
15:50:51:627 Websocket disconnected 172.17.0.1:53640 (state: 0) 
15:50:53:039 New websocket 172.17.0.1:53642 (state: 3) 
15:51:02:220 Websocket disconnected 172.17.0.1:53642 (state: 0) 
15:51:06:480 created username: 79585A58A5, devicetype: Phoscon#B1440x803
15:51:36:791 Updated password hash: $1$8282jdkm$dBng6.FaBk3sdpAlWL46i0
15:51:36:987 created username: C00BA9AE8F, devicetype: Phoscon#B1440x803
15:51:38:477 New websocket 172.17.0.1:53648 (state: 3) 
15:51:40:108 Websocket disconnected 172.17.0.1:53648 (state: 0) 
15:51:41:619 New websocket 172.17.0.1:53650 (state: 3) 
15:51:45:707 Websocket disconnected 172.17.0.1:53650 (state: 0) 
15:51:47:066 New websocket 172.17.0.1:53652 (state: 3) 
15:53:20:160 Websocket disconnected 172.17.0.1:53652 (state: 0) 
15:53:21:518 New websocket 172.17.0.1:53658 (state: 3) 
15:53:22:390 Websocket disconnected 172.17.0.1:53658 (state: 0) 
15:53:23:899 New websocket 172.17.0.1:53662 (state: 3) 
15:59:52:794 Announced to internet
16:09:52:098 Announced to internet

Any ideas, help will be appreciated :)
Regards,
Romei.
PS : here's the conf using the API, the gateway IP is different from the one I use to access the app (a docker issue ?)
{
  "UTC": "2019-07-26T17:09:22",
  "apiversion": "1.16.0",
  "backup": {
    "errorcode": 0,
    "status": "idle"
  },
  "bridgeid": "0000000000000000",
  "datastoreversion": "60",
  "dhcp": true,
  "factorynew": false,
  "fwversion": "0x00000000",
  "gateway": "172.17.0.1",
  "internetservices": {
    "remoteaccess": "disconnected"
  },
  "ipaddress": "172.17.0.2",
  "linkbutton": false,
  "localtime": "2019-07-26T17:09:22",
  "mac": "02:42:ac:11:00:02",
  "modelid": "deCONZ",
  "name": "Phoscon-GW",
  "netmask": "255.255.0.0",
  "networkopenduration": 60,
  "panid": 0,
  "portalconnection": "disconnected",
  "portalservices": false,
  "portalstate": {
    "communication": "disconnected",
    "incoming": false,
    "outgoing": false,
    "signedon": false
  },
  "proxyaddress": "none",
  "proxyport": 0,
  "replacesbridgeid": null,
  "rfconnected": false,
  "starterkitid": "",
  "swupdate": {
    "checkforupdate": false,
    "devicetypes": {
      "bridge": false,
      "lights": [],
      "sensors": []
    },
    "notify": false,
    "text": "",
    "updatestate": 0,
    "url": ""
  },
  "swupdate2": {
    "autoinstall": {
      "on": false,
      "updatetime": ""
    },
    "bridge": {
      "lastinstall": "2019-06-16T17:39:51",
      "state": "noupdates"
    },
    "checkforupdate": false,
    "install": false,
    "lastchange": "",
    "lastinstall": "",
    "state": "noupdates"
  },
  "swversion": "2.5.66",
  "timeformat": "12h",
  "timezone": null,
  "uuid": "bac04c62-924f-4cb2-adb0-361f2cc1dd79",
  "websocketnotifyall": true,
  "websocketport": 443,
  "whitelist": {
    "532F2FA38F": {
      "create date": "2019-07-26T17:08:07",
      "last use date": "2019-07-26T17:09:22",
      "name": "justme"
    },
    "79585A58A5": {
      "create date": "2019-07-26T15:51:06",
      "last use date": "2019-07-26T15:51:36",
      "name": "Phoscon#B1440x803"
    },
    "C00BA9AE8F": {
      "create date": "2019-07-26T15:51:36",
      "last use date": "2019-07-26T17:09:22",
      "name": "Phoscon#B1440x803"
    },
    "FA2A376BF3": {
      "create date": "2019-07-26T16:42:52",
      "last use date": "2019-07-26T17:09:21",
      "name": "Phoscon#B1440x803"
    }
  },
  "zigbeechannel": 0
}

**Comment by m-reuter** [comment]
Same Problem here (on Sierra 10.12.6 , Macbook Pro). Device is also called 
tty.usbmodem##### and --priviledged is needed. Phoscon App starts, but I see "Firmware: not connected" and cannot find any hue lights. Someone in issue #32 has the same problem.

**Comment by JayStringer** [comment]
I've run in to this issue now too, has anybody had any luck? Even when I run with `--privileged` and specify `--device=/dev/tty.usbmodemXXXXXXX` I still can't get my mac to recognise my Conbee II stick (although I no longer get the device not found problem when I run with `--privileged`.

**Comment by m-reuter** [comment]
Back in the old days, when docker still used docker-machine (which again created a virtual machine using VirtualBox) this probably worked. Now that docker runs more natively on the Mac via the Hypervisor Framework, USB passthrough stopped working. 

You could try to
- either do what I did and use VirtualBox with Ubuntu and install deCONZ in that VM 
- or if you want to stick with docker, you can tell it to go through docker-machine instead of Hypervisor. see for example here: https://milad.ai/docker/2018/05/06/access-usb-devices-in-container-in-mac.html 

If anyone gets USB passthrough working with Appels Hypervisor Framework, let us know.

**Comment by JayStringer** [comment]
I went option number 3, running docker in an Ubuntu Server VM. I've only got the Hue Dimmer switches to test, but they seem to be working fine after a small amount of faffing. Bit of a shame it doesn't work natively on MacOS, but at least the VSCode remote extension is really good :)

Starting to miss hass.io on the Pi lol

**Comment by marthoc** [comment]
Closing this given the age of the issue, please open a new issue if this is still relevant.
