### ISSUE TITLE
Option for deCONZ X11 GUI with external X Server possible?

### ISSUE THREAD

**Issue by felixstorm** [marthoc/docker-deconz#15]
For debugging purposes, it would sometimes be helpful to be able to use the X11 UI of deCONZ together with an external X server e.g. on my (Windows) development PC.  
Unfortunately I don’t have enough Linux knowledge to estimate wether it would be just as simple as an option to not use `-platform minimalˋ or wether a lot more changes would be necessary for this?

Thanks,  
Felix

**Comment by manup** [comment]
If you use the official image you can log in remotely with the realVNC client.
It needs the deconz-gui version running though. Note the official image runs an X server but doesn't need a monitor attached.

**Comment by felixstorm** [comment]
Yes, that's exactly what I had used before. Then I added Home Assistant and it's very convenient to run both independently on one Raspberry Pi and even more convenient by the help of the the hassio add-on system and this add-on.  
But sometimes I miss the GUI, e.g. for OTA, querying attributes etc. and was hoping to be able to do this also in a headless docker container with an external X server.

@manup - It should generally be possible to run deCONZ headless without a local X server but with a remote one, shouldn't it? But I would most likely need more packages/libraries than are included in this image and would also need to configure the docker image for the socket/network connections for X11?  
From googling for X clients inside docker in general I saw that I will probably also need to deal with Xauthority, but that is independent of deCONZ.

Another idea (although most likely more performance hungry) seems to be to just include a (fake) display and a vnc server inside the image as outlined [here](https://stackoverflow.com/a/16311264), but this probably is outside of the scope of this project...

Thanks,  
Felix

**Comment by felixstorm** [comment]
@marthoc - Perfect, thank you!

**Comment by oscar-b** [comment]
Anyone who took a stab at this? As far as I know, the official RPI image from Dresden Electronics ships with a VNC server setup, maybe inspiration could be gathered from there.

There's also some base images on Docker Hub for running GUI applications, which might be interesting to look at.

**Comment by chimpy** [comment]
Hey guys,

I installed this docker image to get myself up and running with the ConBee.

I'm trying to add soft turn on/offs for my Osram lights and I think I need the "real" GUI rather than the webUI. What is the best way to go about this?

Thanks!
