### ISSUE TITLE
Possibility to use RealVNC account

### ISSUE THREAD

**Issue by Krocko** [marthoc/docker-deconz#152]
Is it possible to add an option to use an RealVNC Account?

**Comment by volschin** [comment]
What do you mean with RealVNC Account? I use RealVNC Viewer without problems.

**Comment by Krocko** [comment]
Yes it works well. 
If you have a RealVNC Account, you can login with your RealVNC email and password. 
So you have access over the internet.

**Comment by marthoc** [comment]
At the moment, I'm going to say no.

**Comment by marthoc** [comment]
Closing this given the age of the issue, please open a new issue if this is still relevant.
