### ISSUE TITLE
Variables seem not to be set using docker-compose

### ISSUE THREAD

**Issue by Xento** [marthoc/docker-deconz#158]
It seems that setting the environment variables are not set when they are specified in the docker-compose.yml.
I'm running docker on a synology nas and with all other containers like openhab etc. setting the variables works.

**Comment by volschin** [comment]
There is a known problem with the docker update to 18.9.03 on synology regarding docker-compose. Read the synology forums for this.

**Comment by Xento** [comment]
Ah ok.
But I think this issue was even with docker 17.x
I updates to docker 18 a few weeks ago and before I had the same problem.

**Comment by volschin** [comment]
No, the 17.x version was fine regarding environment variables. As I know some users switch back to 17.x to resove the problems.

**Comment by Xento** [comment]
https://github.com/oznu/docker-homebridge/issues/227#issuecomment-531165177
I will try the new version.

**Comment by Xento** [comment]
I can confirm that the new Version (Build 506 instead of 505) works now

**Comment by volschin** [comment]
https://usdl.synology.com/download/Package/spk/Docker/18.09.0-0506/
