### ISSUE TITLE
Combee Stick Update is incomplete

### ISSUE THREAD

**Issue by daendaen** [marthoc/docker-deconz#160]
Hi,

i have a big Problem, i try to make a Update of my Conbee Stick. The process is incomplete and now the USB Stick is recognized only a few seconds, than for a few seconds not recognized, then for a few seconds recognized and so on....

Can anybody help me

Greetings

**Comment by manup** [comment]
Please try step 6. from the following guide (if possible on a native system).

https://phoscon.de/en/support#conbee2-connection-issues

    sudo GCFFlasher_internal -d /dev/ttyACM0 -t 60 \
         -f /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26490700.bin.GCF

The `-t` parameter should ensure that the updater catches the bootloader.

More guides for other platforms can be found here:
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually
