### ISSUE TITLE
Run as non root user. 

### ISSUE THREAD

**Issue by chilledhobbit** [marthoc/docker-deconz#161]
I can't run the container with another user.
I have added "user: 1000:1000" to my compose file, but that doesn't work.
It's working with all my other containers, so is it something special with this one?

**Comment by marthoc** [comment]
Probably your user doesn’t have access to the USB/serial device. Have you added your user to the docket and dialout groups?

**Comment by chilledhobbit** [comment]
Yes, my user is added to both groups. I had the same problem with Home Assistant, but it did work when I added:

> group_add: 20

to the compose file. But no succes with Deconz.

I've found some differences in the logs.

This is the log when running with root:

> 21:13:08:955 HTTP Server listen on address 0.0.0.0, port: 80, root: /usr/share/deCONZ/webapp/,
21:13:09:225 CTRL. 3.16.221:13:09:271 ZCLDB init file /root/.local/share/dresden-elektronik/deCONZ/zcldb.txt,
21:13:09:324 GW sd-card image version file does not exist: /root/.local/share/dresden-elektronik/deCONZ/gw-version
21:13:09:374 started websocket server at port 443

And this is when running with user 1000:

> 21:01:42:164 HTTP Server listen on address 0.0.0.0, port: 8090, root: /usr/share/deCONZ/webapp/,
21:01:42:165 CTRL. 3.16.221:01:42:202 ZCLDB init file /.local/share/dresden-elektronik/deCONZ/zcldb.txt,
21:01:42:251 GW sd-card image version file does not exist: /.local/share/dresden-elektronik/deCONZ/gw-version,
21:01:42:253 started websocket server at port 8088,
21:01:42:253 create default username and password,

**Comment by volschin** [comment]
Seems your user hasn‘t assigned a homedir and so $HOME is empty.

**Comment by chilledhobbit** [comment]
My user has a homedir.

And with the ports, there is no need for me to run with 80 and 443, in fact, I can access to port 8090 and deconz is running. But the problem is it will do a new setup from scratch, even if the volume binds to the config files are correct. So where do it save the new setup? 🤷‍♂️

**Comment by marthoc** [comment]
Just commenting on this before closing the issue - deCONZ is meant to be run with root privileges, so I do not see changing the fact that it runs as the root user in the docker container any time soon.
