### ISSUE TITLE
Cant connect to Web UI: HTTP 413

### ISSUE THREAD

**Issue by c3g0** [marthoc/docker-deconz#163]
I have some problems setting up the Raspbee Module with the Docker Container
Its running on my headless rpi 3B+ raspbian buster.

I added 
```
enable_uart=1
dtoverlay=pi3-miniuart-bt
to my /boot/config.txt
```

And started with: `docker run -d --restart=always --name=deconz -p 1337:1337 -p 4443:4443 -v /opt/deCONZ:/root/.local/share/dresden-elektronik/deCONZ --device=/dev/ttyAMA0 -e DECONZ_DEVICE=/dev/ttyAMA0 -e DECONZ_WEB_PORT=1337 -e DECONZ_WS_PORT=4443 -e DEBUG_INFO=1 -e DEBUG_APS=1 -e DEBUG_ZCL=1 -e DEBUG_ZDP=1 -e DEBUG_OTAU=1 marthoc/deconz
`
Here ist my log File:
```
[marthoc/deconz] Starting deCONZ...,
[marthoc/deconz] Current deCONZ version: 2.05.69,
[marthoc/deconz] Web UI port: 1337,
[marthoc/deconz] Websockets port: 4443,
[marthoc/deconz] VNC Disabled,
libpng warning: iCCP: known incorrect sRGB profile,
This plugin does not support propagateSizeHints(),
This plugin does not support propagateSizeHints(),
This plugin does not support propagateSizeHints(),
22:14:37:135 HTTP Server listen on address 0.0.0.0, port: 1337, root: /usr/share/deCONZ/webapp/,
22:14:37:150 CTRL. 3.16.222:14:37:284 dev /dev/ttyAMA0,
22:14:37:284 COM: /dev/ttyAMA0 / serialno: ,
22:14:37:284 COM: --dev: /dev/ttyAMA0 (RaspBee),
22:14:37:284 ZCLDB init file /root/.local/share/dresden-elektronik/deCONZ/zcldb.txt,
22:14:37:687 parent process /bin/sh,
22:14:37:688 gw run mode: docker,
22:14:37:688 GW sd-card image version file does not exist: /root/.local/share/dresden-elektronik/deCONZ/gw-version,
22:14:37:688 sd-card cid: 035344534331323880ffffffff013227,
22:14:37:711 DB sqlite version 3.16.2,
22:14:37:713 DB PRAGMA page_count: 30,
22:14:37:713 DB PRAGMA page_size: 4096,
22:14:37:713 DB PRAGMA freelist_count: 0,
22:14:37:713 DB file size 122880 bytes, free pages 0,
22:14:37:714 DB PRAGMA user_version: 6,
22:14:37:714 DB cleanup,
22:14:37:717 DB create temporary views,
22:14:37:742 don't close database yet, keep open for 900 seconds,
22:14:37:751 started websocket server at port 4443,
22:14:37:772 found node plugin: libde_rest_plugin.so - REST API Plugin,
22:14:37:779 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin,
22:14:37:808 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin,
22:14:37:850 dev /dev/ttyAMA0,
22:14:37:850 COM: /dev/ttyAMA0 / serialno: ,
22:14:37:850 COM: --dev: /dev/ttyAMA0 (RaspBee),
22:14:38:065 Device firmware version 0x26050500,
22:14:38:085 unlocked max nodes: 200,
22:14:38:086 scan skip host .2,
22:14:38:282 Device protocol version: 0x0103,
```

**Comment by marthoc** [comment]
If you omit the -p directives and just include --net=host (I know you may not want to do that permanently but just to test), does it work (can you access the webUI at ip.ad.dr.ess:1337)? Keep in mind that you will still need to leave the env vars DECONZ_WEB_PORT and DECONZ_WS_PORT for this to work.

**Comment by c3g0** [comment]
I changed the ports to 4080, at first it didnt worked, but now I came back and I could connect to the Gateway.

`docker run -d --restart=always --name=deconz -p 4080:4080 -p 4443:4443 -v /opt/deCONZ:/root/.local/share/dresden-elektronik/deCONZ --device=/dev/ttyAMA0 -e DECONZ_DEVICE=/dev/ttyAMA0 -e DECONZ_WEB_PORT=4080 -e DECONZ_WS_PORT=4443 -e DEBUG_INFO=1 -e DEBUG_APS=1 -e DEBUG_ZCL=1 -e DEBUG_ZDP=1 -e DEBUG_OTAU=1 marthoc/deconz`
