### ISSUE TITLE
IKEA OTAU script on startup

### ISSUE THREAD

**Issue by tubalainen** [marthoc/docker-deconz#169]
The OTAU works great with this version of docker deconz.

Would it be possible to run the IKEA FW downloader script on startup and place the files in the ~/otau folder?

#168

**Comment by tubalainen** [comment]
Have updated the Readme file. Here is the PR: #168

**Comment by marthoc** [comment]
I’m not crazy about the idea of including the OTAU downloader in this image. You can always download the files manually, then mount a host folder containing the otau files into the container at /root/otau.

**Comment by tubalainen** [comment]
> I’m not crazy about the idea of including the OTAU downloader in this image. You can always download the files manually, then mount a host folder containing the otau files into the container at /root/otau.

Ok, fair enough :) .. Let me try to update my PR/Readme.md with instructions according to your recommendation.

**Comment by wmn79** [comment]
There is a feature merged in the deconz repo that might be usefull here. See this issue: [https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1606](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1606)

**Comment by duffbeer2000** [comment]
I made a little container out of it and included the osram firmwares too.
duffbeer2000/deconz_fw_downloader:latest
It downloads the firmware files in the folder: /otau
So if you mount a local Folder to that folder you have the files there.
Next step is to mount that local folder to the /root/otau folder in the deconz Container, then deconz recognizes them.
At the moment it loads all the firmware files. I will add a switch and a description to the container so you are able to decide if you need ikea, osram, or both firmware files.
After the download the container stops, so you have to start it maybe once a week to check if there are new firmware files.
On Github: https://github.com/duffbeer2000/deconz_fw_downloader

**Comment by lubbertkramer** [comment]
> I made a little container out of it and included the osram firmwares too.
> duffbeer2000/deconz_fw_downloader:latest
> It downloads the firmware files in the folder: /otau
> So if you mount a local Folder to that folder you have the files there.
> Next step is to mount that local folder to the /root/otau folder in the deconz Container, then deconz recognizes them.
> At the moment it loads all the firmware files. I will add a switch and a description to the container so you are able to decide if you need ikea, osram, or both firmware files.
> After the download the container stops, so you have to start it maybe once a week to check if there are new firmware files.
> On Github: https://github.com/duffbeer2000/deconz_fw_downloader

Looking great, unfortunately i didn't got it working. Hope you can support :)  -> https://github.com/duffbeer2000/deconz_fw_downloader/issues/1

**Comment by DerOetzi** [comment]
I'm not a fan of running on ota download automaticaly too, because as there a more and more different vendors are coming up with ota posibbilities for example osram, each startup of the container  will take a long time. But I want to suggest to include known download bash scripts inside the container. This would give users the possibility to manually start download inside the container without having to install additional packages on the docker host and to mount volumes for the "corner case" Firmware Update. The user can then use a docker command to start download for example

`docker exec -it deconz /ikea-otau-download.sh`
or
`docker exec -it deconz /ledvance-otau.sh`

Maybe I can suggest a PR this evening for further discussion

**Comment by Gizmo-Ger** [comment]
I used the docker pull but the OTA plugin can´t access the root/otau folder. How do I mount the folder so the OTAU plugin can access the files?

**Comment by marthoc** [comment]
@DerOetzi The problem with including known scripts inside the image is that the files would then likely get downloaded inside the image (unless the user knows to mount a volume) and would get removed when the user e.g. pulls the new image. I feel like this introduces a new level of complexity that is not worth supporting.
