### ISSUE TITLE
Firmware not connected issue

### ISSUE THREAD

**Issue by youlib** [marthoc/docker-deconz#170]
Hi,
on a HassOS 3.5, with RaspBee, and 2.05.69 version of Phoscon,
I get a "firmware not connected" image on the Gateway tab.
Any ideas? I know that the security token is not set up as well, but I suspect that I first need to fix the firmware issue.

Logs: 

starting version 232
[06:51:54] INFO: Starting the deCONZ gateway...
[06:51:54] INFO: Running the deCONZ OTA updater...
[06:51:54] INFO: Running the IKEA OTA updater...
[06:51:54] INFO: Running Hass.io discovery task...
{"uuid":"be1bfd9c00974ee397b9269d55577824"}
[06:51:54] INFO: Success send discovery information to Home Assistant
[06:51:54] INFO: deCONZ is set up and running!
libpng warning: iCCP: known incorrect sRGB profile
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
06:51:54:873 HTTP Server listen on address 0.0.0.0, port: 40850, root: /usr/share/deCONZ/webapp/
06:51:54:898 CTRL. 3.16.206:51:54:969 dev /dev/ttyAMA0
06:51:54:969 COM: /dev/ttyAMA0 / serialno: 
06:51:54:969 COM: --dev: /dev/ttyAMA0 (RaspBee)
06:51:54:969 ZCLDB init file /data/.local/share/dresden-elektronik/deCONZ/zcldb.txt
06:51:55:080 parent process bash
06:51:55:080 gw run mode: docker/hassio
06:51:55:080 GW sd-card image version file does not exist: /data/.local/share/dresden-elektronik/deCONZ/gw-version
06:51:55:080 sd-card cid: 035344534e36344780ffffffff013500
06:51:55:081 DB sqlite version 3.16.2
06:51:55:082 DB PRAGMA page_count: 30
06:51:55:082 DB PRAGMA page_size: 4096
06:51:55:083 DB PRAGMA freelist_count: 0
06:51:55:083 DB file size 122880 bytes, free pages 0
06:51:55:083 DB PRAGMA user_version: 6
06:51:55:083 DB cleanup
06:51:55:083 DB create temporary views
06:51:55:088 don't close database yet, keep open for 900 seconds
06:51:55:089 started websocket server at port 40860
06:51:55:095 found node plugin: libde_rest_plugin.so - REST API Plugin
06:51:55:098 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
06:51:56:350 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
06:51:56:375 dev /dev/ttyAMA0
06:51:56:375 COM: /dev/ttyAMA0 / serialno: 
06:51:56:375 COM: --dev: /dev/ttyAMA0 (RaspBee)
06:51:56:426 New websocket 192.168.8.120:59184 (state: 3) 
06:51:56:902 device state timeout ignored in state 2
06:51:57:852 device state timeout ignored in state 2
06:51:58:818 device state timeout ignored in state 2
06:51:59:490 New websocket 192.168.8.120:59187 (state: 3) 
06:51:59:818 device state timeout ignored in state 2
06:52:00:358 dev /dev/ttyAMA0
06:52:00:561 discovery network reply error: Error transferring http://dresden-light.appspot.com/discover - server replied: Service Unavailable
06:52:00:818 device state timeout ignored in state 2
06:52:01:817 device state timeout (handled)
06:52:02:215 New websocket 192.168.8.120:59188 (state: 3) 
06:52:02:317 void zmMaster::handleStateIdle(zmMaster::MasterEvent) not connected goto OFF state
06:52:02:317 device state timeout ignored in state 1
06:52:02:818 wait reconnect 15 seconds
06:52:03:355 New websocket 192.168.8.111:57690 (state: 3) 
06:52:03:818 wait reconnect 14 seconds
06:52:04:817 wait reconnect 13 seconds
06:52:05:818 wait reconnect 12 seconds
06:52:06:818 wait reconnect 11 seconds
06:52:07:818 wait reconnect 10 seconds
06:52:08:817 wait reconnect 9 seconds
06:52:09:818 wait reconnect 8 seconds

**Comment by marthoc** [comment]
@youlib The Hass.io addon is a completely separate project from this Docker image and you will need to open an Issue on the repo for the Hass.io addons: https://github.com/home-assistant/hassio-addons.

**Comment by youlib** [comment]
Hi Mark,
I understand, I was under the wrong impression that the issue was within
the docker,
but, dah, that was stupid :D Thank you for your reply and for the nice
docker image!

youlib

**Comment by marine1988** [comment]
im facing same issue any tip?
