### ISSUE TITLE
deCONZ gateway version 2.5.70

### ISSUE THREAD

**Issue by giss69** [marthoc/docker-deconz#171]
Hello,

wenn is an update for docker to version 2.5.70 to expect?

Thank you

**Comment by tubalainen** [comment]
Doesnt look like it has been released yet... This repo is just a docker adaptation of the deconz-rest-plugin that can be found here, and as fas as  I can see they are still at version .69 https://github.com/dresden-elektronik/deconz-rest-plugin/releases

**Comment by giss69** [comment]
strange, homebridge-hue plugin requiers .70 Version. that's why i asking.

**Comment by manup** [comment]
The release files are currently  only in the APT-repository, the copies used by the Dockerfile are coming tomorrow and finally this step will be automated so it becomes faster the next time.

**Comment by bastshoes** [comment]
2.05.70 is availible :tada:
