### ISSUE TITLE
docker: no matching manifest for linux/386: 

### ISSUE THREAD

**Issue by Klagio** [marthoc/docker-deconz#175]
Hi I wish to install Marthoc docker image, in a proxmox VE on a Intel NUC

Currently I created a Lubuntu VM and everything works well, while trying to install docker-deconz I receive this error. Is there a way to install  docker-deconz or what shall I do?
```

nuc-lubuntu:~$ sudo docker run -d    --name=deconz    --net=host    --restart=always    -v /etc/localtime:/etc/localtime:ro    -v ~/.local/share/dresden-elektronik/deCONZ:/root/.local/share/dresden-elektronik/deCONZ    --device=/dev/ttyUSB0    marthoc/deconz
Unable to find image 'marthoc/deconz:latest' locally
latest: Pulling from marthoc/deconz
docker: no matching manifest for linux/386 in the manifest list entries.
See 'docker run --help'.


```

**Comment by volschin** [comment]
This docker image doesn‘t support i386 architecture as you can read in the readme.
Normally on Intel NUC it should be possible to use amd64 architecture. So there should be a problem with your installation, perhaps proxmox.

**Comment by marthoc** [comment]
@volschin is correct. You probably selected a 32 bit Lubuntu image. You will need to use 64 bit.
