### ISSUE TITLE
Not Persisting Data

### ISSUE THREAD

**Issue by warllo54** [marthoc/docker-deconz#177]
I cannot get the deconz container to store the data where specified. It will always create a new volume regardless of whether it's mapped to a volume or a directory. Here is my config. Hoping someone can point me in the correct direction.

https://pastebin.com/HC1b3GsH

`version: '2'
services:
    zigbee2mqtt:
      container_name: deconz
      image: marthoc/deconz
      restart: always
      environment:
        - PUID = 1001
        - PGID = 1001 
        - TZ=America/Chicago
        - DECONZ_VNC_MODE=1
        - DECONZ_VNC_PORT=5900
        - DECONZ_VNC_PASSWORD=******
      volumes:
        - /apps/deconz:/root/.local/share/dresden-elektronik/deCONZ \
      devices:
        - /dev/ttyACM0
      network_mode: host`

**Comment by o0shojo0o** [comment]
remove the **\\** at the end of your volumes mount.

It should look like this:
~~~
volumes: 
    - /apps/deconz:/root/.local/share/dresden-elektronik/deCONZ
~~~

**Comment by warllo54** [comment]
Embarrassing! I can't believe I missed that. I thought I was going insane. Thanks for the help.
