### ISSUE TITLE
Synology Docker GUI

### ISSUE THREAD

**Issue by alexvandervegt** [marthoc/docker-deconz#18]
Hi,

I am currently using your image with the Synology Docker GUI app. Unfortunately, this app does not have an opportunity to add the --device parameter. So I gave the docker container root capabilities.

How can I configure it for deconz to find my conbee in the usb port?

**Comment by marthoc** [comment]
Please try to add the Conbee device as a normal volume mount. You’ll have to find out what the Conbee is detected as on your Synology.

**Comment by alexvandervegt** [comment]
I am trying to add it to the command line now and trying to figure out which port the conbee is.

Any clue?


--device=/dev/ttyUSB0
--


<img width="619" alt="screen shot 2018-04-29 at 16 43 14" src="https://user-images.githubusercontent.com/3672692/39407812-8b1cec0a-4bcc-11e8-84f3-4765d46a63d9.png">

**Comment by marthoc** [comment]
Try:
`ls -l /dev | grep tty`

That should return at least one device, probably /dev/ttyUSB0 if you don’t have more than one USB serial device installed.

**Comment by alexvandervegt** [comment]
Did not see your hassio addon before, nice work! using this now!
