### ISSUE TITLE
Not working in docker - but windows

### ISSUE THREAD

**Issue by ubid** [marthoc/docker-deconz#183]
Hi.
I run in docker, but not working.
I tried from hassio.io plugin, and try with deconz container from https://hub.docker.com/r/marthoc/deconz.

(docker is runned from qnap virutal ubuntu server, with portainer ) 

The log is the following:

06:49:18:671 DB file size 122880 bytes, free pages 0,
06:49:18:672 DB PRAGMA user_version: 6,
06:49:18:672 DB cleanup,
06:49:18:688 DB create temporary views,
06:49:18:714 don't close database yet, keep open for 900 seconds,
06:49:18:718 started websocket server at port 443,
06:49:18:927 GW firmware update not supported on x86 linux headless,
06:49:18:930 found node plugin: libde_rest_plugin.so - REST API Plugin,
06:49:18:934 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin,
06:49:18:951 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin,
06:49:19:017 COM: --dev: /dev/TTYACM0 (RaspBee),
This plugin does not support propagateSizeHints(),
This plugin does not support propagateSizeHints(),
06:49:19:201 wait reconnect 15 seconds,
06:49:19:264 COM: --dev: /dev/TTYACM0 (RaspBee),
06:49:20:006 wait reconnect 14 seconds,
......
06:49:24:084 discovery network reply error: Error transferring http://dresden-light.appspot.com/discover - server replied: Service Unavailable,
06:49:25:025 wait reconnect 9 seconds,
....
06:49:33:024 wait reconnect 1 seconds,
06:49:33:089 COM: --dev: /dev/TTYACM0 (RaspBee),
06:49:34:024 wait reconnect 15 seconds,
06:49:34:103 COM: --dev: /dev/TTYACM0 (RaspBee),
06:49:35:024 wait reconnect 14 seconds,
....
06:49:44:275 failed to reconnect to network try=1,
....
06:49:48:098 COM: --dev: /dev/TTYACM0 (RaspBee),
06:49:49:026 wait reconnect 15 seconds,
06:49:49:251 COM: --dev: /dev/TTYACM0 (RaspBee),
06:49:49:524 failed to reconnect to network try=2,
.......
06:49:54:524 failed to reconnect to network try=3,
06:49:55:024 wait reconnect 9 seconds,
.....
06:49:59:524 failed to reconnect to network try=4,
.....
06:50:03:024 wait reconnect 1 seconds,
06:50:03:089 COM: --dev: /dev/TTYACM0 (RaspBee),
06:50:04:026 wait reconnect 15 seconds,
06:50:04:164 COM: --dev: /dev/TTYACM0 (RaspBee),
06:50:04:524 failed to reconnect to network try=5,
06:50:05:024 wait reconnect 14 seconds,
...
06:50:09:524 failed to reconnect to network try=6,
06:50:10:025 wait reconnect 9 seconds,
....
06:50:14:524 failed to reconnect to network try=7,
06:50:15:024 wait reconnect 4 seconds,
.....
06:50:18:094 COM: --dev: /dev/TTYACM0 (RaspBee),
06:50:19:027 wait reconnect 15 seconds,
06:50:19:257 COM: --dev: /dev/TTYACM0 (RaspBee),
06:50:19:526 failed to reconnect to network try=8,
06:50:20:024 wait reconnect 14 seconds,
....
06:50:24:524 failed to reconnect to network try=9,
06:50:25:024 wait reconnect 9 seconds,

If i try to run from my win 10, is correctly worked.
I try to update firm with win 10.
Maybe success, but no result in screen.
I try to connect in docker again, the result was same :( 

I try to run firm update from docker, but not works.

Please help me.

**Comment by marthoc** [comment]
Not enough info to troubleshoot. What do you mean “not working”? Can’t access the Web UI, can’t connect to the USB/raspbee device? More details and please reopen if you still need help.
