### ISSUE TITLE
cannot open webapp or phoscon app

### ISSUE THREAD

**Issue by IIIdefconIII** [marthoc/docker-deconz#184]
Hi,

Im new with deconz, just order the stick and could make a connection to the device. Im using synology docker.

Im connecting with vnc, is there another way? I dont think so... not sure do

Whatever i do i cannot click on phoscon app or webapp, when i click, i excpect a window but nothing happens. if i know where i can find more logs please let me know:

![image](https://user-images.githubusercontent.com/9917659/70377014-7f598b00-190f-11ea-99d5-5e661b3c5606.png)

EDIT: i did found this in the logs:

![image](https://user-images.githubusercontent.com/9917659/70377028-c2b3f980-190f-11ea-9a48-f29acc79eca0.png)

so should there be a webbrowser included in the dock?

EDIT2: so i found out that i am able to launch the webbrowser from my pc instead:
http://10.3.1.2:8090/pwa/login.html

lets put this in the documentation ?

**Comment by marthoc** [comment]
There is no web browser included in this image and there won’t be. Phoscon is a web app and must be accessed from a web browser on a pc on your network.
