### ISSUE TITLE
deconz conects to wrong websocket and can't start

### ISSUE THREAD

**Issue by bibicu123** [marthoc/docker-deconz#186]
Last day I had to restart the Ubuntu server and thus restarted the marthoc/deconz container.
After restart deconz could not connect discover any lights and sensors.

Looking at the log I see this suspect message:

New websocket 10.11.1.20:59374 (state: 3)

The problem is that 10.11.1.20 is the IP address of my laptop and NOT the IP address of the deconz machine.

This does not seem right. Here is the relevant log:

[marthoc/deconz] Current deCONZ version: 2.05.70
[marthoc/deconz] Web UI port: 80
[marthoc/deconz] Websockets port: 443
[marthoc/deconz] VNC port: 5900
Killing Xtigervnc process ID 24... which was already dead
Cleaning stale pidfile '/root/.vnc/ubu:0.pid'!
Cleaning stale x11 lock '/tmp/.X0-lock'!
Cleaning stale x11 lock '/tmp/.X11-unix/X0'!

New 'ubu:0 (root)' desktop at :0 on machine ubu

Starting applications specified in /etc/X11/Xvnc-session
Log file is /root/.vnc/ubu:0.log

Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /root/.vnc/passwd ubu:0 to connect to the VNC server.

13:08:15:017 HTTP Server listen on address 0.0.0.0, port: 80, root: /usr/share/deCONZ/webapp/
13:08:15:114 CTRL. 3.16.213:08:15:272 ZCLDB init file /root/.local/share/dresden-elektronik/deCONZ/zcldb.txt
13:08:15:482 parent process /bin/sh
13:08:15:482 gw run mode: docker
13:08:15:482 GW sd-card image version file does not exist: /root/.local/share/dresden-elektronik/deCONZ/gw-version
13:08:15:503 DB sqlite version 3.16.2
13:08:15:504 DB PRAGMA page_count: 37
13:08:15:504 DB PRAGMA page_size: 4096
13:08:15:504 DB PRAGMA freelist_count: 2
13:08:15:504 DB file size 151552 bytes, free pages 2
13:08:15:504 DB PRAGMA user_version: 6
13:08:15:504 DB cleanup
13:08:15:505 DB create temporary views
13:08:15:580 don't close database yet, keep open for 900 seconds
13:08:15:582 started websocket server at port 443
13:08:15:587 found node plugin: libde_rest_plugin.so - REST API Plugin
13:08:15:590 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
13:08:15:600 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
13:08:15:798 New websocket 10.11.1.20:59374 (state: 3)
13:08:16:360 device state timeout ignored in state 2
13:08:17:360 device state timeout ignored in state 2
13:08:17:587 New websocket 10.11.1.20:59378 (state: 3)
13:08:18:361 device state timeout ignored in state 2
13:08:19:361 device state timeout ignored in state 2
13:08:20:362 device state timeout ignored in state 2
13:08:21:258 Announced to internet https://phoscon.de/discover
13:08:21:361 device state timeout (handled)
13:08:21:861 void zmMaster::handleStateIdle(zmMaster::MasterEvent) not connected goto OFF state
13:08:21:861 device state timeout ignored in state 1
13:08:22:361 wait reconnect 15 seconds
13:08:23:361 wait reconnect 14 seconds
13:08:24:362 wait reconnect 13 seconds

**Comment by tubalainen** [comment]
"device state ignored" ... The USB dongle has most likely changed port in the OS.

Mine "jumps around" as well during restarts...
type 'dmesg | grep ttyUSB' and look where its at. If unsure unplug and re-plug it again and just run 'dmesg' to see what "ttyUSBx' it assigned.

It is recommended to "bind" a USB device and that way it will always be the same regardless of reboots or dis/reconnects. For info have a look here: https://unix.stackexchange.com/questions/66901/how-to-bind-usb-device-under-a-static-name

Also make sure that you point to the device according to the documentation. I use the two following attributes for that.

Here is my magic "docker run line" for your reference.
'docker run -d --name=deconz -p 8882:80 -p 4434:4434 -p 5900:5900  -v /usr/share/dockers/deconz/otau:/root/otau -v /usr/share/dockers/deconz:/root/.local/share/dresden-elektronik/deCONZ -v /etc/localtime:/etc/localtime:ro --device=/dev/ttyUSB1 -e DECONZ_DEVICE=/dev/ttyUSB1 -e DECONZ_WEB_PORT=80 -e DECONZ_WS_PORT=4434 -e DECONZ_VNC_MODE=1 -e DECONZ_VNC_DISPLAY=0 -e DECONZ_VNC_PASSWORD=secret -e DECONZ_VNC_PORT=5900 marthoc/deconz:latest'

**Comment by bibicu123** [comment]
Looking at kernel.log I realized the issue was due to  Conbee getting disconnected and jumping from ttyACM0 to ttyACM1 and back.

Why that happened I have no idea, but after restarting container (not the server) everything went well.

Dec 11 13:08:17 ubu kernel: [   23.936174] usb 2-2.1: USB disconnect, device number 5
Dec 11 13:08:17 ubu kernel: [   23.939168] cdc_acm 2-2.1:1.0: failed to set dtr/rts
Dec 11 13:08:18 ubu kernel: [   24.619346] usb 2-2.1: new full-speed USB device number 6 using uhci_hcd
Dec 11 13:08:18 ubu kernel: [   25.157115] usb 2-2.1: New USB device found, idVendor=1cf1, idProduct=0030
Dec 11 13:08:18 ubu kernel: [   25.157119] usb 2-2.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Dec 11 13:08:18 ubu kernel: [   25.157120] usb 2-2.1: Product: ConBee II
Dec 11 13:08:18 ubu kernel: [   25.157122] usb 2-2.1: Manufacturer: dresden elektronik ingenieurtechnik GmbH
Dec 11 13:08:18 ubu kernel: [   25.157123] usb 2-2.1: SerialNumber: XXXX
Dec 11 13:08:18 ubu kernel: [   25.182225] cdc_acm 2-2.1:1.0: ttyACM1: USB ACM device
Dec 11 13:08:18 ubu snapd[1074]: hotplug.go:199: hotplug device add event ignored, enable experimental.hotplug
Dec 11 13:11:40 ubu kernel: [  226.722313] usb 2-2.1: USB disconnect, device number 6
Dec 11 13:11:42 ubu kernel: [  228.315465] usb 2-2.1: new full-speed USB device number 7 using uhci_hcd
Dec 11 13:11:42 ubu kernel: [  228.851378] usb 2-2.1: New USB device found, idVendor=1cf1, idProduct=0030
Dec 11 13:11:42 ubu kernel: [  228.851381] usb 2-2.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Dec 11 13:11:42 ubu kernel: [  228.851383] usb 2-2.1: Product: ConBee II
Dec 11 13:11:42 ubu kernel: [  228.851384] usb 2-2.1: Manufacturer: dresden elektronik ingenieurtechnik GmbH

**Comment by tubalainen** [comment]
Will post a issue to dresten for the log to print out a better error message when it cannot communicate with the transceiver (USB dongle) .. Its not that easy to figure out just by looking at the log.

I will steal your logfile as an example, hope thats ok. :)

**Comment by bibicu123** [comment]
Thanks again. I am closing the issue since it was the USB connection that failed.
