### ISSUE TITLE
Firmware update fails: raspberry pi4 + RaspBee + hass.io + deconz addon

### ISSUE THREAD

**Issue by panhans** [marthoc/docker-deconz#187]
Hi there,

I just want to update the firmware of my raspbee but I get following output. I followed every step like discribed. 

Hardware: 
- Raspberry Pi 4b (hassio 32Bit)
- RaspBee (current firmware version: 26050500)

Here is the whole log:

```
# docker run -it --rm --device=/dev/ttyAMA0 --privileged --cap-add=ALL -v /lib/m
odules:/lib/modules --entrypoint "/firmware-update.sh" marthoc/hassio-addon-deco
nz-armhf
-------------------------------------------------------------------
 
       marthoc/deconz Conbee/RaspBee Firmware Flashing Script
 
                       Version: 0.4
 
-------------------------------------------------------------------
 
Enter C for Conbee, R for RaspBee, or press Enter now to exit: R
 
-------------------------------------------------------------------
 
Firmware available for flashing:
 
deCONZ_ConBeeII_0x26480700.bin.GCF
deCONZ_ConBeeII_0x26490700.bin.GCF
deCONZ_Rpi_0x261f0500.bin.GCF
deCONZ_Rpi_0x26320500.bin.GCF
deCONZ_Rpi_0x26330500.bin.GCF
 
Enter the firmware file name from above, including extension,
or press Enter now to exit.
 
File Name : deCONZ_Rpi_0x26330500.bin.GCF
 
-------------------------------------------------------------------
 
Device: RaspBee
 
Firmware File: deCONZ_Rpi_0x26330500.bin.GCF
 
Are the above device and firmware values correct?
Enter Y to proceed, any other entry to exit: Y
 
Flashing...
 
GCFFlasher V3_05 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device RaspBee (RaspBee)
deCONZ firmware version 26050500
action: reset device RaspBee
action: update firmware after 2 ms
could not sync with bootloader
 
Flashing Error! Please re-run this script... 
```

**Comment by robidog** [comment]
Similar issue here, but it ends with the following: 

![image](https://user-images.githubusercontent.com/46966978/77579896-591a2400-6edb-11ea-9717-0424f4f789a1.png)

What am I doing wrong here?

**Comment by robidog** [comment]
Same issue here. 

![image](https://user-images.githubusercontent.com/46966978/77581905-d09d8280-6ede-11ea-8724-68650944b865.png)

Is this actually working for anyone?

**Comment by Wonkavator** [comment]
Having the same issue here. Would love to find a solution for that.

**Comment by robidog** [comment]
Looks like we have to wait for @marthoc to look into this. Update script is only tested on Debian-based distos but not on HassOS, which is a very much stripped down version of Linux.

**Comment by xavi-dev** [comment]
Not a fix but you can update the firmware outside the docker image: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually#update-in-raspbian

**Comment by robidog** [comment]
Yes but not on HassOS, where capabilities 'outside the docker image' are very limited. Only option is to physically remove RaspBee and update firmware in another Raspi. Or temporarily boot Raspbian and do the firmware update there. It's not a big issue but still not ideal. Just a limitation of using deCONZ Add-On with HassOS that I was not aware of.

**Comment by hmrc87** [comment]
Hi, I tried it inside the Docker image on my Raspi4 but it gives me the following

```
root@raspberrypi:/tmp# sudo GCFFlasher_internal -f deCONZ_Rpi_0x26350500.bin.GCF
/usr/bin/GCFFlasher_internal.bin: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/libwiringPi.so)
```

Since months I am unable to update my firmware :(((

**Comment by marthoc** [comment]
@hmrc87 - related to #228. Updates will be posted in that issue.

With respect to HassOS, I thought it may now be possible to update the device firmware through the web interface in that Add-On (possibly not). I have discontinued work on my Home Assistant deCONZ add-on. Those images are very out of date and I will be removing them from Docker Hub so that no further confusion is caused.
