### ISSUE TITLE
docker conbee1 "not connected" after update

### ISSUE THREAD

**Issue by davenbo** [marthoc/docker-deconz#188]
Hello I pulled the latest image for my marthoc/deconz for the first time in a while.
My phoscon app is now 2.05.71 from nov 17th 2019 but after the update **my conbee1 is now listed as not connected**.

**I start the container with the following command:**
`docker run -d --name=deconz --net=host --restart=always -v /opt/docker/deconz:/root/.local/share/dresden-elektronik/deCONZ  --device=/dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DM01DVB5-if00-port0 -e DECONZ_VNC_MODE=1 -e DECONZ_WEB_PORT=8080 marthoc/deconz `

**And when I list /dev/serial/by-id** i see that very same device right there.

Any suggestion what to try? 
Thanks in advance.

**Comment by D34DC3N73R** [comment]
Can you try `--device=/dev/ttyUSB0` 

According to the [setup guide](https://github.com/marthoc/docker-deconz#command-line-options) 
> by default ConBee = /dev/ttyUSB0, Conbee II = /dev/ttyACM0, RaspBee = /dev/ttyAMA0 or /dev/ttyS0

**Comment by davenbo** [comment]
Thanks; It works...

I mean, I feel stupid for not trying to revert it back to dev/ttyUSB0 since I considered the serial/by-id path "an upgrade" on my behalf, been having issues with devices swapping names and refering to the ID fixed it for me with the zwave stick in home assistant so just wanted to be consequent and do it in deconz as well... 

Why doesn't it work though? It should resolve to the same device, or it does in linux but not in the deconz-container for some reason...

Regardless, thanks for your reply.

**Comment by marthoc** [comment]
This should work, and I know many others have set up their device mapping with the by serial id.

**Comment by flexy2dd** [comment]
In some case, for example on synology, the mount point of USB change (especially if there is more than one usb device)
And on Synology udev deamon not work by default, i have make PR for add this feature for my synology https://github.com/marthoc/docker-deconz/pull/197

**Comment by marthoc** [comment]
Closing this given the age of the issue, please open a new issue if this is still relevant.
