### ISSUE TITLE
All is lost for no obvious reason (restart?)

### ISSUE THREAD

**Issue by Henkis** [marthoc/docker-deconz#189]
I seem to have lost all my devices, possibly when I restarted my docker host, I had this configuration for a year or so without problems before.

In the logs I get:
error APSDE-DATA.confirm: 0xA7 on task
max transmit errors for node 0xBADCAFFE last seen by neighbors 650 s
seems to be a zombie recv errors 6
GW firmware version: 0x26330500
GW firmware version is up to date: 0x26330500

I look at my historical configuration, I am on ID 17 now, my previous 16 have all had the same PANID and Network key (different versions over time of course) but the latest have a new PANID, channel and network key. I have tried to load the previous configuration but nothing seem to change.

Before finding this configuration difference I restarted everything again and cut the power to the Conbee, moved it physical  and so on.

**Comment by Henkis** [comment]
Ok, now I have restarted 10 times, backed configuration, changed channels and turned off power to devices for a few hours and now all of a sudden a older configuration seems to work, I reverted, it then complained about channel but after manually changing channel it works. I had done both before tho.

**Comment by marthoc** [comment]
Sounds like an issue with deCONZ, not this image specifically; open an issue here: https://github.com/dresden-elektronik/deconz-rest-plugin

**Comment by solsson** [comment]
@Henkis It looks like https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2273

**Comment by mycanaletto** [comment]
For me I just loose the 3 last device registered. Others devices (11) are present ! Any idea ?

In fact it seems that it happens on Xiaomi sensors that were previously paired with the GW Xiaomi, then removed from it.
I have just paired an Aqara sensor (opening) and I find it after restarting Deconz.
