### ISSUE TITLE
Even better hass.io integration

### ISSUE THREAD

**Issue by Kane610** [marthoc/docker-deconz#19]
Hi Mark!

Now with deCONZ component fully supporting config flows and with config flows allowing initiation from external parts, such as hass.io addons. It would be great to see this improved flow with your add-on.

https://developers.home-assistant.io/docs/en/config_entries_config_flow_handler.html

**Comment by Kane610** [comment]
So if you choose to install the addon, the addon should trigger the config flow. Similar to how the discovery flow works

**Comment by Kane610** [comment]
I don't know if it is even possible for the addon to automatically open to allow generation of new api key. That would be awesome

**Comment by marthoc** [comment]
Understood. I’ll look into this, if it’s possible to implement now I will add to the addon. I’ll also take a look at whether I can automate the opening of Phoscon to unlock the gateway but I’m not sure whether that’s possible yet...

**Comment by Kane610** [comment]
As its in the public documents it should work. Just holler if anything seems weird

**Comment by marthoc** [comment]
@Kane610 I'm all for adding this to the Add-on but I can't figure out how to do it. Does this need to be added to the deCONZ component in HA first? From the hass.io developer page it looks like there are two new config file options: "discovery" ("A list of services they this Add-on allow to provide for Home Assistant. Currently supported: mqtt") and "services" ("A list of services they will be provided or consumed with this Add-on. Format is service:function and functions are: provide (this add-on can provide this service), want (this add-on can use this service) or need(this add-on need this service to work correctly"). If you can help me make heads or tails of this I'm down for adding it!

**Comment by Kane610** [comment]
I'm gonna need to delve into this deeper as well. There are config flow steps needed for the component. I guess it is easiest if I implement those.

**Comment by Kane610** [comment]
Seems all parts are not even merged yet

https://github.com/home-assistant/hassio-addons/pull/427

**Comment by Kane610** [comment]
https://github.com/home-assistant/hassio/blob/dev/API.md#discovery

**Comment by Kane610** [comment]
**pvizeli Today at 12:55 PM:**
Is coming soon with a blog post @Robban also with examples on core repository

**Comment by marthoc** [comment]
@Mariusthvdb Definitely possible to use Conbee and the Add-on. Follow the instructions in the Readme, many people have it working.  If there is still a problem open a new issue and post the error log.

**Comment by Mariusthvdb** [comment]
I did... there’s no info for Hassio, only for docker Ha? Thx btw ;-)

**Comment by marthoc** [comment]
@Mariusthvdb here: https://github.com/marthoc/hassio-addons/tree/master/deconz

**Comment by marthoc** [comment]
@Kane610 - any progress on this from your end? I haven't dug into this yet, so I'm not sure what pieces are necessary from the HA component side to get this working. But, Pascal reached out to me recently about moving my deCONZ Add-on to the Core Add-ons repo, so I'm sure to get a lot of help from him on that front re enabling the new Hass.io features in the Add-on.

**Comment by Kane610** [comment]
I'm working on a PR for another component. This is among the next things to look at. I've talked with Pascal about this so I know where to look. Don't know all details yet though

**Comment by Kane610** [comment]
This is solved with the official hass.io addon now. I don't know if there is any plan to support this version of the addon much longer? But I guess it would just be to copy what was done for the other addon and it will work here as well.
