### ISSUE TITLE
How do you change 'power failure' modes and fade durations?

### ISSUE THREAD

**Issue by Webunity** [marthoc/docker-deconz#190]
I have the Docker Deconz running, all seems to work fine; paired about 10 Hue bulbs but i would like to change their power failure settings and for example how long it takes for a bulb to fade from one setting to another (currently it is a second i think).

I cant seem to find these settings in the GUI, but maybe i have to change it in the config in the docker image itself? The URL i am looking at starts with /pwa/index.html?...

**Comment by marthoc** [comment]
This is a question for the deCONZ repo, not here (this is the Docker image only): https://github.com/dresden-elektronik/deconz-rest-plugin
