### ISSUE TITLE
Firewall Ports

### ISSUE THREAD

**Issue by kmplngj** [marthoc/docker-deconz#192]
Hello,

you someone tell me if I have to open more ports for Deconz as 80, 443 and 5900? Do I have to open some for UPNP?

Thanks
Jan

**Comment by tubalainen** [comment]
> Hello,
> 
> you someone tell me if I have to open more ports for Deconz as 80, 443 and 5900? Do I have to open some for UPNP?
> 
> Thanks
> Jan

Hej Jan,

Deconz operates normally within your network. It is not needed to open any ports towards Internet to get Deconz to work. You should rather avoid exposing it.

Hope that answers your question.

**Comment by kmplngj** [comment]
Thanks, I don’t  mean the routers port forwarding. I mean the firewall of the Linux it is running on.

**Comment by tubalainen** [comment]
> Thanks, I don’t mean the routers port forwarding. I mean the firewall of the Linux it is running on.

Try to follow the examples in the readme to forward (point) the ports into the docker container. If you have a firewall setup on the Linux machine you might need to adjust your settings to suit the new 172.x subnet created by Docker.

**Comment by kmplngj** [comment]
I just found out that I have to open Port 80 & 443 for main functions, Port 5900 for VNC and 1900/udp for upnp support (e.g. Alexa). I opened the port on the Fedora VM my Deconz is running on.
