### ISSUE TITLE
Aqara Switch ZNCZ12LM registered as light

### ISSUE THREAD

**Issue by D34DC3N73R** [marthoc/docker-deconz#193]
Using ConBee II with deCONZ docker image on Ubuntu 18.04. I went through the steps to add a new switch, but it's automatically added as a light instead lumi.plug.maus01. Let me know if you need any other info.

ConBee II 
Version: 2.05.71
Firmware: 264A0700

**Comment by marthoc** [comment]
This is not a Docker image issue, please create an issue here: https://github.com/dresden-elektronik/deconz-rest-plugin
