### ISSUE TITLE
latest tag points to a beta version

### ISSUE THREAD

**Issue by duffbeer2000** [marthoc/docker-deconz#196]
Is there a reason why the latest tag of the image suddenly points to a beta version (2.05.72) of the rest api?

**Comment by marthoc** [comment]
This has always been the case. Latest has always pointed to the most recent release, whether stable or beta. Another issue has raised this and I may add a “stable” tag for stable releases. Latest will stay pointing to the most recent release - stable, Beta, or otherwise.
