### ISSUE TITLE
cpu time 8-12 times more 

### ISSUE THREAD

**Issue by MattL0** [marthoc/docker-deconz#198]
the deconz process is consuming 8-12 times more  cpu time  vs with the non docker version . is that normal ? 

the process is always at 4-7 % cpu load now

using an amd 2700x cpu here

**Comment by MattL0** [comment]
at this moment cpu time would be 1 min ( 8 times less ) in the non-docker version. 

The non-docker version was using minimal config tag.

**Comment by marthoc** [comment]
I’m not sure why this is. Presumably Docker adds some overhead.

**Comment by MattL0** [comment]
Just wanted to say that  docker with minimal install vs vnc etc., is night and day in term in cpu time usage. 
So that was it. 

Here will use the minimal install for everyday usage. And when i'll need the deconz  i'll switch to the default install with vnc . 

Thanks again for maintaining this docker image !
