### ISSUE TITLE
The daylight sensor seems to be configured with invalid values

### ISSUE THREAD

**Issue by bierlos** [marthoc/docker-deconz#200]
i use the docker container on a synology dsm.
i get always this error: The daylight sensor seems to be configured with invalid values
how can i set the long/lat/sunriseoffse/sunsetoffset on this container?

thanks
roland

**Comment by Krocko** [comment]
Hi. Are you using the Hue Essentials app?
I have this error if I change the geo location in this app. 
You can change the lat/long with an sql lite editor in the zll.db .

**Comment by bierlos** [comment]
thank you for your hint. i changed it with hue essentials. no more errors

**Comment by Mace404** [comment]
I have the same error message.
Tried Hue Essentials but gives no change.
Looked into the zll.db but I see no keys for lat/long. Are they in the config2 table?

**Comment by Krocko** [comment]
@Mace404 it is in the sensors table under the daylight sensor config.

**Comment by marthoc** [comment]
This is not an issue specific to the Docker image. Please open an issue on this repo: https://github.com/dresden-elektronik/deconz-rest-plugin.
