### ISSUE TITLE
deConz 2.05.73

### ISSUE THREAD

**Issue by Krocko** [marthoc/docker-deconz#201]
deCONZ 2.05.73 is available.

**Comment by tubalainen** [comment]
Oh? .. Cannot see it being released. Where did you find the .73 version?

https://github.com/dresden-elektronik/deconz-rest-plugin/releases
![image](https://user-images.githubusercontent.com/26795429/74605135-5c90e300-50c5-11ea-8d40-20c04e21ac59.png)

**Comment by phdelodder** [comment]
The tag indicates that it's a beta version https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_73

**Comment by stickpin** [comment]
@phdelodder 2.0.5.72 is beta also: https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_72 
;)

**Comment by phdelodder** [comment]
I'll see what I can do, can't promise anything today

**Comment by duffbeer2000** [comment]
Like I said in "https://github.com/marthoc/docker-deconz/issues/196" why the latest tag points to beta versions? That's not the right way! The latest tag always should point to the latest offical release. You could implement a beta tag on docker hub.

**Comment by Krocko** [comment]
It is the same for the deCONZ packages.
`deconz-latest.deb | 14-Feb-2020 21:52 | 4.9M`
`deconz-2.05.73-qt5.deb | 14-Feb-2020 21:52 | 4.9M`

**Comment by marthoc** [comment]
While there are “stable” releases of deconz they tend to lag behind Beta in terms of both bug fixes and device compatibility. For that reason, this image’s latest points to Beta. I could consider adding a “stable” tag that points to the latest stable version for those that want to remain on the older version, but latest will stay on Beta as it truly is the latest version of the software.
