### ISSUE TITLE
Manual update Conbee firmware by firmware file 

### ISSUE THREAD

**Issue by lubbertkramer** [marthoc/docker-deconz#204]
Because of some problems with ikea lightning there has been made an official release for testing, see this issue @ the github of Dresden https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1261#issuecomment-590530228

Is it possible to use that file to update the firmware of my conbee 1? Regarding this documentation at the Dresden Git it's not possible -> https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

Or can the beta / test tag be applied as requested here https://github.com/marthoc/docker-deconz/issues/201

**Comment by realwax** [comment]
sudo systemctl stop deconz 
sudo systemctl stop deconz-gui
wget http://deconz.dresden-elektronik.de/deconz-firmware/deCONZ_Rpi_0x26340500.bin.GCF
sudo GCFFlasher_internal -d 0 -f deCONZ_Rpi_0x26340500.bin.GCF

works for conbee 1, see your link for conbee2 or others... 

![image](https://user-images.githubusercontent.com/14924590/75199515-a16ee680-5763-11ea-9ec8-642a72866f29.png)

**Comment by bytat** [comment]
> sudo systemctl stop deconz
> sudo systemctl stop deconz-gui
> wget http://deconz.dresden-elektronik.de/deconz-firmware/deCONZ_Rpi_0x26340500.bin.GCF
> sudo GCFFlasher_internal -d 0 -f deCONZ_Rpi_0x26340500.bin.GCF
> 
> works for conbee 1, see your link for conbee2 or others...
> 
> ![image](https://user-images.githubusercontent.com/14924590/75199515-a16ee680-5763-11ea-9ec8-642a72866f29.png)

That's not for the docker version so it won't work.
(I'm trying to update to the latest Conbee firmware but it isn't bundled in the container so I'm interested in this too)

**Comment by realwax** [comment]
Maybe this helps a little further. Otherwise stop the service connect it another machine and upgrade it there f.e. https://github.com/dresden-elektronik/deconz-rest-plugin/issues/236

**Comment by tubalainen** [comment]
> > sudo systemctl stop deconz
> > sudo systemctl stop deconz-gui
> > wget http://deconz.dresden-elektronik.de/deconz-firmware/deCONZ_Rpi_0x26340500.bin.GCF
> > sudo GCFFlasher_internal -d 0 -f deCONZ_Rpi_0x26340500.bin.GCF
> > works for conbee 1, see your link for conbee2 or others...
> > ![image](https://user-images.githubusercontent.com/14924590/75199515-a16ee680-5763-11ea-9ec8-642a72866f29.png)
> 
> That's not for the docker version so it won't work.
> (I'm trying to update to the latest Conbee firmware but it isn't bundled in the image so I'm interested in this too)

The firmware update script in marthocs docker didnt work for me... :/
I run the docker under Debian.

This is what I did, try to do like this:
* download the firmware using wget from above
```
cd /opt/deconz
(sudo) docker exec -it deconz bash
cp /usr/bin/GCFFlasher_internal* /root/.local/share/dresden-elektronik/deCONZ/
exit
(sudo) apt-get install libqt5serialport5
(sudo) ./GCFFlasher_internal -d 0 -f deCONZ_Rpi_0x26340500.bin.GCF
```

**Comment by bytat** [comment]
> > > sudo systemctl stop deconz
> > > sudo systemctl stop deconz-gui
> > > wget http://deconz.dresden-elektronik.de/deconz-firmware/deCONZ_Rpi_0x26340500.bin.GCF
> > > sudo GCFFlasher_internal -d 0 -f deCONZ_Rpi_0x26340500.bin.GCF
> > > works for conbee 1, see your link for conbee2 or others...
> > > ![image](https://user-images.githubusercontent.com/14924590/75199515-a16ee680-5763-11ea-9ec8-642a72866f29.png)
> > 
> > 
> > That's not for the docker version so it won't work.
> > (I'm trying to update to the latest Conbee firmware but it isn't bundled in the image so I'm interested in this too)
> 
> The firmware update script in marthocs docker didnt work for me... :/
> Even if I copied the firmware file to the firmware folder inside the docker but it was not listed when running the firmware-update script.
> 
> So I lifted out the flasher from the docker container and ran it on the host machine, to do so I needed to install a lib then it all ran fine.
> 
> I run the docker instance under Debian. And have the Conbee version 1 stick.
> 
> This is what I did, try to do like this:
> 
> ```
> cd /opt/deconz
> wget http://deconz.dresden-elektronik.de/deconz-firmware/deCONZ_Rpi_0x26340500.bin.GCF
> (sudo) docker exec -it deconz bash
> cp /usr/bin/GCFFlasher_internal* /root/.local/share/dresden-elektronik/deCONZ/
> exit
> (sudo) apt-get install libqt5serialport5
> (sudo) docker stop deconz
> (sudo) ./GCFFlasher_internal -d 0 -f deCONZ_Rpi_0x26340500.bin.GCF
> (sudo) docker start deconz
> (sudo) docker logs deconz
> ```

Thank you, tunalainen! This worked. 😄
