### ISSUE TITLE
Can't update Deconz

### ISSUE THREAD

**Issue by kirbby** [marthoc/docker-deconz#207]
Current Version:
Version 2.05.44 / 10/28/2018
Firmware 262D0500

I try to update like described in the description, but it only shows me 2 Versions to Update to:

Firmware available for flashing:

deCONZ_Rpi_0x261f0500.bin.GCF
deCONZ_Rpi_0x262d0500.bin.GCF

Those are both old, and no matter which one I choose, after restarting Phoscon it is back to the 2.05.44 and 10/28/2018.
I also tried to remove and recreate the docker container, but with no success
I tried yesterday for over 2 hours to get this update running...

I appreciate your help.

**Comment by BOZG** [comment]
Available firmwares are entirely dependent on the version of Deconz that you're using so it's not surprising that only old firmwares are available. Are you sure you're pulling the latest version of Deconz?

**Comment by kirbby** [comment]
My god, thanks so much. That gave me the push in the right direction. I thought the firmware update is the thing I need to do.
Now I understand, you update Deconz in docker with "docker pull marthoc/deconz" and then you can upgrade to the new firmware.

Thanks a lot BOZG

I have another problem now though, i managed to update Deconz itself, now when i want to upgrade the firmware i get the error: 
"/usr/bin/GCFFlasher_internal.bin: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/libwiringPi.so)
Enter the full device path, or press Enter now to exit."

The newest version i can get with apt-get is 2.24. I have a Raspi 3B+ with hassbian if that matters.

**Comment by BOZG** [comment]
Hassbian is deprecated now so that might be the underlying problem?

There's a discussion about the same issue on normal Raspbian here: https://github.com/marthoc/docker-deconz/issues/153

At the bottom, there seems to be a definitive solution.

**Comment by kirbby** [comment]
I didn't know Hassbian is deprecated. So I probably need to change anyway I guess?
The solution from there doesn't work, I just updated my above comment once more.

**Comment by BOZG** [comment]
Yeah, if I remember correctly, the main developer didn't have time to continue with development and had already made the switch to Hass.io (which is now renamed to Home Assistant if you missed it!).

Have you tried the solution posted here: https://github.com/marthoc/docker-deconz/issues/153#issuecomment-538689683?

**Comment by kirbby** [comment]
Yes that's what I tried. But I guess I'll just reinstall everything anyway on a new Home Assistant instance so no need to try to get this running here anymore, thanks for your help anyway.

**Comment by mnpg** [comment]
Hi everyone,

i've also the same problem as you and, in my case, i fixed it.

My configuration : RPI3B+ with raspbian stretch.

I've replaced the installed version of wiringpi (v2.52) by an old version (v2.46), compatible with libc6 (v2.24) version installed with stretch -and for my RPI3+-

URL to download wiringpi v2.46 :  http://wiringpi.com/wiringpi-updated-for-the-pi-v3plus/

hope it can help you

Regards

**Comment by kirbby** [comment]
Thanks for the tip, I tried that but the Flashing script still asks for:
/usr/bin/GCFFlasher_internal.bin: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/libwiringPi.so)

**Comment by mnpg** [comment]
In the Dockerfile for armhf, the wiringpi version that is installed is the latest one.
```
# Add WiringPi, install WiringPi
ADD https://project-downloads.drogon.net/wiringpi-latest.deb /wiringpi.deb
RUN dpkg -i /wiringpi.deb && \
    rm -f /wiringpi.deb
```
download wiringpi.deb v2.42 in your docker image and replace the latest one 2.52 by the old one.

**Comment by kirbby** [comment]
Thanks for your help but this is all too complicated I will just reinstall with hass.io and set everything up fresh.
