### ISSUE TITLE
Question: dev-container image with the latest current commits

### ISSUE THREAD

**Issue by SAOPP** [marthoc/docker-deconz#211]
I just wanted to ask, if there were any plans to release nightly builds of the Deconz image?

So that all peoples could use it before the release if they want some a new features. Since, for example, the situation with Opple Aqara switches is very sad right now, I just get it two switches, but cannot be used until the next official release of the container. I really want to. But to collect all this on my own is so lazy. :)

Maybe you can build some nightly pre-release container?

It's just question guys, just interesting about this dirrection. Thanks anyway!

**Comment by volschin** [comment]
This is probably the wrong address to ask this. 
If you take a look at the Dockerfile it has to use the build submitted by dresden elektronik. So you should ask them if they would submit a nightly build that could be then used by this docker image.
