### ISSUE TITLE
WebUI doesnt detect devices that the Desktop app detects

### ISSUE THREAD

**Issue by mike391** [marthoc/docker-deconz#214]
I tried to pair 2 Xiaomi mija door sensors using the webapp.  I tried to add them using Sensors->Add Sensor-> Other.   The webui was never able to detect these sensors though.  However in the Desktop UI, both devices appeared, however I am unable to set their 'Name', 'Model' or change any settings for them. 
 Furthermore they do not show up in the WebUI under sensors.

![image](https://user-images.githubusercontent.com/7278201/78800214-30893400-7989-11ea-9578-b6e2c8ca05f7.png)

![image](https://user-images.githubusercontent.com/7278201/78800219-33842480-7989-11ea-8240-c73d75b120e6.png)

**Comment by marthoc** [comment]
This appears to be a problem with deConz, not with the docker image. Please open an image on the deCONZ repo.
