### ISSUE TITLE
Firmware update not working with docker?

### ISSUE THREAD

**Issue by davralin** [marthoc/docker-deconz#215]
I see no mention of this in README.md - so I assume this should have worked?

Going through the logs from docker-run, I see `GW firmware update not supported on x86 linux headless` - and such I can't get what firmware I should use to upgrade.

As I have never upgraded, and the Conbee-stick is at least six months old - I'm assuming there is an upgrade here somewhere.

Is this not supposed to be possible with Docker?

**Comment by marthoc** [comment]
Yes, but you have to update manually, not through the link on Phoscon. Instructions are in the README.

**Comment by davralin** [comment]
Again, the output is from the Docker-image - I have not used the Phoson app for firmware-upgrades.

And the instructions in the README, tells me to look for `GW update firmware found: [...]` - but using the container, I get `GW firmware update not supported on x86 linux headless`.

**Comment by marthoc** [comment]
I suppose the developers have changed the log messages and I will need to update the readme. You can search the deCONZ GitHub to determine what the recommended firmware is; otherwise the README instructions are accurate. Perhaps @manup can assist with the proper firmware version for Conbee

**Comment by davralin** [comment]
So this issue is valid then? Maybe re-open? :-)

It appears that  https://deconz.dresden-elektronik.de/deconz-firmware/?C=M;O=D - is some sort of authorative source, based on: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

For my sake, it seems I'm already on the latest firmware.

**Comment by BenAndDevelopment** [comment]
I'd like to install the latest beta software. I get the same message as the OP. The list from @davralin doesn't contain beta firmware. So where do I get the lasted beta from?
