### ISSUE TITLE
Raspbee 1 does not connect to hue bulbs and unable to update

### ISSUE THREAD

**Issue by white91wolf** [marthoc/docker-deconz#216]
hey i have the issue that i cant find hue bulbs and light strips) - my osram bulbs 
So i searched for a reason and found this in the docker log:

```
15:58:32:920 dev /dev/ttyAMA0
15:58:32:921 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_Rpi_0x26330500.bin.GCF
15:58:32:921 GW firmware version: 0x1a020500
15:58:32:921 GW firmware version shall be updated to: 0x26330500
```

then i tried to update but got another issue (/usr/bin/GCFFlasher_internal.bin: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/libwiringPi.so)). So i updated the lib manually like descripted in this issue: https://github.com/marthoc/docker-deconz/issues/153

Then i stated the flashing script again and first it looked like it is fine but i wasnt able to flash anyways (i tried all rpi files)

```
-------------------------------------------------------------------

             marthoc/deconz Firmware Flashing Script

                       Version: 0.5

-------------------------------------------------------------------


Listing attached devices...

GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyAMA0     | 0x0000 | 0x0000  |            | RaspBee

Enter the full device path, or press Enter now to exit.

Device Path : /dev/ttyAMA0

-------------------------------------------------------------------

Firmware available for flashing:

deCONZ_ConBeeII_0x26490700.bin.GCF
deCONZ_ConBeeII_0x264a0700.bin.GCF
deCONZ_Rpi_0x26330500.bin.GCF
deCONZ_Rpi_0x26350500.bin.GCF

Enter the firmware file name from above, including extension,
or press Enter now to exit.

File Name : deCONZ_Rpi_0x26330500.bin.GCF

-------------------------------------------------------------------

Device: /dev/ttyAMA0

Firmware File: deCONZ_Rpi_0x26330500.bin.GCF

Are the above device and firmware values correct?
Enter Y to proceed, any other entry to exit: Y

Flashing...

GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 1A020500
action: reset device RaspBee

Flashing Error! Please re-run this script...
```

dont really know if this is releated to my main issue that im not able to connect my hue bulbs.
Funny is that i was able to pair my hue movement sensor and like already written all my osram bulbs.
i resetted the hue bulbs with my hue dimming switch - the bulbs are flashing fine but i am not able to pair :(
i also updated the docker to latest and tried all steps again (flashing also did not worked).

edit: also my hue bridge is not able to find all my hue lights anymore - only if i use touchlink or search with the serial no of the bulbs / stripes... very strange

EDIT: i now tried to use the deconz rest api - specially the touchlink one. Here the interessting fact is, that the touchlink scan shows all bulbs in the result. But they dont get paired for some reason.

Hope someone can help

**Comment by marthoc** [comment]
@white91wolf That is a very old firmware version on your device. @manup Could the old version be causing issues updating to a new version?

**Comment by white91wolf** [comment]
> @white91wolf That is a very old firmware version on your device. @manup Could the old version be causing issues updating to a new version?

Thought so too, but i think i also posted my attempts of trying updating/upgrading the Firmware and they all failed.
