### ISSUE TITLE
Feature Request Unraid Docker Template

### ISSUE THREAD

**Issue by markmghali** [marthoc/docker-deconz#217]
this not an issue but a feature request
Can we get an Unraid docker template created for this? That would be super helpful!

**Comment by duffbeer2000** [comment]
Hi, maybe I could help. I'm running this container on my unraid system. Do you have an example of a good template so I can make one for you?

**Comment by markmghali** [comment]
If you add it to the community apps. I think would involve you making a template out of your config somehow? not entirely sure

**Comment by markmghali** [comment]
looks like spaceinvader just made one recently?

![image](https://user-images.githubusercontent.com/17356528/83177817-51e2e280-a0e5-11ea-9e4c-2ec2ef1e887d.png)

**Comment by Mimiix** [comment]
As there hasn't been any new replies and as there are newer versions, i'm closing this issue. If this needs to be re-opened, please ping me :)
