### ISSUE TITLE
Run container as non-root?

### ISSUE THREAD

**Issue by raidenii** [marthoc/docker-deconz#218]
Hi,

I wonder if it's possible to have the deconz process inside container running as root, while the container run as a non-root user.

Namely, I have a deconz user with uid 2000 and gid 2000, and created a folder to store deconz configs on host at /opt/deconz, owned by deconz. deconz is also added to dialout group on host. And I created a container with the following:

`docker create --name=deconz --user=2000:2000 --restart=always -e DECONZ_UPNP=0 -e DECONZ_DEVICE=/dev/ttyACM0 -p 192.168.100.100:4080:80 -p 192.168.100.100:4443:443 -v /etc/localtime:/etc/localtime:ro -v /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ --device=/dev/ttyACM0 marthoc/deconz`

After I started the container, the container itself is running as deconz (expected), but I noticed that there was no file written to /opt/deconz. I ran bash inside the container and found that, within the container the deconz process is also running with uid 2000, and naturally it cannot either write to /root or access the Conbee II stick.

So I wonder if there is a way to make deconz inside container thinks it's running as root with uid 0 while the container runs a non-root user?

Thanks.

**Comment by volschin** [comment]
Please read the docker documentation.

**Comment by marthoc** [comment]
Closing this as I'm not likely to change the root usage any time soon. See also #161.
