### ISSUE TITLE
Finding IKEA Trådfri motion detectors does not work sometimes

### ISSUE THREAD

**Issue by helto4real** [marthoc/docker-deconz#22]
I find scanning and finding new devices is not as reliable as when using deconz api directly on the rpi.

Using RPI 3b+
Latest version ; 2.05.25 on both 

starting container with
docker run -d \
    --name=deconz \
    --net=host \
    --restart=always \
    -v /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ \
    --device=/dev/ttyUSB0 \
    marthoc/deconz

For example it finds one of my IKEA Trådfri motiondetector but not the other one. And also dont find all my IKEA Trådfri lights. One the rpi version no problem at all. Finds all perfectly.

Any advice would be great. I would prefer to run this in docker.

**Comment by helto4real** [comment]
Great work by the way :)

**Comment by marthoc** [comment]
I'm really not sure why this is happening. I haven't heard anything like this form anyone else and I haven't experienced it myself. I'll leave this issue open in case anyone else has the problem!

**Comment by helto4real** [comment]
CLosing this. I cant reproduce anymore. Probably another problem
