### ISSUE TITLE
Feature Request: replace VNC with XPRA

### ISSUE THREAD

**Issue by b2un0** [marthoc/docker-deconz#221]
replace VNC with XPRA and html5 server, so we can access the deCONZ ui via Browser,

like this container,
https://github.com/ffeldhaus/docker-wireshark

**Comment by volschin** [comment]
Generally sounds like an interesting idea. Is it really stable enough?
In your wireshark example I see bullseye used, which is not released as stable yet, will be 2021.
Additional there seem to be no debian packages for, they have to be taken from 3rd-party repository.

**Comment by DIYtechie** [comment]
@b2un0 I agree that browser access would be best, but of course it needs to be stable. You should make this request in the official deCONZ repository. They should really be the ones implementing such feature.

**Comment by Mimiix** [comment]
As there hasn't been any new replies and as there are newer versions, i'm closing this issue. If this needs to be re-opened, please ping me :)
