### ISSUE TITLE
Can't update to latest firmware version

### ISSUE THREAD

**Issue by fyksen** [marthoc/docker-deconz#223]
Latest from dresden site is: deCONZ_ConBeeII_0x26580700.bin.GCF

Latest in update script is: deCONZ_ConBeeII_0x26490700.bin.GCF

FTP site: https://deconz.dresden-elektronik.de/deconz-firmware/?C=M;O=D

**Comment by Gizmo-Ger** [comment]
https://github.com/marthoc/docker-deconz/issues/204#issuecomment-590831341

You need to change the parameter of GCFFlasher_internal for ConbeeII accordingly.

Have a look here for the details
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

**Comment by marthoc** [comment]
@manup Can you advise on the `-t 60` parameter when flashing ConbeeII with GCFFlasher? If required, I will need to update my flashing script to take that parameter into account...

**Comment by Sennevds** [comment]
@marthoc dresden elektronic created a beta release that's stating the following:
Firmware updates via deCONZ now use GCFFlasher parameter -t 60 to improve update robustness [c3c5ce](https://github.com/dresden-elektronik/deconz-rest-plugin/commit/c3c5cefbf2d5e09cda72d754af4c1bba68b4f4dd)

**Comment by manup** [comment]
> @manup Can you advise on the `-t 60` parameter when flashing ConbeeII with GCFFlasher? If required, I will need to update my flashing script to take that parameter into account...

Sorry I missed the notification. The `-t 60` parameter lets GCFFlasher try for 60 seconds to upgrade the firmware which often results in a higher success rate if the update doesn't succeed in the first run.

So it's a good idea to add this in the script.

**Comment by jghaanstra** [comment]
I run into the same issue with the current latest Docker container. According to my logs:
```
11:53:53:121 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26580700.bin.GCF
11:53:53:121 GW firmware version: 0x26580700
11:53:53:121 GW firmware version is up to date: 0x26580700
```

While latest firmware  for my ConbeeII is `deCONZ_ConBeeII_0x26650700.bin.GCF`. 

What do I need to do to upgrade?

**Comment by marthoc** [comment]
A feature has been introduced to help address this issue in #265. In the flashing script you should be able to specify that file name and the script will download it for you and allow you to flash it.

**Comment by snhnic** [comment]
I don't have "GW update firmware found: " in the log. Is there a step by step update for deconz in docker synology?
