### ISSUE TITLE
Firmware update fails (ConBee 1, FW 26350500) with error of missing GLIBC_2.28 on Raspbian stretch

### ISSUE THREAD

**Issue by DOliana** [marthoc/docker-deconz#226]
I am running the container on a raspberry with raspbian stretch.

I tried to update the firmware as described and got the output / error shown below. Could it be that there is a dependency missing? (A short googling shows that stretch does not seem to have the required version of glibc)

output:
```bash
Device: /dev/ttyUSB0

Firmware File: deCONZ_Rpi_0x26350500.bin.GCF

Are the above device and firmware values correct?
Enter Y to proceed, any other entry to exit: Y

Flashing...

/usr/bin/GCFFlasher_internal.bin: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/libwiringPi.so)

Flashing Error! Please re-run this script...
```

**Comment by volschin** [comment]
Looks like duplicate to #153

**Comment by DOliana** [comment]
Yes indeed. But that issue is 9 intra old and it seems that the solution is as simple as upgrading libc in the image. Can you do it?

**Comment by marthoc** [comment]
Working on this issue in #228. Follow that issue for updates.
