### ISSUE TITLE
Upgrading image to use Debian Buster

### ISSUE THREAD

**Issue by phdelodder** [marthoc/docker-deconz#228]
Should we update the docker file to "apt install" the libc package as well to restore the firmware flashing capability?
[153](https://github.com/marthoc/docker-deconz/issues/153)

_Originally posted by @tubalainen in https://github.com/marthoc/docker-deconz/pull/227#issuecomment-633944701_

I assume yes, but as I'm not a code owner it is best to have the opinion of @marthoc

**Comment by phdelodder** [comment]
I assume we beter upgrade the base image from stretch to buster.

**Comment by marthoc** [comment]
Yes we should look into that. I upgraded them a while back and had to revert because the upgrade to buster broke the rest of Deconz. Perhaps it would be useful to conduct some tests!

**Comment by marthoc** [comment]
Tonight I will do some cleaning up of the GitHub issues and I will create a branch for testing the upgrade to buster. I will likely push a testing image with a “testing” tag or something similar so that we can have some users verify that all is ok before we make the move to buster again.

**Comment by marthoc** [comment]
I have built and pushed a "testing" tag that upgrades the base image to Debian Buster. It is only for amd64 at the moment. Can users please test this and report back 1) if deconz still works on the Buster image and 2) if this fixes the libc6 issue with the flashing script.

Thanks!

**Comment by marthoc** [comment]
@phdelodder Please be advised that I am going to create a `next` branch to this repo where I will be making several modifications to the image. If there is a new deCONZ version released before I am done, please do not update the image. I would like to incorporate the new version into the next branch and release it alongside the changes. Thanks!

**Comment by tubalainen** [comment]
testing-buster installed without any issues and deconz started fine including the vnc server.
I have not tested flashing of the conbee.

I will let it run for a day or so and report back any findings.

My setup:
Core I7 server
Debian OS (amd64)
Docker
ConBee 1 with latest fw
Home Assistant 0.110.3

**Comment by marthoc** [comment]
I've now pushed testing tags for each arch: `testing-amd64`, `testing-armhf`, and `testing-aarch64`. These images are based on Debian Buster. Can I have arm users test and report back whether the upgrade to Buster fixes the problem with the flashing script and also whether deCONZ continues to operate normally under Buster?

Thanks!

**Comment by jjlawren** [comment]
I was able to use the new image to upgrade the firmware successfully.

It may be unrelated, but I seemed to have connectivity issues with two Hue bulbs while running the `testing-armhf` image. They have never had connectivity issues before but both would go offline after a couple minutes on the testing image. Reverting back to the `latest` image seems to keep the connection stable.

**Comment by sylvaing** [comment]
Hi @marthoc ,
I tested testing-armhf on orange PI.
For firmware upgrade ok, no problem
For deconz run (from One day) ok

But I have a problem with VNC connection, I can't connet. My VNC Viewer say " The connection closed unexpectedly."
And on docker log deconz, i found this:

```
[marthoc/deconz] Starting deCONZ...
[marthoc/deconz] Current deCONZ version: 2.05.77
[marthoc/deconz] Web UI port: 8080
[marthoc/deconz] Websockets port: 8443
[marthoc/deconz] VNC port: 5900
Killing Xtigervnc process ID 23... which was already dead
Cleaning stale pidfile '/root/.vnc/localhost:0.pid'!

New 'localhost:0 (root)' desktop at :0 on machine localhost

Starting applications specified in /etc/X11/Xvnc-session
Log file is /root/.vnc/localhost:0.log

Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /root/.vnc/passwd localhost:0 to connect to the VNC server.

```

**Comment by robsonke** [comment]
For what it's worth, I tested this too with a RP4 and the testing-armhf tag. Flashed a ConbeeII and all oke so far.

**Comment by phdelodder** [comment]
When connecting using the VNC the image restarts, the logging output: 

```
Xvnc TigerVNC 1.9.0 - built Jan 23 2020 18:03:00
Copyright (C) 1999-2018 TigerVNC Team and many others (see README.rst)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12004000, The X.Org Foundation


Thu Jun  4 11:25:30 2020
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5900
 vncext:      created VNC server for screen 0

Thu Jun  4 11:26:29 2020
 Connections: accepted: [fd00::d42f:60ff:fe4d:63a0]::36644
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)
terminate called after throwing an instance of 'rdr::Exception'
terminate called recursively
(EE)
(EE) Backtrace:
(EE)
(EE)
Fatal server error:
(EE) Caught signal 6 (Aborted). Server aborting
(EE)
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"

Xvnc TigerVNC 1.9.0 - built Jan 23 2020 18:03:00
Copyright (C) 1999-2018 TigerVNC Team and many others (see README.rst)
See http://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12004000, The X.Org Foundation


Thu Jun  4 11:26:41 2020
 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on all interface(s), port 5900
 vncext:      created VNC server for screen 0
```

**Comment by mtressl** [comment]
> When connecting using the VNC the image restarts, the logging output:

Same problem here, image restarts. Using the Screen Sharing app in MacOS which worked fine before.

**Comment by phdelodder** [comment]
@marthoc you have any insights on the VNC issue?

**Comment by momomok** [comment]
Running testing-armhf tag.

- Cannot flash firmware update: 

> /usr/bin/GCFFlasher_internal.bin: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/libwiringPi.so)

- VNC not working (using RealVNC)

> The connection closed unexpectedly

- The gateway seems to be working fine though

**Comment by marthoc** [comment]
@momomok What command are you using to invoke the flashing script?

**Comment by momomok** [comment]
> 
> 
> @momomok What command are you using to invoke the flashing script?

`docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz`

[from dockerhub page](https://hub.docker.com/r/marthoc/deconz)

**Comment by marthoc** [comment]
@momomok You need to substitute marthoc/deconz:testing-armhf for the image in that command.

**Comment by momomok** [comment]
> 
> 
> @momomok You need to substitute marthoc/deconz:testing-armhf for the image in that command.

Oh foolish me, changing to marthoc/deconz:testing-armhf did the trick. Firmware upgrade completed.
VNC still doesn't work though

**Comment by slamp** [comment]
Flashing works also for me with testing-armhf
`GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device /dev/ttyACM0 (ConBee II)
deCONZ firmware version 264A0700
R21B18 Bootloader
Vers: 2.07
build: Jun 17 2019
unlock!  (7441 ms)
flashing 160930 bytes: |==============================|
verify: .
SUCCESS`

**Comment by phdelodder** [comment]
A promising workaround: 

https://github.com/TigerVNC/tigervnc/issues/800

**Comment by elrollo** [comment]
Hi, 
after updating the docker image to the latest version "docker logs deconz" doesn't show any output.
Is this ok or is there something wrong with setup?
I am running a Pi with Buster 10.4.

thanks in advance for any help

**Comment by VincentMasselis** [comment]
> I've now pushed testing tags for each arch: `testing-amd64`, `testing-armhf`, and `testing-aarch64`. These images are based on Debian Buster. Can I have arm users test and report back whether the upgrade to Buster fixes the problem with the flashing script and also whether deCONZ continues to operate normally under Buster?
> 
> Thanks!

The `testing-armhf` image worked like a charm on my Rp3, thanks !

**Comment by Florian-Schmidt** [comment]
Hi guys,

I really waiting for Osram switches support for a long time and updated deconz on my RaspberryPi 4 two days ago for the first time. I've got the "GLIBC_2.28" issue and found @marthoc's hint to try:

docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz:armhf-2.05.66

This worked for me and showed me two possible /dev/tty* including mit /dev/ttyACM0 for my Conbee II. I thought: OK, this will work in future with next releases. 

Today I tried to use 2.05.79 but saw the same issue with "GLIBC_2.28". Then i found to add "deb http://ftp.de.debian.org/debian sid main" to /etc/apt/sources.list and updating packages. After some unsuccessfull "apt-get" commands I was able to install packages via "sudo aptitude".

But still getting the same error. Any ideas how to fix/update my RaspberryPi

**Comment by sibuser** [comment]
The testing-armhf image worked like a charm on my Rp3, thanks !

**Comment by marthoc** [comment]
@Florian-Schmidt use the command you posted but substitute marthoc/deconz:testing-armhf for the image.

**Comment by Florian-Schmidt** [comment]
@marthoc Thanks for test testing image. This worked but I still see 2.05.73 perhaps I have chosen the wrong firmware image.

**Comment by corvy** [comment]
I used this command and it worked just fine :) 

`docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz:testing-armhf`

This is my output. 

```
~ $ docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz:testing-armhf
Unable to find image 'marthoc/deconz:testing-armhf' locally
testing-armhf: Pulling from marthoc/deconz
c439312a9c21: Already exists 
3435a007b2ef: Pull complete 
2417758ec34a: Pull complete 
97fd7e7bb0d0: Pull complete 
996a54f13b28: Pull complete 
3eed5c5dc092: Pull complete 
0791b3f9150a: Pull complete 
b5a4663bd77c: Pull complete 
179f233a0152: Pull complete 
b8030a331b56: Pull complete 
e793c1d734b4: Pull complete 
dc2f89829815: Pull complete 
45e86eb422a1: Pull complete 
110c89fd8d89: Pull complete 
fc8b6e601cbd: Pull complete 
62dbcb4ccd9e: Pull complete 
01fe7248ecef: Pull complete 
79a5f8b3baf3: Pull complete 
32867d1186a5: Pull complete 
a9bb8d32a69d: Pull complete 
944696f7721d: Pull complete 
12bca756c863: Pull complete 
Digest: sha256:666ba68664c0b5a91049ca9227dd682743ff59e7e5784772abe39fbf0dcf0b63
Status: Downloaded newer image for marthoc/deconz:testing-armhf
-------------------------------------------------------------------
 
             marthoc/deconz Firmware Flashing Script
 
                       Version: 0.5
 
-------------------------------------------------------------------
 
 
Listing attached devices...
 
GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyAMA0     | 0x0000 | 0x0000  |            | RaspBee 
 
Enter the full device path, or press Enter now to exit.
 
Device Path : /dev/ttyAMA0
 
-------------------------------------------------------------------
 
Firmware available for flashing:
 
deCONZ_ConBeeII_0x264a0700.bin.GCF
deCONZ_ConBeeII_0x26580700.bin.GCF
deCONZ_Rpi_0x26330500.bin.GCF
deCONZ_Rpi_0x26350500.bin.GCF
 
Enter the firmware file name from above, including extension,
or press Enter now to exit.
 
File Name : deCONZ_Rpi_0x26350500.bin.GCF
 
-------------------------------------------------------------------
 
Device: /dev/ttyAMA0
 
Firmware File: deCONZ_Rpi_0x26350500.bin.GCF
 
Are the above device and firmware values correct?
Enter Y to proceed, any other entry to exit: Y
 
Flashing...
 
GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26330500
RaspBee Bootloader premium
Vers. 1.02
build 201
3/08/01
 (4354 ms)
flashing 125732 bytes: |=============================|
verify: ....
SUCCESS
```

**Comment by DerOetzi** [comment]
RPI 3, Docker-CE and Conbee II works fine. Firmware Update as well as running system (web and vnc) all okay so far.

**Comment by Florian-Schmidt** [comment]
I still stuck on firmware 2.05.73. Running the testing-armhf again still provides firmware deCONZ_ConBeeII_0x26580700.bin.GCF.

Also tried to create another container from marthoc/deconz to use newest master.

@phdelodder Didn't you commit changes to master to bump deconz to 2.05.82!? Is there any way to use this new version?

**Comment by phdelodder** [comment]
@Florian-Schmidt have you had a look at #259

**Comment by Florian-Schmidt** [comment]
@phdelodder hadn't found that yesterday. I'll check it and give it a try, thanks!
