### ISSUE TITLE
Unable to update firmware with image marthoc/deconz:armhf-2.05.77

### ISSUE THREAD

**Issue by rafuz** [marthoc/docker-deconz#229]
I am getting the old 
```
/usr/bin/GCFFlasher_internal.bin: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/libwiringPi.so)
```
when trying to update to the latest firmware deCONZ_Rpi_0x26350500.bin.GCF
@marthoc could you fix this image too? I have raspberry pi3 b+ with raspbee module

**Comment by marthoc** [comment]
Tracking the fix in #228.
