### ISSUE TITLE
How-To compile own changes / pull request from deconz-rest-plugin

### ISSUE THREAD

**Issue by bortim** [marthoc/docker-deconz#231]
Hey guys, hello @marthoc ,

I am trying to compile a pull-request before it goes to the official build.
My environment is a Docker-Container on a Ubuntu 20.04 LTS Raspberry-Image.

Within the container mat dependencies are missing.

That’s why I downloaded and installed the deconz and deconz-dev version, which is running within my container.

Then I downloaded the source of the pull-request and compiled it as described in the readme.

After compiling libde_rest_plugin.so was created.
Over the docker-directory I made it available in the Container and copied it to the plugins-folder.

Then I try to restart the container.

The web-Frontend starts (callable within the browser) but a gateway is not shown.

Then I started the container with more logging.
The general.xml was loaded, then two plugins.
But not the Rest-Plugin.

If I switch back to the old rest-plugin within that step the loading is shown with one log-entry.

I tried to do a chmod with the original as a reference file, but it did not work.

All in all:
I have no further idea, what I can do now.

So maybe somebody can give me some hints or a manual.

Regards
bortim

**Comment by bortim** [comment]
Now some information from the bash of the  docker-host and the container:
Ubuntu Server 20.4 LTS host:
`
$ docker version
OS/Arch:          linux/arm64
$ uname -m
aarch64
$ uname -a
Linux ubuntu 5.4.0-1011-raspi #11-Ubuntu SMP Fri May 8 07:43:33 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
$ arch
aarch64
$ dpkg --print-architecture
arm64
$ getconf LONG_BIT
64
$ file /usr/bin/ld
/usr/bin/ld: symbolic link to aarch64-linux-gnu-ld
$ file libde_rest_plugin.so
ELF 64-bit LSB shared object, ARM aarch64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=71275c4456d4d0e9e2f0a359b8e569a37de015ee, not stripped
Within the docker container: sudo docker exec -it deconz /bin/bash
`
`
$ uname -m
aarch64
$ uname -a
Linux ubuntu 5.4.0-1011-raspi #11-Ubuntu SMP Fri May 8 07:43:33 UTC 2020 aarch64 GNU/Linux
$ arch
aarch64
$ dpkg --print-architecture
arm64
$ getconf LONG_BIT
64
$ file libde_rest_plugin.so
ELF 64-bit LSB shared object, ARM aarch64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=02a7d73e49ba2db940242d76e2f4067227e05737, not stripped
`
So all in all I think that it is the same.
BUT: I don't know whty the docker container returns for uname -a the same as my host.
I would expect that there is something with debian and not with ubuntu.

Thanks and regards

**Comment by bortim** [comment]
If i install deconz directly on the Raspberry Pi and use my own compiled plugin, everything works.

**Comment by bortim** [comment]
I had the same question within the repository of the deconz-rest-plugin:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2894

**Comment by smesguich** [comment]
Same issue here .... 
https://github.com/marthoc/docker-deconz/issues/114#issuecomment-643760547

If you check your Docker logs, you will see that the rest API lib is not identifyed ....

**Comment by smesguich** [comment]
Hello @bortim 
Did you make it works ?

**Comment by bortim** [comment]
> Hello @bortim
> Did you make it works ?

Hey @smesguich ,
no. I had no possibility to solve this issue.
I migrated to a direct installation, and updated the Plugin with my selfcompiled one.
Regards

**Comment by smesguich** [comment]
hum okay, thanks ...

**Comment by samsam-rolon** [comment]
Hello,
Is there any update there ?
That's would be great for testing dev lib ...
cc @marthoc

**Comment by samsam-rolon** [comment]
Hello @bortim 
Did you find a way to bind a custom lib ?

**Comment by Mimiix** [comment]
As there hasn't been any new replies and as there are newer versions, i'm closing this issue. If this needs to be re-opened, please ping me :)
