### ISSUE TITLE
Getting VNC to work

### ISSUE THREAD

**Issue by gasm67** [marthoc/docker-deconz#235]
Hi,  Thanks for the work you have done.  I tried this evening to use Docker for the first time and after many hours I did manage to get it working using your instructions and code;
docker run -d \
    --name=deconz \
    --net=host \
    --restart=always \
    -v /etc/localtime:/etc/localtime:ro \
    -v /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ \
    --device=/dev/ttyUSB0 \
    marthoc/deconz

I thought it would be simple to add in the VNC using the environments.  This is what I used.

docker run -d \
    --name=deconz_local \
    --net=host \
    --restart=always \
    -v /etc/localtime:/etc/localtime:ro \
    -v /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ \
    --env=DECONZ_VNC_MODE=1 \
    --env=DECONZ_VNC_PORT=5900 \
    --env=DECONZ_VNC_PASSWORD=password \
    --device=/dev/ttyUSB0 \
    marthoc/deconz

But when I do a 'docker ps -a' , it just seems to be starting all the time.
Could you possibly point out where I might be going wrong ?  I would like to VNC into a NUC which doesn't have a monitor attached (when running).

Many Thanks,
G

arbeadie@arbeadie-deconz:~$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS                            PORTS               NAMES
27bf680b45c9        marthoc/deconz      "/tini -- /start.sh"   8 minutes ago       Restarting (134) 26 seconds ago                       deconz_local
3cb2a8dac9de        marthoc/deconz      "/tini -- /start.sh"   11 minutes ago      Restarting (134) 2 seconds ago                        deconz_vnc
99001018e66b        marthoc/deconz      "/tini -- /start.sh"   16 minutes ago      Up 16 minutes                                         deconz

**Comment by marthoc** [comment]
What does `docker logs deconz_local` report?

**Comment by gasm67** [comment]
Hi Mark,

I manages to get it working, just had to change the port from 5900 to 5901.

G
