### ISSUE TITLE
deCONZ has all my devices, but Phoscon App (and Homebridge) do not

### ISSUE THREAD

**Issue by mtressl** [marthoc/docker-deconz#237]
To be honest, I am quite lost. After having a very stable system based on **2.05.77** for a while (even though without VNC) I did a Docker container `pull` for the latest version, and an `up -d` to restart. All was fine, Phoscon App gave me **2.05.78** as current version and all devices were still there, working perfectly fine with the Homebridge Hue plugin. I left that +/-24hrs until I decided to look into the RaspBee II firmware update again, since now the logs show there is an update available (I still have **26520700**, logs show **26580700**). So I did how described in the _readme.md_ - stop the container, and initiate the _FWflasher_. Since it (again) gave me the error of missing GLIBC version I stopped the process and brought my Docker container back with `up -d`, no problem.

**_Now it's the point I cannot wrap my head around._**
To check things, I access the Phoscon App. The Phoscon App lost my gateway name, and asks me for a new one and to set a password. _Ok, the shit hit the fan._ Phoscon App is empty, rooms and devices are gone. Bummer.
Desperate I try to access deCONZ via VNC (and did not expect it to work, since it did not work in **.77**). But hello, VNC works like a charm and I have a connection. AND all my devices are there in deCONZ. _WHAT???_
Ok, back to Phoscon App to check things, and now there is a _Group 420_ showing up, and the lights section has my two bulbs, one outlet and the range extender. Lights and outlet are in Group 420 (my former basement room), but all sensors, switches, and the roller blinds are missing (all passive battery devices).
My blinds still work, and I can move them up/down with the Ikea up/down switch (they were paired before). But all of the devices are not available in Homebridge, and not in HomeKit (ALL of them).

So a bit context, but I really do not see why this is happening:
- Pi 3B+ running Homebridge in docker, all latest versions
- the same Pi running deCONZ in docker
- Homebridge Config-Ui-X running on 192.168.1.xxx:8080
- Phoscon App running on 192.168.1.xxx:8282
- VNC (now again) running on 192.168.1.xxx:5900
- `docker ps` gives me two running containers (homebridge and deconz) as expected

Any ideas guys? Is it the missing firmware update that causes this? Why did Phoscon App lose everything, then partly reappearing, but nothing is exposed to anywhere?

Help is really appreciated. Let me know if further details (e.g. logs) might help.

**Comment by mtressl** [comment]
Cross-posted here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2974

**Comment by Mimiix** [comment]
As there hasn't been any new replies and as there are newer versions, i'm closing this issue. If this needs to be re-opened, please ping me :)
