### ISSUE TITLE
Question: How to install Beta-Releases of deconz?

### ISSUE THREAD

**Issue by hmrc87** [marthoc/docker-deconz#238]
Hi, the title says it all I think. Since a few days Deconz will publish Beta-Releases every 15th month. How would one install them? or lets say in general: I only accomplished updating my gateway-firmware with the guide in the readme in this repository.

**Comment by Gizmo-Ger** [comment]
AFAIK for every deconz release a new docker is published by the docker-deconz maintainer. So just wait till a new one is released or open a pull request instead.

**Comment by DerOetzi** [comment]
Maybe there could be a seperated image build with tag beta or snapshot or something like that.

**Comment by marthoc** [comment]
FYI this will be solved when #265 is merged. Stable releases will be available using the "stable" tag, while all releases including betas will be available using the "latest" tag.
