### ISSUE TITLE
Firmware Update not working in proxmox env

### ISSUE THREAD

**Issue by me2000** [marthoc/docker-deconz#240]
I am trying to update the firmware of my ConBee II to the latest suggested version per the instructions on hub.docker.com. This freezes the docker host when the script starts the actual update process hard. The only solution is to reset the docker host hard, this can be reproduced.

The docker host is a Debian Buster system and the container is also the latest. The docker host is running inside a Proxmox virtualization environment at the latest version (6.2-6).

I know that this is probably a non-standard setup but I am still wondering if there is a workaround to this problem apart from updating the firmware on another system. Also it might be worth to put this information into the readme for the container to warn others about this.

**Comment by Mimiix** [comment]
Nope there is not. Updating in a VM environment is a big nono.

Please refer to https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually which is official documentation :)
