### ISSUE TITLE
VNC password file support for use with docker secrets

### ISSUE THREAD

**Issue by mingan666** [marthoc/docker-deconz#242]
A small update in the start.sh would make it possible to use a docker secret for the VNC password:

```
  # Set VNC password
  if [ "$DECONZ_VNC_PASSWORD_FILE" != 0 ]; then
      cat "$DECONZ_VNC_PASSWORD_FILE" | tigervncpasswd -f > /root/.vnc/passwd
  else
    echo "$DECONZ_VNC_PASSWORD" | tigervncpasswd -f > /root/.vnc/passwd
  fi
  chmod 600 /root/.vnc/passwd
```

**Comment by mingan666** [comment]
It's been some months now without any feedback.
Is there any change of getting this small improvement?

**Comment by volschin** [comment]
Why you don‘t submit a PR for this?

**Comment by mingan666** [comment]
Haven't done much of this... Not sure what the process is.
I was waiting for some feedback if the change was ok for the maintainer before taking the effort.

https://github.com/marthoc/docker-deconz/pull/262

**Comment by fubar-coder** [comment]
Is there any progress for this feature?

**Comment by mingan666** [comment]
No, unfortunately my PR got canceled/closed.

**Comment by fubar-coder** [comment]
It would've been better to have at least something instead of nothing.

**Comment by Mimiix** [comment]
Is this still valid?

**Comment by phdelodder** [comment]
Will be adding this in my batch of improvements
