### ISSUE TITLE
Deconz uses the default ssl port 443 for websockets but doesn't provide an ssl certificate

### ISSUE THREAD

**Issue by Mrono** [marthoc/docker-deconz#243]

**Comment by Mrono** [comment]
Why not expose websockets on the normal webserver port instead of causing conflicts?

**Comment by Kane610** [comment]
It's docker. You can change the port yourself

**Comment by marthoc** [comment]
You can change the port to whatever you like and this is not an issue specifically with the Docker image. Closing.
