### ISSUE TITLE
ConBee 2 Firmware not connected

### ISSUE THREAD

**Issue by barthelemyguillaume** [marthoc/docker-deconz#245]
Hi,

I've a problem with my stick ConBee 2 on my Raspberry Pi3 B+.
Until yesterday it was working fine but the container has stopped working for some unknown reason. 

I created a new container with the following command
`docker run -d --name=deconz --net=host --restart=always -v /opt/deconz:/root.local/shar/dresden-elektronik/deCONZ --device=/dev/ttyACMZigBee:/dev/TTYACM0 -e TZ=Europe/Brussels -e DECONZ_VNC_MODE=1 -e DECONZ_VNC_PORT=5901
-e DECONZ_DEVICE=/dev/ttyACMZigBee marthoc/deconz` 
ttyACMZigBee is a SYMLINK for ttyACM1 (this is my Conbee 2)
![image](https://user-images.githubusercontent.com/45336692/88707632-d0262a00-d112-11ea-8fff-3f47eacc2a2a.png)
![image](https://user-images.githubusercontent.com/45336692/88707706-f055e900-d112-11ea-92b3-cfc1bdcb3c01.png)

In the Phoscon App, I've this informations
![image](https://user-images.githubusercontent.com/45336692/88707817-11b6d500-d113-11ea-9a43-8ef14898b56c.png)

In the logs of the container, I hav this informations
`20:48:33:568 dev /dev/ttyAMA0
20:48:33:569 COM: --dev: /dev/ttyACMZigBee (ConBee II)
20:48:33:591 device disconnected reason: 4, index: 0
20:48:34:478 wait reconnect 15 seconds
20:48:34:526 dev /dev/ttyAMA0
20:48:34:526 COM: --dev: /dev/ttyACMZigBee (ConBee II)
20:48:35:478 wait reconnect 14 seconds
20:48:36:479 wait reconnect 13 seconds
20:48:37:479 wait reconnect 12 seconds
20:48:38:479 reconnect network failed, try later
20:48:38:479 wait reconnect 11 seconds
20:48:38:479 start reconnect to network
20:48:38:523 dev /dev/ttyAMA0
20:48:39:479 wait reconnect 10 seconds
20:48:40:479 wait reconnect 9 seconds
20:48:41:479 wait reconnect 8 seconds
20:48:42:479 wait reconnect 7 seconds
20:48:43:479 failed to reconnect to network try=1
20:48:43:479 wait reconnect 6 seconds
20:48:44:479 wait reconnect 5 seconds
20:48:45:480 wait reconnect 4 seconds
20:48:46:479 wait reconnect 3 seconds
20:48:47:479 wait reconnect 2 seconds
20:48:48:479 failed to reconnect to network try=2
20:48:48:479 wait reconnect 1 seconds`

I use a USB cable for the ConBee 2

Thank you for your help

**Comment by arthurspa** [comment]
Check #271
Basically you can try using 'privileged: true' and 'UDEV=1'
