### ISSUE TITLE
Conbee II Hardware Compatibility

### ISSUE THREAD

**Issue by whitebengal** [marthoc/docker-deconz#251]
This is more a comment for extended debug tips that needs to be incorporated into the documentation.

I just ran across a major nightmare getting the gateway to work with my Synology NAS Docker. The root cause was a hardware compatibility problem on the DS918+. I added the appropriate insmod script, see below, to load the kernel modules and the /dev/ttyACM0 device showed up as expected, but all attempts to contact it through the docker image failed. It had high privileges as Docker is partially broken on Synology. Upon deeper inspection of the kernel logs, error codes were being thrown by the USB drivers and disconnecting the gateway, followed by immediately reconnecting it. The solution was to install an unpowered USB3 hub between the NAS and the gateway. Apparently, the kernel version and hardware used in the NAS are not 100% compatible with USB2 devices like the gateway.

/usr/local/etc/rc.d/startup.sh: (-rwx------ 1 root root)
#!/bin/sh
sudo insmod /lib/modules/usbserial.ko
sudo insmod /lib/modules/ftdi_sio.ko

**Comment by Mimiix** [comment]
@whitebengal For documentation, refer to the deconz-rest wiki. Best to put it [there ](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki):)!

**Comment by senilio** [comment]
Moved this to https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Synology-hack-for-Conbee-II
