### ISSUE TITLE
Switch Editor broken?

### ISSUE THREAD

**Issue by Surfer2010** [marthoc/docker-deconz#252]
## Describe the bug

I have a Switch (Osram Lightyfy 4 Button Switch) in the "switches" menu, but no available switch in the switch editor in my Room

## Expected behavior
In my "room" i go to SwitchEditor to add a switch that is known to the system

## Environment
Newest Docker Image (2.05.80 / 14.8.2020)

 - Host system: intel server
 - Running method: Marthoc Docker container on a debian server
 - Firmware version: (26xxyy00)
 - deCONZ version: (2.05.80)
 - Device: ConBee II
 - Do you use an USB extension cable: yes

**Comment by Surfer2010** [comment]
This is how it looks like:

![screenshots](https://user-images.githubusercontent.com/5108376/91285597-b584b680-e78d-11ea-8ffb-ca39ccfa0003.jpg)
[Uploading screenshots_pdf.pdf…]()

**Comment by marthoc** [comment]
This is an issue with deCONZ, not the Docker image specifically. Please post this as an issue on the deCONZ repo or seek assistance on the Discord server. Thanks!
