### ISSUE TITLE
Hi CPU on Synology DS718+ 

### ISSUE THREAD

**Issue by rjenx** [marthoc/docker-deconz#253]
Hi 
I am running deconz on a synology DS718+, the container is consuming around 25% CPU which seems a lot. My other containers are all averaging around 0.2 - 0.5% (home assistant, unifi controller, plex etc) 

Is this normal, I don't remember it being so high on previous versions. Currently running 2.05.75, if its abnormal any suggestions on root cause?

Thanks for all your work, by the way!

**Comment by mtressl** [comment]
I usually realise high CPU usage when I have LQI signal strength enabled via VNC. Maybe you are as well? Turning that off puts CPU usage back to normal.
