### ISSUE TITLE
deconz is constantly logging

### ISSUE THREAD

**Issue by DenisLug** [marthoc/docker-deconz#255]
Hello,

every few seconds I'm getting these messages on my console output:
```
16:30:59:109 apsUseExtPanid is 0xDDDDDDDDDDDDDDDD but should be 0, start reconfiguration             
16:30:59:109 Skip automatic channel change, TODO warn user                                           
16:31:07:404 don't close database yet, keep open for 900 seconds
```
What does these messages mean? What do I need to do to solve the problem?

I'm using deconz version 2.05.78 on a synology with the Conbee II.

Best Regards

**Comment by marthoc** [comment]
@DenisLug you can turn down the log level of the container by setting the environment variable `-e DEBUG_INFO=0`. 

As for why this issue is happening, you will need to raise an issue on the deCONZ repo. Thanks!
