### ISSUE TITLE
Stable Image is missing

### ISSUE THREAD

**Issue by duffbeer2000** [marthoc/docker-deconz#258]
At the moment we only have the newest beta release and not the newest stable release.
Problem is the line:
ADD http://deconz.dresden-elektronik.de/ubuntu/beta/deconz-${DECONZ_VERSION}-qt5.deb /deconz.deb

For the latest stable release of deconz it has to be:
DECONZ_VERSION=2.05.81
ADD http://deconz.dresden-elektronik.de/ubuntu/stable/deconz-${DECONZ_VERSION}-qt5.deb /deconz.deb

Maybe there should be a tag for latest stable and latest beta?

**Comment by Knapoc** [comment]
On a side note: imho stable and beta releases should be published under separate tags (e.g. beta=beta and latest=stable).

**Comment by marthoc** [comment]
@duffbeer2000 @Knapoc Please note that this will be addressed in an omnibus PR to be merged shortly, but the main changes are addressed in #266. 

Bottom line: "latest" tag will include beta releases (literally, the latest release of software), "stable" tag will include stable releases only. This also avoids a breaking change as the latest tag currently includes all releases.
