### ISSUE TITLE
Unable to update firmware

### ISSUE THREAD

**Issue by pippo73** [marthoc/docker-deconz#259]
Hello all, 
I have seen that there is a new firmware for the ConBeeII usb dongle.
If you take a look  the following site http://deconz.dresden-elektronik.de/deconz-firmware/ there is a new firmware is present called  **deCONZ_ConBeeII_0x26650700.bin.GCF**.
Since I'm new to zigbee and docker environment maybe I'm failing something.

Here what I did (almost the instructions found here https://github.com/marthoc/docker-deconz#updating-conbeeraspbee-firmware)

```
$ docker stop _[container name]_
$ docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz
```

I gave the path to my device (/dev/ttyACM0)
And in responce I got the following list

```
deCONZ_ConBeeII_0x264a0700.bin.GCF
deCONZ_ConBeeII_0x26580700.bin.GCF
deCONZ_Rpi_0x26330500.bin.GCF
deCONZ_Rpi_0x26350500.bin.GCF

```
I've tried to indicate the new fw present on the site (not in the list) as expected it doesn't work.

is there any way to update?

If it could help
```
$ uname -a
Linux sk4mc 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

thanks for the help?

**Comment by jghaanstra** [comment]
I'm experiencing the same. This is what the Docker logs tell me:

```
11:53:53:121 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26580700.bin.GCF
11:53:53:121 GW firmware version: 0x26580700
11:53:53:121 GW firmware version is up to date: 0x26580700
```

So it does not seem to discover the latest firmware version for my ConbeeII which is `0x26650700`.

**Comment by bytat** [comment]
Thanks jghaanstra! Had the same issue, your suggestion worked. Note to others, had to chmod 777 the firmware to get it to flash without errors.

**Comment by Whilk-and-Misky** [comment]
Hey,

I also had the same problem and the following helped me:

After starting Docker like this:

`docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add = ALL -v / dev: / dev -v / lib / modules: / lib / modules -v / sys : / sys marthoc / deconz`

I have ...

```
... STEP 1: / dev / ttyACM0
... STEP 2: deCONZ_ConBeeII_0x26580700.bin.GCF
```

entered.

In short, leave out the path in STEP 2 and it worked perfectly.

**Comment by pippo73** [comment]
Sorry @Whilk-and-Misky  I did not understood what you mean?

**Comment by matthias-burgfried** [comment]
> 
> 
> I'm experiencing the same. This is what the Docker logs tell me:
> 
> ```
> 11:53:53:121 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26580700.bin.GCF
> 11:53:53:121 GW firmware version: 0x26580700
> 11:53:53:121 GW firmware version is up to date: 0x26580700
> ```
> 
> So it does not seem to discover the latest firmware version for my ConbeeII which is `0x26650700`.
> 
> [EDIT]
> A workaround is creating a volume mapping to /usr/share/deCONZ/firmware where the mapped volume contains the latest firmware you want to flash. I just updated my ConbeeII.


My sequence of commands
```
cd /root/download
wget http://deconz.dresden-elektronik.de/deconz-firmware/deCONZ_ConBeeII_0x26650700.bin.GCF
chmod 777 deCONZ_ConBeeII_0x26650700.bin.GCF
docker stop deconz
docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys -v /root/download:/usr/share/deCONZ/firmware marthoc/deconz
docker start deconz
```

**Comment by phdelodder** [comment]
These are my steps: https://gist.github.com/phdelodder/60de443020417d4b813544afeb8c0168

I hope it can help

**Comment by mconnolly05** [comment]
> These are my steps: https://gist.github.com/phdelodder/60de443020417d4b813544afeb8c0168
> 
> I hope it can help

this worked perfectly, thank you!

**Comment by pippo73** [comment]
> These are my steps: https://gist.github.com/phdelodder/60de443020417d4b813544afeb8c0168
> 
> I hope it can help

Thank you. It worked for me too 😊
