### ISSUE TITLE
New Firmware not installing because of wrong md5 path inside firmware-update.sh

### ISSUE THREAD

**Issue by wcdgit** [marthoc/docker-deconz#272]
Hi,

new firmware could not be installed because of a wrong path to the md5 file. See row 72 in firmware-update.sh:
`md5=$(curl --fail --silent "${FW_BASE%/}/${fileName}.md542")`
There is no *.md542 in ${FW_BASE%}.

After changing to 
`md5=$(curl --fail --silent "${FW_BASE%/}/${fileName}.md5")`
the download and install of the newest firmware for my ConBeeII went perfectly fine.
http://deconz.dresden-elektronik.de/deconz-firmware/deCONZ_ConBeeII_0x26650700.bin.GCF

Please fix this typo.

**Comment by Jo-Be-Co** [comment]
Fixed this annoying thing with #273

**Comment by corvy** [comment]
Does this solve this error? 

`~ $ docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz:latest
-------------------------------------------------------------------
 
             marthoc/deconz Firmware Flashing Script
 
                       Version: 0.6
 
-------------------------------------------------------------------
 
 
Listing attached devices...
 
GCFFlasher V3_15 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyACM0     | 0x1CF1 | 0x0030  |            | ConBee II 
/dev/ttyACM1     | 0x1CF1 | 0x0030  |            | ConBee II 
 
Enter the full device path, or press Enter now to exit.
 
Device Path : /dev/ttyACM0  
 
-------------------------------------------------------------------
 
Firmware available for flashing:
deCONZ_ConBeeII_0x264a0700.bin.GCF
deCONZ_ConBeeII_0x26580700.bin.GCF
deCONZ_Rpi_0x26330500.bin.GCF
deCONZ_Rpi_0x26350500.bin.GCF
 
Enter the firmware file name from above, including extension.
Alternatively, you may enter the name of a firmware file to download
from http://deconz.dresden-elektronik.de/deconz-firmware/
or press Enter now to exit.
 
File Name : deCONZ_ConBeeII_0x26650700.bin.GCF
 
File not found locally. Try to download?
Enter Y to proceed, any other entry to exit: Y
 
Downloading...
 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  160k  100  160k    0     0   270k      0 --:--:-- --:--:-- --:--:--  270k
 
Download complete! Checking md5 checksum...
md5sum: 'standard input': no properly formatted MD5 checksum lines found
 
Error comparing checksums! Please re-run this script...
 
`

**Comment by Jo-Be-Co** [comment]
> Does this solve this error?
> 
> ## `~ $ docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz:latest
> ```
> -------------------------------------------------------------------
> 
>              marthoc/deconz Firmware Flashing Script
> 
>                        Version: 0.6
> 
> -------------------------------------------------------------------
>
> [...]
>
> Download complete! Checking md5 checksum...
> md5sum: 'standard input': no properly formatted MD5 checksum lines found
> 
> Error comparing checksums! Please re-run this script...
> ```

Yes, that's exactly the behaviour caused by the typo.

The script tries to download the `.md542` to compare it's content to the md5sum of the firmware file. As there isn't such a file the script exits with an error.

Even worse: the script does a cleanup after exiting. Otherwise you would have seen the downloaded file on the next run.

**Comment by S474N** [comment]
Same problem with new firmware deCONZ_ConBeeII_0x26660700.bin.GCF

```
-------------------------------------------------------------------

             marthoc/deconz Firmware Flashing Script

                       Version: 0.6

-------------------------------------------------------------------


Listing attached devices...

GCFFlasher V3_15 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyACM0     | 0x1CF1 | 0x0030  |            | ConBee II
/dev/ttyAMA0     | 0x0000 | 0x0000  |            | RaspBee

Enter the full device path, or press Enter now to exit.

Device Path : /dev/ttyACM0

-------------------------------------------------------------------

Firmware available for flashing:
deCONZ_ConBeeII_0x264a0700.bin.GCF
deCONZ_ConBeeII_0x26580700.bin.GCF
deCONZ_Rpi_0x26330500.bin.GCF
deCONZ_Rpi_0x26350500.bin.GCF

Enter the firmware file name from above, including extension.
Alternatively, you may enter the name of a firmware file to download
from http://deconz.dresden-elektronik.de/deconz-firmware/
or press Enter now to exit.

File Name : deCONZ_ConBeeII_0x26660700.bin.GCF

File not found locally. Try to download?
Enter Y to proceed, any other entry to exit: y

Downloading...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  160k  100  160k    0     0   438k      0 --:--:-- --:--:-- --:--:--  439k

Download complete! Checking md5 checksum...
md5sum: 'standard input': no properly formatted MD5 checksum lines found

Error comparing checksums! Please re-run this script...
```

Tested also manual downloading file directly to `/usr/share/deCONZ/firmware/`, but script dont recognize it.

**Comment by wcdgit** [comment]
> Tested also manual downloading file directly to `/usr/share/deCONZ/firmware/`, but script dont recognize it.

Just edit the firmware-update.sh like I showed in post #1.

**Comment by S474N** [comment]
> > Tested also manual downloading file directly to `/usr/share/deCONZ/firmware/`, but script dont recognize it.
> 
> Just edit the firmware-update.sh like I showed in the first post.

Cannot find them. Upgraded on Windows :)

**Comment by Loader23** [comment]
I tried to update the script but its also not recognizing...
I downloaded the script and copied it inside the container.

**Comment by wcdgit** [comment]
> 
> I tried to update the script but its also not recognizing...
> I downloaded the script and copied it inside the container.

maybe this could help you:
```
sudo docker run --name=deconz-fw -d -it --name=deconz-fw --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz
sudo docker exec -it deconz-fw bash
# inside the container, run:
apt update
apt install nano
nano firmware-update.sh
# remove the 42 in row 72. Result:
        md5=$(curl --fail --silent "${FW_BASE%/}/${fileName}.md5")
# save file and exit container
sudo docker stop deconz-fw
sudo docker start -i deconz-fw
# install your favorite fw file. ex. deCONZ_ConBeeII_0x26650700.bin.GCF
sudo docker rm deconz-fw
```
If not, just wait for the next version of  `marthoc/deconz`. It will be fixed.

**Comment by Loader23** [comment]
That worked, thanks alot! 👍 :-)

**Comment by Jo-Be-Co** [comment]
> ```
> # inside the container, run:
> apt update
> apt install nano
> nano firmware-update.sh
> # remove the 42 in row 72. Result:
>         md5=$(curl --fail --silent "${FW_BASE%/}/${fileName}.md5")
> # save file and exit container
> ```

To modify the `firmware-update.sh` you could just run this from outside the container.
```shell
sudo docker exec -it deconz-fw bash -c 'sed -i s/md542/md5/ firmware-update.sh'
```
... or use it with the appropriate container name. `sed` is available inside the deconz-container and therefore no installation is needed.

**Comment by Jo-Be-Co** [comment]
Putting all into one: if you want to download the firmware the way it should have been - call this:
```sh
sudo docker run -it --rm --entrypoint "sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz '-c' 'sed -i -e "s/md542/md5/" firmware-update.sh;./firmware-update.sh'
```

**Comment by wcdgit** [comment]
> 
> ```shell
> sudo docker exec -it deconz-fw bash -c 'sed -i s/md542/md5/ firmware-update.sh'
> ```
> 
> ... or use it with the appropriate container name. `sed` is available inside the deconz-container and therefore no installation is needed.

`sed`... very sleek. that didn't cross my mind.
