### ISSUE TITLE
Rpi2 and beta image

### ISSUE THREAD

**Issue by SAOPP** [marthoc/docker-deconz#277]
At the latest beta image, I can't recreated the container at my rpi2 host, the issue is:

`ailure OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/tini\": stat /tini: no such file or directory": unknown`

raspberry pi2 / raspbian / docker

There were no problems on the x86 platform. Any suggestion? Thanks.

**Comment by PaulErdbeck** [comment]
Version 2.05.83 can't connect to my conbee II
Devices are gone (may be because of missing connection to conbee), but not all.
If I run the 2.05.80 it works fine... I didn't get any error message...

raspberry pi 4 with raspbian and docker...

**Comment by SAOPP** [comment]
The latest stable release 84 is the same behaviour.

**Comment by SAOPP** [comment]
I'm just re-created a new container with a brand new version of latest image, and it seems to working good.

Obviously, the changes what Martin made after the container with version 82 is normal behavior, since the structure of the container has been slightly changed... But the question remains why there were no problems with x86. Well, I think the problem is closed.

At least on raspberry pi2, you need to re-create the deconz container. Peace.
