### ISSUE TITLE
Confusion about releases

### ISSUE THREAD

**Issue by malfroid** [marthoc/docker-deconz#280]
@marthoc it is very confusing to me to figure out what is the latest release and stable release of this docker image.

1. The [github README.md](https://github.com/marthoc/docker-deconz) shows 2.05.83 and 2.05.81

2. The [github releases page](https://github.com/marthoc/docker-deconz/releases) shows 2.05.54

3. The [dockerhub page](https://hub.docker.com/r/marthoc/deconz/tags) show that release 2.05.84 is already available

Could you provide some more clarity about this?

**Comment by phdelodder** [comment]
The latest release is 2.05.84 and it's also the stable.

**Comment by Mimiix** [comment]
We need to do this a bit better on our end.

@malfroid I have edited the readme on deCONZ repo.

**Comment by marthoc** [comment]
The README was missed on the last update. I think I may remove it from there so it does not happen again.
