### ISSUE TITLE
Deconz Docker Raspberry pi not connected

### ISSUE THREAD

**Issue by appleimperio** [marthoc/docker-deconz#281]
![Screen Shot 2020-10-14 at 1 21 25 PM](https://user-images.githubusercontent.com/72883739/96023326-3f610f80-0e20-11eb-960b-293687b9a839.png)
I try everything the only thing that works is outside a Docker. This is how i am creating the container: 

docker run -d --name=deconz --net=host --restart=always -v /etc/localtime:/etc/localtime:ro -v ~/.local/share/dresden-elektronik/deCONZ:/root/.local/share/dresden-elektronik/deCONZ --device=/dev/ttyACM0 -e DECONZ_DEVICE=/dev/ttyACM0 -e DECONZ_WEB_PORT=8181 marthoc/deconz:stable

already install latest firmware:

GCFFlasher V3_15 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device /dev/ttyACM0 (ConBee II)
deCONZ firmware version 26660700
R21B18 Bootloader
Vers: 2.07
build: Jun 17 2019
flashing 164106 bytes: |==============================|
verify: .
SUCCESS
Wait 10 seconds until application starts

Any idea?

**Comment by marthoc** [comment]
Please see #271 . Will be fixed shortly.
