### ISSUE TITLE
Another USB device that takes ttyUSB0 makes deconz fail to load device

### ISSUE THREAD

**Issue by helto4real** [marthoc/docker-deconz#29]
If I have another serial device like a rfxtrx device that takes ttyUSB0 deconz can't find the conbee stick.

Please see workaround here to find out to fix this. You should be able to script this some how especially in the hass.io plugin

https://github.com/helto4real/hassio/blob/master/setupdeconz.md

**Comment by Kane610** [comment]
Great work @helto4real

**Comment by Arsur** [comment]
this is still a point. I cant open the link, but i found a solution by my self. I used docker-compose file, so i just mapped
```
    devices:
      - /dev/ttyUSB1:/dev/ttyUSB0
```

**Comment by Kane610** [comment]
That works. But the number might change in reboot

**Comment by marthoc** [comment]
deCONZ has added a new command line parameter to allow selecting the device - I will be adding this to the container shortly and that should solve this issue. Stay tuned.

**Comment by helto4real** [comment]
Yes with USB discovery pointed out in my original post plus this fix will. Thanks!

**Comment by marthoc** [comment]
This should be fixed in the next version of this image which will get pushed shortly. See: https://github.com/marthoc/docker-deconz/issues/37#issuecomment-424773484

**Comment by wuast94** [comment]
> this is still a point. I cant open the link, but i found a solution by my self. I used docker-compose file, so i just mapped
> 
> ```
>     devices:
>       - /dev/ttyUSB1:/dev/ttyUSB0
> ```

this don´t work for my. i have tried many mappings but none worked. but in log i see two things i don´t understand. 

1. GW firmware update not supported on x86 linux headless

i have a 64bit system im running docker on: 
```
uname -m
x86_64
```

2. log shows like this endless: 
```
16:39:19:747 COM: --dev: /dev/ttyUSB1
16:39:19:757 COM: --dev: /dev/ttyUSB1
16:39:20:748 COM: --dev: /dev/ttyUSB1
16:39:20:757 COM: --dev: /dev/ttyUSB1
16:39:21:747 COM: --dev: /dev/ttyUSB1
16:39:21:757 COM: --dev: /dev/ttyUSB1
16:39:22:747 COM: --dev: /dev/ttyUSB1
16:39:22:757 COM: --dev: /dev/ttyUSB1
```
