### ISSUE TITLE
Docker Container not starting since today on RaspberryPI 3B+

### ISSUE THREAD

**Issue by clutwo** [marthoc/docker-deconz#291]
After automatic container update today, the container won't start anymore.

Error Message:

`ERROR: for deconz  Cannot restart container f132c8de64425e7638398fe8cd85f8fe861329f5e0c8530914a0c93bd0a64971: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/usr/bin/entry.sh\": stat /usr/bin/entry.sh: no such file or directory": unknown`

**Comment by marthoc** [comment]
I assume you are pulling latest? For some reason that has pulled the wrong image for your arch. What OS are you using?

**Comment by clutwo** [comment]
Sorry, yes, I'm pulling latest. OS is Raspbian. I have deleted the image and container. It now pulled the correct image. Don't know what happened, this is a first for me. Anyway, sorry for the bother and thanks for maintaining this image. Closing this.

**Comment by marthoc** [comment]
@clutwo thanks for reporting! Must have pulled the wrong arch for whatever reason. Have a good day!
