### ISSUE TITLE
`stable` and `latest` images from `2020-10-16` fail to load `libQt5Core.so.5`

### ISSUE THREAD

**Issue by Ocramius** [marthoc/docker-deconz#292]
Porting this from https://github.com/marthoc/docker-deconz/commit/f3682c92ed17234150d04f39287ba21f14d236ba#commitcomment-43303100

Related is possibly also the previous update @ https://github.com/marthoc/docker-deconz/commit/a07e972ac38fc1fcbd26a5c37456c7a3afaa9c5d

To be clear, noticed because I run watchtower, and it just did an upgrade:

 * from `sha256:8ce3a3a4ba80cc52803ce230097e47ef0f2006d366dc6ebe4564d440a6dd38eb`
 * to: `sha256:5e6ef3642a3f6e75d373c01ea5ff199aec6a9b211f67f6c164833fde23e3b2de`

This leads to:

```
2020-10-16T13:15:56.295136139Z [marthoc/deconz] Starting deCONZ...
2020-10-16T13:15:56.296017065Z [marthoc/deconz] Current deCONZ version: 2.05.85
2020-10-16T13:15:56.296150303Z [marthoc/deconz] Web UI port: 80
2020-10-16T13:15:56.296229461Z [marthoc/deconz] Websockets port: 443
2020-10-16T13:15:56.296307720Z [marthoc/deconz] VNC Disabled
2020-10-16T13:15:56.296251751Z /usr/bin/deCONZ: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

Potentially related to the change of base image:

```diff
-FROM balenalib/amd64-debian:stretch-run
+FROM debian:10.6-slim
```

Also, `libc6` no longer installed :thinking:

**Comment by andysaab** [comment]
Almost same issue to me:
[marthoc/deconz] Starting deCONZ...
[marthoc/deconz] Current deCONZ version: 2.05.85
[marthoc/deconz] Web UI port: 8080
[marthoc/deconz] Websockets port: 443
[marthoc/deconz] VNC Disabled
/usr/bin/deCONZ: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
Latest working image io.balena.architecture AMD64
Before this update have no problems since deconz v.2.05.76.

**Comment by Ocramius** [comment]
Rolled back to `marthoc/deconz:amd64-2.05.81` for now, so no panic please: stuff just happens :D

**Comment by andysaab** [comment]
No panic. 
Version 2.05.84 work fine.

**Comment by marthoc** [comment]
@Ocramius @andysaab This is a strange problem. I don’t experience it on my amd64 test system, which is running Debian. Out of interest, what OS are you running on?

**Comment by andysaab** [comment]
> @Ocramius @andysaab This is a strange problem. I don’t experience it on my amd64 test system, which is running Debian. Out of interest, what OS are you running on?
Hello!
I need to say a worse words - "docker on Xpenology".

**Comment by Ocramius** [comment]
@marthoc I am running this on a Synology RS1219+ (Intel(R) Atom(TM) CPU C2538, Docker version 18.09.8, build bfed4f5).

**Comment by andysaab** [comment]
I` running Synology DS3615xs, Zeon 1265L.
Docker v.18.09.0, build 0513

**Comment by marthoc** [comment]
@Ocramius @andysaab interesting that this is happening for both of you on Synology, which suggests to me that it may be an issue with the Synology kernel. I believe there is a workaround, however, as this seems to be a known issue with certain Docker implementations. 

If either or both of you can test the workaround for me, that would be very helpful. I'm not sure how Synology works in this regard but you will need to open a shell in the Docker container. Please pull latest, then create a container based on latest, and then from a shell do:
```
docker exec -it [containername] /bin/bash
apt update
apt install binutils
strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
exit
```
Then restart the container and see if it now loads properly. If so, I will create a PR that implements the fix.

**Comment by andysaab** [comment]
Hmm...
How is it possible if container not starting?
Or I not clear you.

**Comment by arctichikee** [comment]
Just wanted to chime in and say that it's happening on Red Hat 7.9 (Kernel: 3.10.0-1160.2.1.el7.x86_64). It has been working perfectly fine for months, but with the latest Docker image, I get the error about the missing libQt5Core.so.5 file.

**Comment by SAOPP** [comment]
@marthoc but how guys can access to not running container? 'coz container is shutting down immediately after it get fails. Okay it's just my minds 'bout it, I will try to help @andysaab right now, and we will share with u this result...

**Comment by marthoc** [comment]
All: I think the easiest way to test my fix will be for me to push a test image that contains the fix. I will advise when the image is ready, should be ten minutes or so.

**Comment by SAOPP** [comment]
Okay we will wait, stable release?

**Comment by marthoc** [comment]
Once the Travis build passes on PR #293, the test image will be available as marthoc/deconz:amd64-test.

**Comment by labaland** [comment]
Same problem here, Docker synology ds916+

**Comment by marthoc** [comment]
Interesting to me that all reports of this have been on amd64, and all but one on Synology.

**Comment by Ocramius** [comment]
It could be the old docker daemon, but we're indeed stuck with LTS for another while :(

**Comment by arctichikee** [comment]
I can confirm the bugfix works on Red Hat 7.9.

**Comment by marthoc** [comment]
Test build is now available as marthoc/deconz:amd64-test ; appears to work at least for @arctichikee, thanks!

**Comment by andysaab** [comment]
Now is work!
Many thanks!!!!

**Comment by Ocramius** [comment]
`amd64-test` (`sha256:b7401896e9103a3be7d2a45d8cbdd9d21cdd8ab0012f1defa4d462a07480bf32`) seems to start up correctly: stellar work, @marthoc!

Leaving this open until it's released though :D

**Comment by marthoc** [comment]
Thanks all for confirming. This issue will get closed when I merge the fix to master; I'm not going to do that until this evening as I want to build images for stable and latest at the same time.

Linking to the fix for future reference: https://github.com/YosysHQ/nextpnr/issues/375.

**Comment by andysaab** [comment]
After some time I see some troubles with this image. For example:
1. Change WS-port to 8081, deploy, after restart it seems 443 again.
2. Change VNC port, after deploy it seems changed but VNC not connects, reject connection.

**Comment by yauh** [comment]
Thanks for fixing it. `latest` appears to be fine, could it be that `stable` somehow slipped through the cracks?

**Comment by marthoc** [comment]
Stable will be up this evening

**Comment by marthoc** [comment]
@yauh Stable is now properly tagged on Docker Hub... both latest and stable images are now patched.

**Comment by Ocramius** [comment]
Thank you, @marthoc!
