### ISSUE TITLE
Firmware Update on Synology NAS DS716+ with Docker because "x86 linus headless"

### ISSUE THREAD

**Issue by helipus** [marthoc/docker-deconz#296]
Hi there,
I tried to do a firmware update of my Conbee II Stick which runs at the USB port of my Synology NAS DS716+ with the docker image marthoc/docker-deconz.
![image](https://user-images.githubusercontent.com/19687604/96363112-7857f780-1132-11eb-9735-7846566be6a3.png)
![image](https://user-images.githubusercontent.com/19687604/96363330-df29e080-1133-11eb-9875-cd90355d66ef.png)
The running firmware is 264A0700 Version 2.05.75 (8.3.2020).

I did SSH into the Synology and followed these instructions:
https://github.com/marthoc/docker-deconz#updating-conbeeraspbee-firmware

But the log doesn't show the firmware as expected:
`
$ sudo docker logs marthoc-deconz1 | grep "firmware"
19:28:13:587 GW firmware update not supported on x86 linux headless
19:28:24:561 Device firmware version 0x264A0700
`
This case is not handled in the update manual.

Some more information:
`
$ uname -a
Linux ds716 3.10.105 #25426 SMP Wed Jul 8 03:12:51 CST 2020 x86_64 GNU/Linux synology_braswell_716+
`
How can I update my firmware now without losing my configuration?

**Comment by Jo-Be-Co** [comment]
@helipus If you are running the latest image you could just continue with the listed steps. Stop your container and call the script:
```shell
docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz
```
If you are asked for the name of the firmware file you could place names of files that are not bundled with the container. The script will download absent files. But the newest image should provide you with `deCONZ_ConBeeII_0x26660700.bin.GCF` ...

Up to now I never lost my configuration by updating the firmware. If the update does not work in the docker context you could just plug the ConBee-Stick to your desktop and just update the firmware on this separate system. Back to your synology all should run well!

**Comment by helipus** [comment]
Thanks for the idea to use my windows machine. I did a successful update with the help of this tutorial:
https://flemmingss.com/how-to-update-conbee-conbee-ii-firmware-in-windows-10/
But as only the stable releases are offered here: 
http://deconz.dresden-elektronik.de/deconz-firmware/
It seems like I'm on the latest version right now. I don't understand though why it is uploaded 07-Oct-2020 but shows this in the GUI:
![image](https://user-images.githubusercontent.com/19687604/96474187-d53ad700-1232-11eb-89bc-174f657ed76e.png)

Where Do I found a *.bin.GCF file for the pre-releases like V2_05_86?

**Comment by Mimiix** [comment]
@helipus The version is the version of deCONZ, the software. The firmware is the stick itself.

**Comment by helipus** [comment]
Ah okay. So I don't need to update the firmware. I need to update my deCONZ software. The reason I need this is because for my Aqara OPPLE switches support I need  at least version 2.05.77. 

How can I updated my deCONZ software then under the conditions written in the first post?

**Comment by helipus** [comment]
Okay hier stet es beschrieben wie es geht:
https://marc.tv/synology-docker-container-aktualisieren-watchtower/
Auf Deutsch muss man statt "Clear" "Inhalt löschen" als Aktion wählen. 
Danke Euch!

**Comment by Jo-Be-Co** [comment]
@helipus did you mount a virtual folder so that all your data is stored outside the docker-container.

Hast Du einen Ordner Deiner Synology als virtuellen Ordner im Docker Container angelegt?
Nur so bleiben die Daten auf Dauer erhalten, wenn Du den Container aktualisierst!

**Comment by helipus** [comment]
I was missing that! Now it is fully working. Thanks a lot. 
For everyone else: The full link in "Mount-Pfad" is: "/root/.local/share/dresden-elektronik/deCONZ
Thanks @Jo-Be-Co and @Mimiix for the help!!!
