### ISSUE TITLE
Handling dynamic USB reconnect/attach

### ISSUE THREAD

**Issue by manup** [marthoc/docker-deconz#298]
Currently the container use the `--device` option to specify the path like /dev/ttyACM0. If that device is disconnected and attached again, physically, by hardware failure or firmware reboot (watchdog), the connection no longer works. In some cases /dev/ttyACM0 changes to /dev/ttyACM1 on re-enumeration.

The `--device-cgroup-rule` option might be a solution to let these changes propagate in the container.

https://docs.docker.com/engine/reference/commandline/create/#dealing-with-dynamically-created-devices---device-cgroup-rule

https://github.com/pbelskiy/docker-usb-sync

I haven't fully understand yet how it works, but it might be worth to test this. The major number can be found via `ls -l /dev/ttyACM0`.

**Comment by mercenaryballs** [comment]
I had been using /dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DM005CVV-if00-port0 to get around this issue on my server because I have a z-wave and conbee plugged in and sometimes it decides to change the tty number. Although this seems to not be working after I just updated. I had to change back to passing /dev/ttyUSB2

**Comment by manup** [comment]
The v2.5.87 release does support paths like /dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DM005CVV-if00-port0, but they need to be available in the container. The release will also automatically find this static path if only /dev/ttyACM0 is specified.

The problem is that when a device is re-enumerated under a different name this new device name isn't visible in  the container.
The cgroups flag can help with that but it likely also requires a small udev script or more /sys/ stuff to exposed to the container.

**Comment by manup** [comment]
After some tests it seems **cgroups** are indeed the right approach.
Here is my `docker-compose.yml` file.

```
version: "2.3"
services: 
  deconz:
    image: marthoc/deconz
    container_name: deconz
    network_mode: host
#    restart: always
    volumes:
      - /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ
      - /run/udev:/run/udev:ro  # so that serial number vendor/product ids are known
    device_cgroup_rules:
      - 'c 166:* rmw' # allow creation of /dev/ttyACMx nodes via mknod
    devices:
      - /dev/bus/usb

    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=2
      - DEBUG_ERROR=2
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
```
*  `cgroup 166` allows creation of the /dev/ttyACMx names inside the container;
* The device is set to `/dev/bus/usb` to be able to detect dynamic USB attach / reboots;
* The `/run/udev:/run/udev:ro` exposes vendorId, productId and serial number of ConBee II to the container, which helps with reconnecting and also doing firmware updates.

#### Test

I've unplugged and reattached ConBee II quickly so that the /dev/ttyACM0 becomes invalid and new /dev/ttyACM1 is created on the host (but not visible in the container yet).
In the container I could manually create /dev/ttyACM1 and deCONZ automatically connected to it.

This wasn't possible before.

#### Next steps

The upcoming deCONZ beta version will automatically create these /dev/ttyACMx devices via `mknod` if they aren't already present.

Since this is only possible with above `cgroups` configured, deCONZ will check if the container is allowed to create these devices by checking the file `/sys/fs/cgroup/devices/devices.list` if a line with `c 166:* rwm` exists.

With these changes reconnection issues should be mitigated as this works like a native system.

**Comment by bigbread59** [comment]
I am using version 3.6
with the following file, I get this error message.

### 
version: '3.6'
services:
  deconz:
    image: marthoc/deconz
    container_name: deconz
    network_mode: host
    restart: unless-stopped
    ports:
      - '8090:80'
      - '443:443'
      - '5901:5900'
    volumes:
      - ./volumes/deconz/:/root/.local/share/dresden-elektronik/deCONZ
      - /run/udev:/run/udev:ro  # so that serial number vendor/product ids are known
    device_cgroup_rules:
      - 'c 166:* rmw' # allow creation of /dev/ttyACMx nodes via mknod
      - 'c 188:* rmw' # allow creation of /dev/ttyUSBx nodes via mknod
    devices:
      - /dev/bus/usb
    environment:
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PASSWORD=changeme
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      
      
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.deconz: 'device_cgroup_rules'

See attaced file


[docker-compose.txt](https://github.com/marthoc/docker-deconz/files/5649067/docker-compose.txt)

**Comment by freemann** [comment]
I run docker compose version 3.6 and with this version 'device_cgroup_rules' is not supported.
So I need to run with a alternative docker-compose version.
Portainer isn't supporting 2 compose files, so controlling the container is a bit cumbersome.
Do you have any solution for running this in a 3.6 environment?

For now it all looks stable with below compose, where my current compose on 3.6 is failing badly within 1 hour since my update to 2.07.

gettings tons of these error and my zigbee network is down:
```dev can't create file: /dev/ttyUSB0 via mknod (missing permissions)```
and
```wait reconnect X seconds```

> version: "2.3"
> services: 
>   deconz:
>     image: marthoc/deconz
>     container_name: deconz
>     network_mode: host
>     restart: always
>     volumes:
>       - /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ
>       - /run/udev:/run/udev:ro  # so that serial number vendor/product ids are known
>     device_cgroup_rules:
>       - 'c 166:* rmw' # allow creation of /dev/ttyACMx nodes via mknod
>       - 'c 188:* rmw' # allow creation of /dev/ttyUSBx nodes via mknod
>     devices:
>       - /dev/bus/usb
> 
>     environment:
>       - DECONZ_WEB_PORT=80
>       - DECONZ_WS_PORT=443
>       - DEBUG_INFO=2
>       - DEBUG_ERROR=2
>       - DEBUG_APS=0
>       - DEBUG_ZCL=0
>       - DEBUG_ZDP=0
>       - DEBUG_OTAU=0

**Comment by manup** [comment]
>Do you have any solution for running this in a 3.6 environment?

It appears that docker compose has removed `device_cgroup_rules` support in 3.x for some reason and re-added it later in version 3.7. Therefore I'm afraid with 3.0 – 3.6 this approach doesn't work.

I'm not sure if as workaround for 3.6 `privileged` forwards the cgroups of the host. Inside Docker deCONZ strictly checks for `166:*` / `188:*` to be present and does print the `dev can't create file: /dev/ttyUSB0 via mknod (missing permissions)` if not.

**Comment by ualex73** [comment]
@bigbread59 any reason why you cannot upgrade to a later version of Docker? The CE version has already 3.9 available, that would be the easiest way forward.

**Comment by bigbread59** [comment]
> @bigbread59 any reason why you cannot upgrade to a later version of Docker? The CE version has already 3.9 available, that would be the easiest way forward.

Thank you but  I'm not so skill!
I am using the environment:
https://sensorsiot.github.io/IOTstack/
with satisfaction but at the moment it does not implement the suggested fixes for DECONZ Conbee2.

**Comment by ualex73** [comment]
Ask them to upgrade Docker to the latest version, then it will directly work for you without hacks.

**Comment by damajor** [comment]
I wonder if a quick and dirty change in menu.sh replacing the docker compose version may work.

**Comment by bigbread59** [comment]
Thanks everyone for the tips, I'll try to use them well!

**Comment by rkkhanna** [comment]
> After some tests it seems **cgroups** are indeed the right approach.
> Here is my `docker-compose.yml` file.
> 
> ```
> version: "2.3"
> services: 
>   deconz:
>     image: marthoc/deconz
>     container_name: deconz
>     network_mode: host
>     restart: always
>     volumes:
>       - /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ
>       - /run/udev:/run/udev:ro  # so that serial number vendor/product ids are known
>     device_cgroup_rules:
>       - 'c 166:* rmw' # allow creation of /dev/ttyACMx nodes via mknod
>       - 'c 188:* rmw' # allow creation of /dev/ttyUSBx nodes via mknod
>     devices:
>       - /dev/bus/usb
> 
>     environment:
>       - DECONZ_WEB_PORT=80
>       - DECONZ_WS_PORT=443
>       - DEBUG_INFO=2
>       - DEBUG_ERROR=2
>       - DEBUG_APS=0
>       - DEBUG_ZCL=0
>       - DEBUG_ZDP=0
>       - DEBUG_OTAU=0
> ```
> 
> * `cgroup 166` allows creation of the /dev/ttyACMx names inside the container;
> * The device is set to `/dev/bus/usb` to be able to detect dynamic USB attach / reboots;
> * The `/run/udev:/run/udev:ro` exposes vendorId, productId and serial number of ConBee II to the container, which helps with reconnecting and also doing firmware updates.
> 
> #### Test
> I've unplugged and reattached ConBee II quickly so that the /dev/ttyACM0 becomes invalid and new /dev/ttyACM1 is created on the host (but not visible in the container yet).
> In the container I could manually create /dev/ttyACM1 and deCONZ automatically connected to it.
> 
> This wasn't possible before.
> 
> #### Next steps
> The upcoming deCONZ beta version will automatically create these /dev/ttyACMx devices via `mknod` if they aren't already present.
> 
> Since this is only possible with above `cgroups` configured, deCONZ will check if the container is allowed to create these devices by checking the file `/sys/fs/cgroup/devices/devices.list` if a line with `c 166:* rwm` exists.
> 
> With these changes reconnection issues should be mitigated as this works like a native system.
> 
> **Edit:** Version [v2.7.0-beta](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.7.0-beta) contains the required changes. The above `docker-compose.yml` works for ConBee I and ConBee II.

I am currently on ver 2.05.84 and highly interested in upgrading to the current stable version to address the dynamic USB reconnect/attach issue. Need some help upgrading though since I am not technically savvy enough and don't have knowledge of Docker Compose. I currently use the following docker command line to create the container:

docker run -d \
    --name=deconz \
    --net=host \
    --restart=unless-stopped \
    --device=/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2120169-if00 \
    --env DECONZ_WEB_PORT=8080 \
    --env DECONZ_WS_PORT=8443 \
    --env DEBUG_INFO=1 \
    --env DEBUG_APS=0 \
    --env DEBUG_ZCL=0 \
    --env DEBUG_ZDP=0 \
    --env DEBUG_OTAU=0 \
    --env DECONZ_DEVICE=/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2120169-if00 \
    --env TZ=America/Chicago \
    -v /home/pi/deconz:/root/.local/share/dresden-elektronik/deCONZ \
    marthoc/deconz:stable

Have two questions:
1. How can I adapt the above command line to include the two device_cgroup_rules? Can I even use the command line for this configuration?
2. What do I mention for the two "device" line items - "--device=xxxxxxxx" and "--env DECONZ_DEVICE=xxxxxxxx"?

Thank you in advance for your time, help and suggestions.

**Comment by rkkhanna** [comment]
Folks, any suggestions / inputs towards the above?

Thanks.

**Comment by ualex73** [comment]
@rkkhanna 

Replace:
--device=/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2120169-if00 
--env DECONZ_DEVICE=/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2120169-if00 

with:
--device=/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2120169-if00:/dev/ttyACM0
--env DECONZ_DEVICE=/dev/ttyACM0

**Comment by rkkhanna** [comment]
@ualex73, thank you for your inputs. Played around with it today and got it working with the docker run below.

Tested it by unplugging and reattaching ConBee II quickly. On reattaching ConBee II connected with /dev/ttyACM2 (I have my Zwave stick on ttyACM1). A few minutes later, deCONZ started controlling the lights again!! In the past I had to restart RPI to get around the random re-enumeration of ConBee II to /dev/ttyACM2. Thank you, @manup !!!

docker run -d \
    --name=deCONZ \
    --net=host \
    --restart=unless-stopped \
    --device=/dev/bus/usb \
    --device-cgroup-rule='c 166:* rmw' \
    --device-cgroup-rule='c 188:* rmw' \
    --env DECONZ_WEB_PORT=8080 \
    --env DECONZ_WS_PORT=8443 \
    --env DEBUG_INFO=1 \
    --env DEBUG_APS=0 \
    --env DEBUG_ZCL=0 \
    --env DEBUG_ZDP=0 \
    --env DEBUG_OTAU=0 \
    --env TZ=America/Chicago \
    --env DECONZ_VNC_MODE=1 \
    --env DECONZ_VNC_PORT=5900 \
    --env DECONZ_VNC_PASSWORD=xxxxxxx \
    -v /home/pi/deconz:/root/.local/share/dresden-elektronik/deCONZ \
    -v /run/udev:/run/udev:ro \
    marthoc/deconz:stable

**Comment by sepo83** [comment]
For me mapping serial by-id path to ttyUSB0 in the container worked (ConBee with docker compose):
````
version: '2'
services:
  deconz:
    image: marthoc/deconz
    container_name: deconz
    restart: unless-stopped
    volumes:
      - deconz_data:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DM01H1BQ-if00-port0:/dev/ttyUSB0
[...]
````

**Comment by Mimiix** [comment]
As there hasn't been any new replies and as there are newer versions, i'm closing this issue. If this needs to be re-opened, please ping me :)
