### ISSUE TITLE
Container in Restarting Loop

### ISSUE THREAD

**Issue by C4mp3r-Grey** [marthoc/docker-deconz#300]
Hello Community,

need help! Conducted a `docker restart deconz` container restart. Since then, the container is in a restart loop, each approx 1 minute long.

docker logs deconz gives following result, repeated endlessly.

Prior to that loop, I was trying to connect a TRADFRI motion sensor, which worked fine, but failed in adding the respective tradfri light bulb. I hoped a restart would fix it, but it made it crash. No backup available. The WAF drowned quickly *grmpft*.

Any ideas how to fix it without an entirely new configuration from scratch?

Thanks!
CG

`12:14:52:533 ZCL attribute report 0x84182600000C4289 for cluster: 0x0006, ep: 0x03, frame control: 0x18, mfcode: 0x0000
12:14:53:052 don't close database yet, keep open for 900 seconds
12:14:55:224 dev /dev/ttyAMA0
12:14:55:224 GW firmware version: 0x26580700
12:14:55:224 GW firmware version is up to date: 0x26580700
12:14:58:177 don't close database yet, keep open for 900 seconds
12:15:05:169 don't close database yet, keep open for 900 seconds
12:15:11:192 don't close database yet, keep open for 900 seconds
12:15:16:169 don't close database yet, keep open for 900 seconds
12:15:22:172 don't close database yet, keep open for 900 seconds
12:15:22:691 no button map for: RWL021 ep: 0x02 cl: 0x0001 cmd: 0x0A pl[0]: 021
12:15:22:691 ZCL attribute report 0x0017880102C19BB6 for cluster: 0x0001, ep: 0x02, frame control: 0x08, mfcode: 0x0000
12:15:28:154 don't close database yet, keep open for 900 seconds
12:15:28:252 ZCL attribute report 0x7CB03EAA0A00F3C8 for cluster: 0x0006, ep: 0x03, frame control: 0x18, mfcode: 0x0000
12:15:33:172 don't close database yet, keep open for 900 seconds
12:15:39:168 don't close database yet, keep open for 900 seconds
12:15:40:167 Current channel 15
12:15:40:173 Device TTL 3839 s flags: 0x7
12:15:45:259 don't close database yet, keep open for 900 seconds
12:15:52:099 don't close database yet, keep open for 900 seconds
12:15:59:049 don't close database yet, keep open for 900 seconds
12:16:04:169 don't close database yet, keep open for 900 seconds
12:16:11:166 don't close database yet, keep open for 900 seconds
12:16:17:961 don't close database yet, keep open for 900 seconds
12:16:24:168 don't close database yet, keep open for 900 seconds
12:16:28:618 ZCL attribute report 0x7CB03EAA0A00D23C for cluster: 0x0006, ep: 0x03, frame control: 0x18, mfcode: 0x0000
12:16:31:172 don't close database yet, keep open for 900 seconds
12:16:38:020 don't close database yet, keep open for 900 seconds
12:16:40:168 Current channel 15
12:16:40:175 Device TTL 3779 s flags: 0x7
12:16:45:051 don't close database yet, keep open for 900 seconds
12:16:51:172 don't close database yet, keep open for 900 seconds
12:16:56:172 don't close database yet, keep open for 900 seconds
12:17:03:169 don't close database yet, keep open for 900 seconds
12:17:09:991 don't close database yet, keep open for 900 seconds
12:17:17:050 don't close database yet, keep open for 900 seconds
12:17:24:164 don't close database yet, keep open for 900 seconds
12:17:30:175 don't close database yet, keep open for 900 seconds
12:17:37:172 don't close database yet, keep open for 900 seconds
12:17:40:169 Current channel 15
12:17:40:177 Device TTL 3719 s flags: 0x7
12:17:44:000 don't close database yet, keep open for 900 seconds
12:17:50:144 don't close database yet, keep open for 900 seconds
12:17:56:173 don't close database yet, keep open for 900 seconds
12:18:02:179 don't close database yet, keep open for 900 seconds
12:18:09:166 don't close database yet, keep open for 900 seconds
12:18:15:996 don't close database yet, keep open for 900 seconds
12:18:23:049 don't close database yet, keep open for 900 seconds
12:18:29:168 don't close database yet, keep open for 900 seconds
12:18:34:172 don't close database yet, keep open for 900 seconds
12:18:40:167 Current channel 15
12:18:40:175 Device TTL 3659 s flags: 0x7
12:18:41:169 don't close database yet, keep open for 900 seconds
12:18:48:002 don't close database yet, keep open for 900 seconds
12:18:55:049 don't close database yet, keep open for 900 seconds
12:18:55:223 dev /dev/ttyAMA0
12:18:55:224 GW firmware version: 0x26580700
12:18:55:224 GW firmware version is up to date: 0x26580700
12:19:01:227 don't close database yet, keep open for 900 seconds
12:19:06:193 don't close database yet, keep open for 900 seconds
12:19:10:125 ZCL attribute report 0x7CB03EAA0A0159D6 for cluster: 0x0006, ep: 0x03, frame control: 0x18, mfcode: 0x0000
12:19:13:170 don't close database yet, keep open for 900 seconds
12:19:20:006 don't close database yet, keep open for 900 seconds
12:19:27:055 don't close database yet, keep open for 900 seconds
12:19:34:171 don't close database yet, keep open for 900 seconds
12:19:40:176 don't close database yet, keep open for 900 seconds
12:19:40:194 Current channel 15
12:19:40:202 Device TTL 3599 s flags: 0x7
12:19:47:169 don't close database yet, keep open for 900 seconds
12:19:49:572 ZCL attribute report 0x84182600000C4289 for cluster: 0x0006, ep: 0x03, frame control: 0x18, mfcode: 0x0000
`

**Comment by C4mp3r-Grey** [comment]
I don`t understand whether this is normal:
`no button map for: RWL021 ep: 0x02 cl: 0x0001 cmd: 0x0A pl[0]: 021 12:15:22:691 ZCL attribute report 0x0017880102C19BB6 for cluster: 0x0001, ep: 0x02, frame control: 0x08, mfcode: 0x0000 `

But I also do not see a reason for container restart. Does anyone?

**Comment by C4mp3r-Grey** [comment]
Oh wait! 
Is it about the GUI, that tries to start? `docker logs deconz | grep restart` returns:

```
/usr/bin/xauth:  file /root/.Xauthority does not exist
libEGL warning: DRI2: failed to open swrast (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
libEGL warning: DRI2: failed to open swrast (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
libpng warning: iCCP: known incorrect sRGB profile
libEGL warning: DRI2: failed to open swrast (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
libEGL warning: DRI2: failed to open swrast (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
libpng warning: iCCP: known incorrect sRGB profile
libEGL warning: DRI2: failed to open swrast (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
libEGL warning: DRI2: failed to open swrast (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
libpng warning: iCCP: known incorrect sRGB profile

```

How can I force the headless start when the container restarts?

**Comment by phdelodder** [comment]
Can you give more detail on your config? What version, arch?

**Comment by C4mp3r-Grey** [comment]
Of course! Thanks for having a look. Hope it is not too much info!

By the way: Recognised two suspicious entries in the `docker inspect deconz` result:
-->       "ExitCode": 134,
            **"Error": "error gathering device information while adding custom device \"/dev/ttyACM0\": no such file or directory"
-->      the other on was the hostname (which I had changed temporarily, but now is back original (pha-rasp-4ha)

I have unplugged all other USB connections, the /dev/ttyACM0 is present...

See below some details:
Raspberry Pi 4 8GB
Raspian (see below)
docker (ioBroker, deconz, portainer)

----

cat /etc/os-release:

> PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
> NAME="Raspbian GNU/Linux"
> VERSION_ID="10"
> VERSION="10 (buster)"
> VERSION_CODENAME=buster
> ID=raspbian
> ID_LIKE=debian
> HOME_URL="http://www.raspbian.org/"
> SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
> BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

docker version

> Client: Docker Engine - Community
>  Version:           19.03.13
>  API version:       1.40
>  Go version:        go1.13.15
>  Git commit:        4484c46
>  Built:             Wed Sep 16 17:07:02 2020
>  OS/Arch:           linux/arm
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          19.03.13
>   API version:      1.40 (minimum version 1.12)
>   Go version:       go1.13.15
>   Git commit:       4484c46
>   Built:            Wed Sep 16 17:00:52 2020
>   OS/Arch:          linux/arm
>   Experimental:     false
>  containerd:
>   Version:          1.3.7
>   GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
>  runc:
>   Version:          1.0.0-rc10
>   GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
>  docker-init:
>   Version:          0.18.0
>   GitCommit:        fec3683

docker ps -a

> CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                      PORTS                                            NAMES
> 01c8fac2c6fd        buanet/iobroker:v5.0.0    "/bin/bash -c /opt/s…"   7 weeks ago         Up 15 hours                                                                  myIObroker
> 333b24f93bb9        buanet/iobroker:v5.0.0    "/bin/bash -c /opt/s…"   2 months ago        Exited (0) 3 weeks ago                                                       myIObroker.old
> d9533a084c1c        portainer/portainer:arm   "/portainer"             2 months ago        Up 16 hours                 0.0.0.0:8500->8000/tcp, 0.0.0.0:9500->9000/tcp   portainer2.1
> aa5339b3c09c        elswork/samba             "/entrypoint.sh -u l…"   3 months ago        Exited (0) 2 months ago                                                      dreamy_fermat
> 1b8e684bb268        marthoc/deconz            "/tini -- /start.sh"     3 months ago        Exited (134) 15 hours ago                                                    deconz
> 

docker inspect deconz

> [
>     {
>         "Id": "1b8e684bb268121d86e2c1553113797405e6177608066a7ea1e486a2c11545cf",
>         "Created": "2020-07-29T12:00:53.340905127Z",
>         "Path": "/tini",
>         "Args": [
>             "--",
>             "/start.sh"
>         ],
>         "State": {
>             "Status": "exited",
>             "Running": false,
>             "Paused": false,
>             "Restarting": false,
>             "OOMKilled": false,
>             "Dead": false,
>             "Pid": 0,
>             "ExitCode": 134,
>             **"Error": "error gathering device information while adding custom device \"/dev/ttyACM0\": no such file or directory",**
>             "StartedAt": "2020-10-28T21:50:49.630871227Z",
>             "FinishedAt": "2020-10-28T21:50:50.089540508Z"
>         },
>         "Image": "sha256:4efb692bd168d1c953e18d7cc465b9651f194e0107aa9bd872b8265bef1be2df",
>         "ResolvConfPath": "/var/lib/docker/containers/1b8e684bb268121d86e2c1553113797405e6177608066a7ea1e486a2c11545cf/resolv.conf",
>         "HostnamePath": "/var/lib/docker/containers/1b8e684bb268121d86e2c1553113797405e6177608066a7ea1e486a2c11545cf/hostname",
>         "HostsPath": "/var/lib/docker/containers/1b8e684bb268121d86e2c1553113797405e6177608066a7ea1e486a2c11545cf/hosts",
>         "LogPath": "/var/lib/docker/containers/1b8e684bb268121d86e2c1553113797405e6177608066a7ea1e486a2c11545cf/1b8e684bb268121d86e2c1553113797405e6177608066a7ea1e486a2c11545cf-json.log",
>         "Name": "/deconz",
>         "RestartCount": 54,
>         "Driver": "overlay2",
>         "Platform": "linux",
>         "MountLabel": "",
>         "ProcessLabel": "",
>         "AppArmorProfile": "",
>         "ExecIDs": null,
>         "HostConfig": {
>             "Binds": [
>                 "/etc/localtime:/etc/localtime:ro",
>                 "/opt/deconz:/root/.local/share/dresden-elektronik/deCONZ"
>             ],
>             "ContainerIDFile": "",
>             "LogConfig": {
>                 "Type": "json-file",
>                 "Config": {}
>             },
>             "NetworkMode": "host",
>             "PortBindings": {},
>             "RestartPolicy": {
>                 "Name": "always",
>                 "MaximumRetryCount": 0
>             },
>             "AutoRemove": false,
>             "VolumeDriver": "",
>             "VolumesFrom": null,
>             "CapAdd": null,
>             "CapDrop": null,
>             "Capabilities": null,
>             "Dns": [],
>             "DnsOptions": [],
>             "DnsSearch": [],
>             "ExtraHosts": null,
>             "GroupAdd": null,
>             "IpcMode": "private",
>             "Cgroup": "",
>             "Links": null,
>             "OomScoreAdj": 0,
>             "PidMode": "",
>             "Privileged": false,
>             "PublishAllPorts": false,
>             "ReadonlyRootfs": false,
>             "SecurityOpt": null,
>             "UTSMode": "",
>             "UsernsMode": "",
>             "ShmSize": 67108864,
>             "Runtime": "runc",
>             "ConsoleSize": [
>                 0,
>                 0
>             ],
>             "Isolation": "",
>             "CpuShares": 0,
>             "Memory": 0,
>             "NanoCpus": 0,
>             "CgroupParent": "",
>             "BlkioWeight": 0,
>             "BlkioWeightDevice": [],
>             "BlkioDeviceReadBps": null,
>             "BlkioDeviceWriteBps": null,
>             "BlkioDeviceReadIOps": null,
>             "BlkioDeviceWriteIOps": null,
>             "CpuPeriod": 0,
>             "CpuQuota": 0,
>             "CpuRealtimePeriod": 0,
>             "CpuRealtimeRuntime": 0,
>             "CpusetCpus": "",
>             "CpusetMems": "",
>             "Devices": [
>                 {
>                     "PathOnHost": "/dev/ttyACM0",
>                     "PathInContainer": "/dev/ttyACM0",
>                     "CgroupPermissions": "rwm"
>                 }
>             ],
>             "DeviceCgroupRules": null,
>             "DeviceRequests": null,
>             "KernelMemory": 0,
>             "KernelMemoryTCP": 0,
>             "MemoryReservation": 0,
>             "MemorySwap": 0,
>             "MemorySwappiness": null,
>             "OomKillDisable": null,
>             "PidsLimit": null,
>             "Ulimits": null,
>             "CpuCount": 0,
>             "CpuPercent": 0,
>             "IOMaximumIOps": 0,
>             "IOMaximumBandwidth": 0,
>             "MaskedPaths": [
>                 "/proc/asound",
>                 "/proc/acpi",
>                 "/proc/kcore",
>                 "/proc/keys",
>                 "/proc/latency_stats",
>                 "/proc/timer_list",
>                 "/proc/timer_stats",
>                 "/proc/sched_debug",
>                 "/proc/scsi",
>                 "/sys/firmware"
>             ],
>             "ReadonlyPaths": [
>                 "/proc/bus",
>                 "/proc/fs",
>                 "/proc/irq",
>                 "/proc/sys",
>                 "/proc/sysrq-trigger"
>             ]
>         },
>         "GraphDriver": {
>             "Data": {
>                 "LowerDir": "/var/lib/docker/overlay2/c2da624524f85ac8374fc57bfc0f09ce1a537e3f156d756f663fe19131aa170d-init/diff:/var/lib/docker/overlay2/5ba995732fde2ab089572869cbfddecbad7ca9841ebbab58c797a21cd1b680c2/diff:/var/lib/docker/overlay2/b615575f0ec3d618a51e9ad1c6af68076db12d32167065b4b035e933ba8fbf0f/diff:/var/lib/docker/overlay2/721e851658bf6e35774c18c1a9e89844fd7ef5dabc6ae3ffb463de2e3b4f6eaf/diff:/var/lib/docker/overlay2/eb7a99cd32afdf549d231eb740cf36435a374883a1b1a90337a21d193443da6f/diff:/var/lib/docker/overlay2/71239454619cf7d6a256a738bd94716551d12161a19481a1c52a986a677e0b9c/diff:/var/lib/docker/overlay2/e717ed87088c16d6628ff26c763cfa0db43b5d9c47212f7cc1c3343fd0b01c31/diff:/var/lib/docker/overlay2/211d642dcf7fa07eb2d078862ce8650c345ab4c16a41b10c6152a84cc5946319/diff:/var/lib/docker/overlay2/2c78a289d96f8b2d51703aaf61547411920c4288dbfc3333d330eca303d9dae2/diff:/var/lib/docker/overlay2/c48922a85273543ee27c3ae462136b47bab1941d389f7f606cdefd77dc3ac44a/diff:/var/lib/docker/overlay2/0cb3fdaede0b629e79b03e74d75c7c7b0698f0e04ff1a3a58fc08b486a7e5441/diff:/var/lib/docker/overlay2/90014a6bf23837481fd206a25118eafda472c7628ba6a1d70785f7116326a5b9/diff:/var/lib/docker/overlay2/f5ee2f08635ea83ea086a64d6406d945225dd0212d9bfe81c8051b5e87781b8a/diff:/var/lib/docker/overlay2/cae4b7a6590e23674487fd03f864626e0bc8d01a933147bed9714366888125a8/diff:/var/lib/docker/overlay2/4e02058bbf6226d0b1df024a59f046f5f54d5f8a192e103a0160612c75e157a2/diff:/var/lib/docker/overlay2/4ca18d1519aa2d162ae45ba3e5b2b99de4683b724976e48b7e80730882d39431/diff:/var/lib/docker/overlay2/7bfeedf81c82dfc58bfe708ca18cfd503ef2188fc57134c571f86fd8814357e6/diff:/var/lib/docker/overlay2/7dd48e5a8529a2dc659a18958e5fceebc3f781c003e4afa67a83ddde05213f1d/diff:/var/lib/docker/overlay2/0454305d6e0edceb02e49823819e20bd7733e832b9427a40d3187224ce526062/diff:/var/lib/docker/overlay2/59454a4597e8e581fae2cc2a957c256fa963d11c296335e1d0a58a89673d4486/diff:/var/lib/docker/overlay2/c65bdc86e00316250a5f625426089b92e77af9f41af83951d27f828d45befd6b/diff:/var/lib/docker/overlay2/d1bf3e90717b5a751e68379f4ff7fdec375476309af184087bb9ed501dff1020/diff",
>                 "MergedDir": "/var/lib/docker/overlay2/c2da624524f85ac8374fc57bfc0f09ce1a537e3f156d756f663fe19131aa170d/merged",
>                 "UpperDir": "/var/lib/docker/overlay2/c2da624524f85ac8374fc57bfc0f09ce1a537e3f156d756f663fe19131aa170d/diff",
>                 "WorkDir": "/var/lib/docker/overlay2/c2da624524f85ac8374fc57bfc0f09ce1a537e3f156d756f663fe19131aa170d/work"
>             },
>             "Name": "overlay2"
>         },
>         "Mounts": [
>             {
>                 "Type": "bind",
>                 "Source": "/etc/localtime",
>                 "Destination": "/etc/localtime",
>                 "Mode": "ro",
>                 "RW": false,
>                 "Propagation": "rprivate"
>             },
>             {
>                 "Type": "bind",
>                 "Source": "/opt/deconz",
>                 "Destination": "/root/.local/share/dresden-elektronik/deCONZ",
>                 "Mode": "",
>                 "RW": true,
>                 "Propagation": "rprivate"
>             }
>         ],
>         "Config": {
>             **"Hostname": "pha-rasp-4ha",**
>             "Domainname": "",
>             "User": "",
>             "AttachStdin": false,
>             "AttachStdout": false,
>             "AttachStderr": false,
>             "ExposedPorts": {
>                 "443/tcp": {},
>                 "5900/tcp": {},
>                 "80/tcp": {}
>             },
>             "Tty": false,
>             "OpenStdin": false,
>             "StdinOnce": false,
>             "Env": [
>                 "DECONZ_VNC_MODE=1",
>                 "DECONZ_VNC_PASSWORD=xxxxxxx",
>                 "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
>                 "LC_ALL=C.UTF-8",
>                 "DEBIAN_FRONTEND=noninteractive",
>                 "UDEV=off",
>                 "TINI_VERSION=0.18.0",
>                 "DECONZ_VERSION=2.05.79",
>                 "DECONZ_WEB_PORT=80",
>                 "DECONZ_WS_PORT=443",
>                 "DEBUG_INFO=1",
>                 "DEBUG_APS=0",
>                 "DEBUG_ZCL=0",
>                 "DEBUG_ZDP=0",
>                 "DEBUG_OTAU=0",
>                 "DECONZ_DEVICE=0",
>                 "DECONZ_VNC_DISPLAY=0",
>                 "DECONZ_VNC_PORT=5900",
>                 "DECONZ_UPNP=1"
>             ],
>             "Cmd": null,
>             "Image": "marthoc/deconz",
>             "Volumes": {
>                 "/root/.local/share/dresden-elektronik/deCONZ": {}
>             },
>             "WorkingDir": "",
>             "Entrypoint": [
>                 "/tini",
>                 "--",
>                 "/start.sh"
>             ],
>             "OnBuild": null,
>             "Labels": {
>                 "io.balena.architecture": "armv7hf",
>                 "io.balena.qemu.version": "4.0.0+balena2-arm"
>             }
>         },
>         "NetworkSettings": {
>             "Bridge": "",
>             "SandboxID": "32c18eaa7ca60858751918514f247b788f64e8982c3d98dbeaa67xxxxxx",
>             "HairpinMode": false,
>             "LinkLocalIPv6Address": "",
>             "LinkLocalIPv6PrefixLen": 0,
>             "Ports": {},
>             "SandboxKey": "/var/run/docker/netns/default",
>             "SecondaryIPAddresses": null,
>             "SecondaryIPv6Addresses": null,
>             "EndpointID": "",
>             "Gateway": "",
>             "GlobalIPv6Address": "",
>             "GlobalIPv6PrefixLen": 0,
>             "IPAddress": "",
>             "IPPrefixLen": 0,
>             "IPv6Gateway": "",
>             "MacAddress": "",
>             "Networks": {
>                 "host": {
>                     "IPAMConfig": null,
>                     "Links": null,
>                     "Aliases": null,
>                     "NetworkID": "ed44c68ced769299e7137b18ba5780092f55662c1d11xxxxx",
>                     "EndpointID": "",
>                     "Gateway": "",
>                     "IPAddress": "",
>                     "IPPrefixLen": 0,
>                     "IPv6Gateway": "",
>                     "GlobalIPv6Address": "",
>                     "GlobalIPv6PrefixLen": 0,
>                     "MacAddress": "",
>                     "DriverOpts": null
>                 }
>             }
>         }
>     }
> ]
>

**Comment by phdelodder** [comment]
Can you check ls -lah /dev/ttyACM0.

**Comment by C4mp3r-Grey** [comment]
Oh, I have forgotten something important maybe:

Recently installed a HM-MOD-RPI-PCB and run piVCCU following this documentation: https://github.com/alexreinert/piVCCU/blob/master/docs/setup/raspberrypi.md

Results of 
ls -lah /dev/ttyACM0
> crw-rw---- 1 root dialout 166, 0 Okt 29 13:52 /dev/ttyACM0
ls /dev/serial/by-id
> usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2214916-if00

Guess that looks as it should?

Many thanks spending your time in my issue!!

**Comment by phdelodder** [comment]
it would be better to use /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2214916-if00 in the docker config

**Comment by C4mp3r-Grey** [comment]
Could you give me advice how to change that without loosing my zigbee config?

**Comment by C4mp3r-Grey** [comment]
should have googled first. I will try it by workaround 2 as described in
https://bobcares.com/blog/docker-change-container-configuration/

**Comment by C4mp3r-Grey** [comment]
but I wonder if that is the problem. Having rebooted the raspi (15minutes ago), docker container is in the loop again, but does **not** report that problem:


>         "Created": "2020-07-29T12:00:53.340905127Z",
>         "Path": "/tini",
>         "Args": [
>             "--",
>             "/start.sh"
>         ],
>         "State": {
>             "Status": "restarting",
>             "Running": true,
>             "Paused": false,
>             "Restarting": true,
>             "OOMKilled": false,
>             "Dead": false,
>             "Pid": 0,
>             "ExitCode": 134,
>             "Error": "",
>             "StartedAt": "2020-10-29T12:59:08.277382093Z",
>             "FinishedAt": "2020-10-29T12:59:08.899031957Z"
>

**Comment by phdelodder** [comment]
Figure out what exitcode 134 is returned, can you run the container with daemonizing it and see where it stops?

**Comment by C4mp3r-Grey** [comment]
I thought `docker start deconz` is the daemonized variant? What exactly should I do?

**Comment by C4mp3r-Grey** [comment]
How can I get a bash in deconz container? docker exec -it either reports the container does not run, or, when started, that it is restarting and i should wait.

`docker events` by the way reports the following (network connect, container start, container die, network disconnect), when the restart occurs:

> 2020-10-29T14:34:07.072274381+01:00 network connect ed44c68ced769299e7137b18ba5780092f55662c1d11fd512694c16c1eed4d82 (container=1b8e684bb268121d86e2c1553113797405e6177608066a7ea1e486a2c11545cf, name=host, type=host)
> 2020-10-29T14:34:07.319130190+01:00 container start 1b8e684bb268121d86e2c1553113797405e6177608066a7ea1e486a2c11545cf (image=marthoc/deconz, io.balena.architecture=armv7hf, io.balena.qemu.version=4.0.0+balena2-arm, name=deconz)
> 2020-10-29T14:34:07.909735080+01:00 container die 1b8e684bb268121d86e2c1553113797405e6177608066a7ea1e486a2c11545cf (exitCode=134, image=marthoc/deconz, io.balena.architecture=armv7hf, io.balena.qemu.version=4.0.0+balena2-arm, name=deconz)
> 2020-10-29T14:34:07.938480882+01:00 network disconnect ed44c68ced769299e7137b18ba5780092f55662c1d11fd512694c16c1eed4d82 (container=1b8e684bb268121d86e2c1553113797405e6177608066a7ea1e486a2c11545cf, name=host, type=host)
>

**Comment by phdelodder** [comment]
docker exec -it deconz bash

**Comment by C4mp3r-Grey** [comment]
You mean `docker version`?

> Client: Docker Engine - Community
>  Version:           19.03.13
>  API version:       1.40
>  Go version:        go1.13.15
>  Git commit:        4484c46
>  Built:             Wed Sep 16 17:07:02 2020
>  OS/Arch:           linux/arm
>  Experimental:      false
> 

`docker exec -it bash` returns

> Error response from daemon: Container 1b8e684bb268121d86e2c1553113797405e6177608066a7ea1e486a2c11545cf is restarting, wait until the container is running


But, I think I am getting closer: Three issues raised when running `docker logs deconz | grep ExitCode`

> hostname: No address associated with hostname

> A VNC/X11 server is already running as :0 on machine localhost
> QXcbConnection: Could not connect to display :0

probably leading to that follow-on error

> eabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
> libEGL warning: DRI2: failed to open swrast (search paths /usr/lib/arm-linux-gnu


I believe it is either a hostname resolution error or a problem that some process started another display:0 VNC/X11?

**Comment by C4mp3r-Grey** [comment]
> Figure out what exitcode 134 is returned for? Could it be that the ports are in use?

Which ports do you mean? 80 shoukld be free. `sudo netstat -tlnpu` reports nothing about port 80

**Comment by Mimiix** [comment]
As far as i can tell you are on a older deCONZ version. I believe this was removed on 2.05.80.

**Comment by C4mp3r-Grey** [comment]
> As far as i can tell you are on a older deCONZ version. I believe this was removed on 2.05.80.

Thanks for that remark! I have howeverno clue how to **backup the deconz config** before trying to build a new container...

**Comment by phdelodder** [comment]
Are you using docker compose? 
How do you start the docker image?
Is there a volume attached to /root/.local/share/dresden-elektronik/deCONZ ?

**Comment by C4mp3r-Grey** [comment]
> Are you using docker compose?

No, I just started a new deconz docker (on a basically fresh system) with

`docker run -d --name deconz --net=host --restart=always -v /etc/localtime:/etc/localtime:ro -v /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ --device=/dev/ttyACM0 -e DECONZ_VNC_MODE=1 -e DECONZ_VNC_PASSWORD=xxxxxx marthoc/deconz`

> How do you start the docker image?

It always started with system boot, restart policy was "always". Yesterday (when it broke) I conducted a `docker restart deconz`, I never had to stop it before...

> Is there a volume attached to /root/.local/share/dresden-elektronik/deCONZ ?

no volume attached there. The folder deCONZ does not exist. Should it?

**Comment by phdelodder** [comment]
is there data in this folder: /opt/deconz? 

If you have data in that folder, do:
docker stop deconz
docker pull marthoc/deconz
docker start deconz

**Comment by C4mp3r-Grey** [comment]
I have data in that folder, yes:

>   4 -rw-r--r-- 1 root root    180 Okt 23 18:30 config.ini
>  16 -rw-r--r-- 1 root root  14671 Jul 29 14:15 deCONZ.tar.gz
>   8 -rw-r--r-- 1 pi   pi     6163 Okt 28 21:21 session.default
>   4 -rw-r--r-- 1 root root     35 Jul 29 12:59 zcldb.txt
> 180 -rw-r--r-- 1 pi   pi   184320 Okt 28 21:26 zll.db

Interestingly, some files are from pi, others root. Normal?

Sure I can pull a new image?

**Comment by phdelodder** [comment]
These are files create by the container, I should be save to pull the new image

**Comment by C4mp3r-Grey** [comment]
`Pull` ran fine.
Started deconz --> Restarting (134)

**Comment by C4mp3r-Grey** [comment]
Concerning the VNC/X11 error message: can I switch off the VNC option by any means?

**Comment by C4mp3r-Grey** [comment]
Problem solved!

Killed the malfunctioning docker container "docker" and created a new one without VNC:
`docker run -d --name deconz --net=host --restart=always -v /etc/localtime:/etc/localtime:ro -v /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ --device=/dev/ttyACM0 marthoc/deconz`

It seems that the entire config is still present.
