### ISSUE TITLE
Flashing error while updating to last firmware

### ISSUE THREAD

**Issue by ErCanotta** [marthoc/docker-deconz#301]
Hi,
I have a Raspberry Pi4 and I'm running Hassio on docker from Raspbian.
I've also a Raspbee on /dev/ttyAMA0
I've also change config.txt in adding those:

#enable_uart=1
dtoverlay=miniuart-bt

(activating or not #enable_uart=1 seems not effective)

I've installed the deCONZ add-on on HomeAssistant, but unfortunately the firmware seems not connected and Zigbee channel is stuck to 0 . Also it is impossible to pair any kind of sensor.
I've tried your procedure to update deCONZ to last firmware (after switching off the deCONZ addon) from Home Assistant SSH terminal (disabling protection mode), but unfortunately I'm having this error:

Flashing...

GCFFlasher V3_15 (c) dresden elektronic ingenieurtechnik gmbh
Reboot device /dev/ttyAMA0 (RaspBee)
action: reset device RaspBee
wiringP1 2.52 initialized

Flashing Error! Please re-run script...

Can you please help me? Is there something wrong in my procedure?

Best regards.

**Comment by Jo-Be-Co** [comment]
Hi,
every time I had an issue like this I could solve this by flashing my stick on a windows system. But even there I had to try it more than once in some cases.
By now I would say the options for `retries` and `timeout` would fix this if used when flashing the "docker-way".

@nhulsch proposed a fix for this in #294 - but somehow it didn't make to the scripts though it has been merged ...
In my fork I have done another approach - there I am reading the options you could specify while starting docker with an entrypoint. See #318. Additionally I could specify default in this implementation ...

**Comment by davewood** [comment]
I just bought a conbee II stick and tried to flash a new firmware following this procedure: https://github.com/marthoc/docker-deconz#updating-conbeeraspbee-firmware

got the same error

```
david@xps:~/dev/conbee$ docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz
-------------------------------------------------------------------

             marthoc/deconz Firmware Flashing Script

                       Version: 0.6

-------------------------------------------------------------------


Listing attached devices...

GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyACM0     | 0x1CF1 | 0x0030  |            | ConBee II

Enter the full device path, or press Enter now to exit.

Device Path : /dev/ttyACM0

-------------------------------------------------------------------
                        
Firmware available for flashing:
deCONZ_ConBeeII_0x26660700.bin.GCF
deCONZ_ConBeeII_0x26680700.bin.GCF
deCONZ_RaspBeeII_0x26690700.bin.GCF
deCONZ_Rpi_0x26350500.bin.GCF
deCONZ_Rpi_0x26390500.bin.GCF

Enter the firmware file name from above, including extension.
Alternatively, you may enter the name of a firmware file to download
from http://deconz.dresden-elektronik.de/deconz-firmware/
or press Enter now to exit.
                        
File Name : deCONZ_ConBeeII_0x26660700.bin.GCF
                        
-------------------------------------------------------------------
                        
Device: /dev/ttyACM0    
                        
Firmware File: deCONZ_ConBeeII_0x26660700.bin.GCF
                        
Are the above device and firmware values correct?
Enter Y to proceed, any other entry to exit: Y
                        
Flashing...             
                        
GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2219384-if00 (ConBee II)
deCONZ firmware version 26580700
R21B18 Bootloader       
Vers: 2.07              
build: Jun 17 2019      
flashing 164106 bytes: |=error: timeout flashing firmware after 3002 ms
                        
Flashing Error! Please re-run this script...
```

**Comment by davewood** [comment]
I was able to recover AND upgrade the firmware -> https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4342

**Comment by Mimiix** [comment]
As there hasn't been any new replies and as there are newer versions, i'm closing this issue. If this needs to be re-opened, please ping me :)
