### ISSUE TITLE
Wohnzimmer fehlt

### ISSUE THREAD

**Issue by r2ixuz** [marthoc/docker-deconz#307]
Im Webadmin (Phoscon App) fehlt seit ca. zwei Versions-Updates die Gruppe Wohnzimmer. Will man die Gruppe neu erstellen, kommt eine Fehlermeldung, dass sie bereits existiert. Geräte die Wohnzimmer zugeordnet waren, sind nun keiner Gruppe zugeordnet.

Da ich die Weboberfläche nur zur Kontrolle nutze, ist mir das eigentlich egal, wollte es nur mal berichten. :-)

Benutze den letzten stable amd64 docker container:

Version 2.05.87 / 15.10.2020
Firmware 26580700 (ConBee II)

P.S. Im repo von deconz-rest-plugin werde ich keinen issue erstellen, da mir dieses template auf den Sack geht. Nach 3 Versuchen habe ich aufgegeben.

**Comment by Mimiix** [comment]
As there hasn't been any new replies and as there are newer versions, i'm closing this issue. If this needs to be re-opened, please ping me :)
