### ISSUE TITLE
Deconz - Conbee II - keine Verbindung zu Xiaomi Sensoren seit 2.05.79

### ISSUE THREAD

**Issue by simon2207** [marthoc/docker-deconz#314]
Hi,

Raspberry Pi 4 - 4GB 
Aktuelles OS - Docker etc.
Conbee II - Firmware 26660700
Deconz - 2.05.79 - 02.06.00

Nach ca. einem Jahr der wunderbaren Nutzung meiner Docker / Conbee II / Xiaomi Installation - denke ich ist es an der Zeit alles aus dem Fenster zu werfen.

Nach einem Upgrade von Deconz 02.05.79 auf 80/81 funktionierte die Verbindung zum Conbee nicht mehr - dieses Issue konnte dann unter Version 82 gefixt werden. Nun habe ich seit dem aber nur noch Kontakt zur Hälfte meiner Xiaomi Sensoren - Tür / Fenster - Temperatur - Buttons - ca. 20 Stück. 

Batteriewechsel - Resets - mehrfache Versuche von Firmware Upgrades, Versionssprüngen zwischen - Latest / Stable / Beta - ergebnislos. 

Die Kombination aus Deconz - Conbee II und Xiaomi Sensoren funktioniert nicht mehr zuverlässig und es ist enttäuschend zu sehen, das der Fehler in vielen Bug Reports dokumentiert und als resolved behandelt wird - obwohl es viele zu geben scheint die ähnliche Probleme haben.

Leider können "alte" Sensoren von Xiaomi auch nach einem Reset nicht mehr gepaired werden, und gleiches gilt auch für Tests mit Philips HUE Remotes oder IKEA Bewegungsmeldern der alten Generation. 

Vielleicht gibt es ja jemanden der noch einen Lösungsansatz hat...

PS: ja ich habe sogar die Docker Install / Deconz gelöscht und KEIN Backup verwendet - um von Scratch zu starten um Fehler auszuschliessen... vergeblich... Conbee II funkt nur noch mit der Hälfte meiner Sensoren - ... 

Danke und Gruß
Simon

**Comment by LightningRhino** [comment]
Same problem here. Don't know which update caused this.
I'm now running 2.06.00 / 15.11.2020 and my Xiaomi devices show the "not reachable" status.

**Comment by simon2207** [comment]
Thanks - hopefully we find someone who can help or explain.

**Comment by Mimiix** [comment]
This seems to be a issue unrelated to Docker. If it's still valid, please open one here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/new/choose
