### ISSUE TITLE
Options for GCFFlasher

### ISSUE THREAD

**Issue by Jo-Be-Co** [marthoc/docker-deconz#318]
Hi @marthoc ,
please have a look at my modification of the [firmware-update.sh](https://github.com/Jo-Be-Co/docker-deconz/blob/improve-firmware-update/amd64/root/firmware-update.sh).
On invocation of the update-script you could additionally add options:
```shell
docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz <option1> <value1> <option2> <value2> ...
```
These options will be read by the script and checked against the possible options of the `GCFFlasher_internal`. Using this mechanism one could specify values for `timeout`, `retries` or the `loglevel`.
Additionally the script defines a default for the `timeout`-parameter.
Feel free to comment my [pull request](https://github.com/Jo-Be-Co/docker-deconz/pull/7).

**Comment by Mimiix** [comment]
As there hasn't been any new replies and as there are newer versions, i'm closing this issue. If this needs to be re-opened, please ping me :)

**Comment by Jo-Be-Co** [comment]
Thanks @Mimiix for your support on these stacking issues.
For mine I actually don't know if @marthoc had the time to dive into this ...

**Comment by phdelodder** [comment]
Can you create a pull request here so I can find some time to test it?
