### ISSUE TITLE
Flashing firmware for `Rasp Bee II` requires different parameter in the `firmware-update.sh` script

### ISSUE THREAD

**Issue by mfloryan** [marthoc/docker-deconz#321]
According to the [firmware update instructions](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually#update-in-raspbian) for dconz on Raspbian the flasher for `Rasp Bee II` should be called like this:
```bash
sudo GCFFlasher_internal -t 60 -f deCONZ_RaspBeeII_0x26680700.bin.GCF
```
Without the `-d` argument.

So the current version of [firmware-update.sh](https://github.com/marthoc/docker-deconz/blob/master/armv7/root/firmware-update.sh#L97) should exclude the `-d` argument when flashing `Rasp Bee II` but include it when flashing `Con Bee II`.

**Comment by manup** [comment]
Both should work for RaspBee I and II, without device `-d` and with `-d <device path>`.

**Comment by mfloryan** [comment]
I have just tested and the upgrade failed with the `-d` option for me but succeeded without it. When there is no `-d` option the firmware upgrade uses `wiringpi` and appears to succeed. This might just be my experience with my hardware setup.

**Comment by Mimiix** [comment]
As there hasn't been any new replies and as there are newer versions, i'm closing this issue. If this needs to be re-opened, please ping me :)
