### ISSUE TITLE
Unauthorized to retrieve API key

### ISSUE THREAD

**Issue by sljdhl** [marthoc/docker-deconz#323]
Hello, im trying to retrieve an API key to use with homebridge. My integration in Homeassistant already works, it works with homebridge until a reboot of my server.

Im trying to access the key through IP:PORT/api and this is the response
`[
    {
        "error": {
            "address": "/",
            "description": "unauthorized user",
            "type": 1
        }
    }
]`

It doesnt matter if I press the "Authenticate app" button in the advanced settings of the GUI. Any suggestions on what could be wrong?

**Comment by marthoc** [comment]
This seems to not be related to Docker specifically... closing for now.
