### ISSUE TITLE
Network was not found...

### ISSUE THREAD

**Issue by nicedevil007** [marthoc/docker-deconz#327]
![image](https://user-images.githubusercontent.com/17103076/101097558-ae0d4e80-35c1-11eb-8d92-89551f720aae.png)

As the image describes I have this problem on my debian based linux running docker.
All packages are update to the latest version and the Conbee II stick is updated the latest version deCONZ_ConBeeII_0x26680700.bin.GCF.

The image of the docker contaier is 2.0.7. On my own raspberry Pi this is running fine. On the client I installed it now I get this error.

**Comment by RealSchlimbo** [comment]
I had the same issue yesterday, in the console output I found following error massage: "dev can't create file: /dev/ttyACM0 via
mknod (missing permissions)". 
Then I just changed the device from "/dev/ttyUSB0" to "/dev/ttyACM0" in my docker-compose file and after that it was working.

**Comment by nicedevil007** [comment]
i get this in docker logs


`13:58:18:623 dev can't create file: /dev/ttyACM0 via mknod (missing permissions)`

**Comment by nicedevil007** [comment]
Hahahaha forget it...
problem solved... problem was just sitting right in front of the PC!

forgot the dialout usermod thing and to mount the USB device into the docker container.... because I was using portainer (that doesn't support device handling in the gui).

**Comment by siaox** [comment]
> Hahahaha forget it... problem solved... problem was just sitting right in front of the PC!
> 
> forgot the dialout usermod thing and to mount the USB device into the docker container.... because I was using portainer (that doesn't support device handling in the gui).

Hey man I'm on the same issue - what do you mean?

**Comment by hajtux** [comment]
Hello siaox, 

You have to run this command : 
sudo usermod -a -G dialout $USER

See [prerequisite](https://github.com/marthoc/docker-deconz#pre-requisite)  for running the deConz container
