### ISSUE TITLE
How can I see my Zigbee Mesh?

### ISSUE THREAD

**Issue by Zuendapp** [marthoc/docker-deconz#328]
Hello,

sorry for my newbie question.
How can I visualize my Zigbee Mesh Network? Is there any way with the Docker Container via Phoscon App or have I to install the Windows Application and connect the ConBee II Stick to my Windows PC?

Thank you very much!

BR

**Comment by n0nk** [comment]
Hi,
as described here --> https://github.com/marthoc/docker-deconz#environment-variables
Set \*VNC\* environment variables to enable VNC

-e DECONZ_VNC_MODE=1
-e DECONZ_VNC_PORT=5900
-e DECONZ_VNC_PASSWORD=changeme

afterwards you can connect via vnc using a vnc client of your choice.

Greetings,
n0nk

**Comment by Zuendapp** [comment]
Hi,

thank you very much :)!!

Greetings
