### ISSUE TITLE
Update RaspBee firmware on hass.io via SSH failed (invalid character 'c' looking for beginning of value.`)

### ISSUE THREAD

**Issue by jantje88** [marthoc/docker-deconz#33]
I am using the Hass.io 0.73.0 image on a RPi3 with the DeCONZ add-on and a RaspBee and want to update the firmware of the RaspBee. After connecting via [SSH on port 22222](https://developers.home-assistant.io/docs/en/hassio_debugging.html) step 3 of this tutorial https://github.com/marthoc/docker-deconz#updating-conbeeraspbee-firmware  gives me an error:

`docker: Error response from daemon: invalid character 'c' looking for beginning of value.`

Any change to update the RaspBee firmware as a Hass.io user?

**Comment by marthoc** [comment]
Follow the instructions in this post: https://community.home-assistant.io/t/marthoc-deconz-addon-cant-connect-lights/57143/12?u=marthocoo .

**Comment by jantje88** [comment]
Fixed, thanks!
