### ISSUE TITLE
Backup zurückspielen

### ISSUE THREAD

**Issue by tonibert** [marthoc/docker-deconz#331]
Hallo ich hatte bisher in Conbee auf einem Raspy laufen.Nun wollte ich alles auf meine NAS umziehen. Funktioniert prima. Nun wollte ich gerne ein Backup meines laufenden Conbee  einspielen aber sobald ich das machen kann ich mich nicht mehr anmelden.
Ich wollte mir durch das Backup ersparen alle Sensoren, Lampen etc neu anzulernen

**Comment by Mimiix** [comment]
As there hasn't been any new replies and as there are newer versions, i'm closing this issue. If this needs to be re-opened, please ping me :)
