### ISSUE TITLE
Continuous reports of "sleeping end device" in deConz console. 

### ISSUE THREAD

**Issue by oywino** [marthoc/docker-deconz#336]
I use deCONZ v2.08 running in a Docker Container and a ConBee II with firmware v26660700
Lately these lines began to flood the console;
![image](https://user-images.githubusercontent.com/18447119/103176337-1d98f580-4871-11eb-913d-768e3636eb65.png)

(I included some in-between-outputs which I think is irrelevant)
My question is; How can I find out which end device these log entries are related to?

**Comment by Mimiix** [comment]
As there hasn't been any new replies and as there are newer versions, i'm closing this issue. If this needs to be re-opened, please ping me :)

**Comment by oywino** [comment]
I have upgraded to deConz v2.10.0 last week, and the problem still persist.
Why would the code throw unidentifiable error messages?  Such messages server no purpose unless they can be tied to "something" that enable me to trace the issue (and hopefully fix or remove it).

**Comment by Mimiix** [comment]
I suggest opening a issue in the deCONZ repo as this seems unrelated to docker :)

**Comment by oywino** [comment]
Yes, you are of course right. Sorry. I don't know why I posted it here. I'll repost over in the deCONZ repo.
Feel free to close.
