### ISSUE TITLE
Device fails to add when using phoscon webapp via docker

### ISSUE THREAD

**Issue by djurcola** [marthoc/docker-deconz#337]
Hi All,
I am trying to connect my Schlage BE468 with conbee 2 via the phoscon webapp accessible from the docker container.
I attempt to add the device as a light but it wont connect.
To confirm the lock works, I connected the conbee 2 to my windows computer, opened phoscon webapp, and successfully paired the lock.
Both times the lock was right next to the conbee stick, there should have been minimal interference.
Docker container shows firmware is all up to date.

I did notice this in the logs while attempting to connect but not sure if relevant: 

21:06:26:617 unknown node 0x90FD9FFFFE0CA698 (0xE616), lqi: 255
21:06:26:617 0x8658 nwk changed to 0xE616
21:06:26:617 device announce 0x90FD9FFFFE0CA698 (0xE616) mac capabilities 0x80
21:06:26:617 set fast probe address to 0x90FD9FFFFE0CA698 (0xE616)
21:06:26:617 FP indication 0x0000 / 0x0013 (0x90FD9FFFFE0CA698 / 0xE616)
21:06:26:617 ... (0x90FD9FFFFE0CA698 / 0xE616)
21:06:26:617 device announce 0x90FD9FFFFE0CA698 (0xE616) mac capabilities 0x80

Any help would be appreciated!
Thanks

**Comment by Mimiix** [comment]
This seems to be a issue unrelated to Docker. If it's still valid, please open one here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/new/choose
