### ISSUE TITLE
Synology Docker: Error gathering device information

### ISSUE THREAD

**Issue by EddieDSuza** [marthoc/docker-deconz#339]
I wanted to revert back to my earlier setup with Conbee II connected to my Synology NAS 218+. I even did a video tutorial on it but this morning when I went to revert back - this is the error I am getting.

Additional also made sure thru super user was able to register the device.

`[  271.027589] usbcore: registered new interface driver usbserial

[  276.605277] usbcore: registered new interface driver ftdi_sio

[  276.611760] usbserial: USB Serial support registered for FTDI USB Serial Device`

`EddieD@XHomeServer:~$  sudo docker run -d     --name=deconz     --net=host     --restart=always     -v /etc/localtime:/etc/localtime:ro     -v /volume1/docker/deconz/opt:/root/.local/share/dresden-elektronik/deCONZ     --device=/dev/ttyACM0     marthoc/deconz

47c1315f1f534d8760d3a74792b91636658df0ac6d344a29d61feeb901014cd8

docker: Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device "/dev/ttyACM0": no such file or directory.`

would appreciate the assistance. Thanks and keep up the good work !!!

**Comment by EddieDSuza** [comment]
<img width="958" alt="Screen Shot 2021-01-05 at 21 46 48" src="https://user-images.githubusercontent.com/52710883/103715513-900b8300-4f9f-11eb-8a39-96cb331276d5.png">

Heres also the confirmation that the device is connected to the NAS

**Comment by eddiedsouza** [comment]
So this is the **FIX** and this one is for those who have moved to DSM 7 as the current beta version does not support external USB devices and their drivers. Please follow these steps - 

1. Log in to your synology via Putty or terminal 
2. change to power user `sudo -su` and `run `following commands in order - 
- modprobe usbserial
- modprobe ftdi_sio
- modprobe cdc-acm
3. Unplug Conbee II stick and plug it back in.
4. Execute Docker Container as per the instructions 

**Until DSM 7 is in Beta Mode - you'll need to run a startup script to execute point 2. To do that - do the below**

Make a script DSM7_enable_usb.sh in the following folder:
`/usr/local/etc/rc.d/`
with the following content:

```
Bash:
#!/bin/sh
# Enable USB Stick in DSM 7

case "$1" in
    start)
        echo "Start"
        echo "setting usbserial"
        /sbin/modprobe usbserial
        echo "setting ftdi_sio"
        /sbin/modprobe ftdi_sio
        echo "setting cdc-acm"
        /sbin/modprobe cdc-acm
        echo "Done..."
        ;;
   *)
        echo "Usage: $1 {start}"
        exit 1
esac
exit 0
```

**Comment by atr00** [comment]
Has anyone tested with the final version of DSM 7.0?

**Comment by EddieDSuza** [comment]
I did test this on Jan 06th - its the response above

**Comment by midijunk** [comment]
Hi, I did try this solution (3x modprobe xxx) with my cc2652 from slaesh but it seems it doesnt work. lsusb shows my stick but it can't be found under ttyACMx or ttyUSBx. Seems like a driver problem?

**Comment by mirceadamian** [comment]
@midijunk Your stick requires either ch341 or cp210x support in your linux kernel. The one that comes with DSM 7.0 does not have this built in or as a module.

The reason it works in VM is because the kernel in that VM likely has the support compiled in.
I'm also running HA in a docker container and have exactly the same problem. I'm waiting for Synology to publish the kernel source so I can cross compile these exact two modules for my Synology DS718+

**Comment by Thoky81** [comment]
> So this is the **FIX** and this one is for those who have moved to DSM 7 as the current beta version does not support external USB devices and their drivers. Please follow these steps -
> 
> 1. Log in to your synology via Putty or terminal
> 2. change to power user `sudo -su` and `run `following commands in order -
> 
> * modprobe usbserial
> * modprobe ftdi_sio
> * modprobe cdc-acm
> 
> 1. Unplug Conbee II stick and plug it back in.
> 2. Execute Docker Container as per the instructions
> 
> **Until DSM 7 is in Beta Mode - you'll need to run a startup script to execute point 2. To do that - do the below**
> 
> Make a script DSM7_enable_usb.sh in the following folder:
> `/usr/local/etc/rc.d/`
> with the following content:
> 
> ```
> Bash:
> #!/bin/sh
> # Enable USB Stick in DSM 7
> 
> case "$1" in
>     start)
>         echo "Start"
>         echo "setting usbserial"
>         /sbin/modprobe usbserial
>         echo "setting ftdi_sio"
>         /sbin/modprobe ftdi_sio
>         echo "setting cdc-acm"
>         /sbin/modprobe cdc-acm
>         echo "Done..."
>         ;;
>    *)
>         echo "Usage: $1 {start}"
>         exit 1
> esac
> exit 0
> ```

I have followed your post and created the file with script but after today power lost and synology restart it looks like the script didnt run. I made the file like this:

root@DSM:~# nano /usr/local/etc/rc.d/DSM7_enable_usb.sh

maybe I am doing something wrong?

Thanks

**Comment by makgiber1984** [comment]
Can someone explain step by step how to create the script and put it in the folder you indicate of Synology?, I'm a novice with Linux, and I don't know how to do that by SSH.

He tried to do it with "Scheduled Tasks" but he didn't either.

I appreciate your help.
