### ISSUE TITLE
Firmware Update for ConBeeII when hardware is RaspBeeII

### ISSUE THREAD

**Issue by liambresnahan** [marthoc/docker-deconz#340]
Hi Folks, 

I have received my RaspBeeII today and noticed I have a firmware update according to the logs. However, it's listing the update as ConBeeII instead of RaspBeeII. Is that expected. Log snip is below.

13:23:44:232 dev /dev/ttyAMA0
13:23:45:324 dev /dev/ttyAMA0
13:23:45:335 COM check bootloader
13:23:47:345 COM timout query bootloader, assume application
13:23:47:398 Device firmware version 0x26610700 RaspBee II
13:23:47:430 unlocked max nodes: 200
13:23:47:623 Device protocol version: 0x010B
13:23:47:674 CTRL restore cached node 0x00212effff062202
13:23:47:674 Node zombie state changed 0x00212effff062202
13:23:47:677 new node - ext: 0x00212effff062202, nwk: 0x0000
13:23:47:803 Current channel 15
13:23:47:846 CTRL ANT_CTRL 0x03
13:23:47:931 Device protocol version: 0x010B
13:23:48:067 Current channel 15
13:23:48:110 CTRL ANT_CTRL 0x03
13:23:49:614 dev /dev/ttyAMA0
13:23:49:614 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26660700.bin.GCF
13:23:49:614 GW firmware version: 0x26610700

**Comment by mrclschstr** [comment]
Today I noticed the same issue. I nearly flashed the `deCONZ_ConBeeII_0x26660700.bin.GCF` firmware instead of `deCONZ_RaspBeeII_0x26690700.bin.GCF`...

**Comment by Mimiix** [comment]
As there hasn't been any new replies and as there are newer versions, i'm closing this issue. If this needs to be re-opened, please ping me :)
