### ISSUE TITLE
/usr/bin/../share/deCONZ/plugins no plugin directory found  (unearthing of #159)

### ISSUE THREAD

**Issue by GallusMax** [marthoc/docker-deconz#342]
I cannot confirm this is solved, as I face the exact issue.

/usr/bin/../share/deCONZ/plugins no plugin directory found

while using the latest version of deCONZ 2.09.00.

[marthoc/deconz] Starting deCONZ...
[marthoc/deconz] Current deCONZ version: 2.09.00

Any help is appreciated, as I am a beginner in deCONZ trying for days now to figure this software surprise ;-)

(please read on for more details at #159 )

**Comment by GallusMax** [comment]
Might have the same root cause: The fileselector opened by deCONZ shows _no_ path at all.

How to reproduce:
Open Preference Menu, opening a window allowing the adding of more .xml files.
ADD opens a fileselector (at filesystem root), but WITHOUT ANY PATH.
You may enter a (known) path "/usr/share ..." whcich is even autocompleted by TAB, but nothing appears in the folder view above.

Remembering the result "no plugin directory found" starts to sound like "no directory found _ever_" ?

**Comment by GallusMax** [comment]
(Indeed I found a "solution" in rolling back by specifying the image "marthoc/deconz:amd64-2.05.67")
- plugin directoy is found, and thus REST is working
- file selector allows browsing directory tree, and thus general.xml ist found

Downside is I am fixed to a somewhat outdated version. Any help in sight?

**Comment by GallusMax** [comment]
In the meantime I tried - to some success - to build a docker image based on the deconz:amd64-2.05.67. But I ADDed the current 2.09.00 deconz.deb.
It works! Container runs, paths are found, learned devices are present!

Leaving the question, what might have changed on the way to the deconz:latest image. .
Any comments?

**Comment by peterlindeman** [comment]
Notice the same problem here on two different systems (Scientific Linux 7.6 host) I notice that when I run the container with the "--privileged" parameter it does work.

**Comment by Mimiix** [comment]
As there hasn't been any new replies and as there are newer versions, i'm closing this issue. If this needs to be re-opened, please ping me :)

**Comment by rustyb** [comment]
@Mimiix I think this one might still be an issue, it would seem that the plugins path cannot be found when I use the latest images. 

Seems to be once you use the buster base image it doesn't work but if you revert the base to stretch version, something like `FROM balenalib/amd64-debian:stretch-run` deconz will find the plugins on startup. Any idea what might cause it?

**Comment by Mimiix** [comment]
@senilio can you check the comment from @rustyb ?
