### ISSUE TITLE
phoscon app connect to backend api over web dns address only the first time

### ISSUE THREAD

**Issue by DAMEK86** [marthoc/docker-deconz#343]
try to expose deconz over my k3s cluster with nginx over public dns provider.

I deploy deconz with helm chart https://github.com/k8s-at-home/charts/tree/master/charts/deconz which works very well if I use the default ingress (deconz.local).

**behavior for deconz.local**
to connect to deconz.local, I added "<ip> deconz.local" to my /etc/hosts file
result:
```
scanner worker init
https://deconz.local/api/config
add ip deconz.local
found gw: deconz.local
add ip 10.42.0.118:80
https://deconz.local/api/config?_=1610322827671 (OK)
https://10.42.0.118:80/api/config?_=1610322827693 (canceled)
```

**behavior for https://my-domain.de**
with my external domain, however, I see the following logs/network requests
```
scanner worker init
https://my-domain.de/api/config
add ip 10.42.0.118:80
https://10.42.0.118:80/api/config?_=timestamp (canceled)
```

10.42.0.118 stands for the node IP but I didn't see the load balancer IP which is resolved on the .local behavior

is there a workaround for defining a default IP or dns name? or disabling the discovery and work with the host url so I can work with pwa app?
with the current behavior, the pwa app isn't working over dns as expected.

A valid solution is using the default route over the request-host since the pwa app isn't shipped standalone (i think)?

I think this is the main problem is matching the defined IP ranges wich never matches over public IP's
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/702 points to this problem too

**Comment by Mimiix** [comment]
This seems to be a issue unrelated to Docker. If it's still valid, please open one here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/new/choose
