### ISSUE TITLE
After Host Reboot, Zigbee Network and Channel have changed

### ISSUE THREAD

**Issue by scobby** [marthoc/docker-deconz#347]
This is a very weird problem. 
After a host restart, the Zigbee Network ID has changed to always the same  "4C4C" and the channel is 20.
I have to restore the latest Backup with "Zigbee Network ID" 88CC and change the channel back to 25.
If i just shut down the container with "docker-compose down" and restart it again, this doesnt happen.
Any ideas?

**Comment by Mimiix** [comment]
As there hasn't been any new replies and as there are newer versions, i'm closing this issue. If this needs to be re-opened, please ping me :)
