### ISSUE TITLE
Silvercrest motion sensor (Lidl) on raspberry (openhab 2.5. / deCONZ) 

### ISSUE THREAD

**Issue by franzda** [marthoc/docker-deconz#348]
Hi there
I use Raspberry / openhab 2.5.1 / deCONZ / ConBee II)
I installed both version 2.07.02 and 2.09.01 ( 23.12.2020). The behavior is the same. The sensor is recognized and runs fine on / in openhab (the integration is quite shaky but it works)

An open point is the duration of the detection display. The sensor displays "detected" for 65 seconds. In the rule, it must be taken into account when and how the next detection is to be recognized because no second detection is registered while detection is being displayed. (but this is not an issue just needs to be considered)
Times shorter than 65 seconds (as far as I have seen) are not possible.

**Does anyone know how the duration of the detection in the sensor data set can be adjusted?**

We can exchange ideas about the rule definition in openhab

**Comment by Mimiix** [comment]
This seems to be a issue unrelated to Docker. If it's still valid, please open one here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/new/choose
