### ISSUE TITLE
Multiarch version specific tags

### ISSUE THREAD

**Issue by mattsve** [marthoc/docker-deconz#350]
It would be really nice if multiarch version specific tags were provided. I run deconz in a k8s cluster manged by argocd and I like to pin the version for easy controlled upgrade. I'm in process of adding a raspberry pi 4 to the cluster (right now it has only amd64 nodes) which will have the conbee attached. It would be great if I could just specify marthoc-deconz:2.09.01 because then I would not have to change anything about the deployment and it would just work.

**Comment by marthoc** [comment]
I am working on adding support for this now.
