### ISSUE TITLE
Not connecting to hardware Raspbee II

### ISSUE THREAD

**Issue by Exhibit99** [marthoc/docker-deconz#351]
Hello,
I have absolutely no coding experience and it may be that I phrase this badly and am being dumb.  Any help will be appreciated.  I have set up raspberry operating system on a RPI 4 8GB running on an NVME not an SD card.  I have raspbee II installed.  Previously when running on an SD card I used the phoscon image and everything worked great.  I have now installed using these instructions Phoscon on docker.  However when I search for any device nothing is found - the devices are in pairing mode.

I then went on to install home assistant via docker and again installed deconz set the hardware path to /dev/ttyAMA0 again nothing is found when a search for lights or sensors are made.

I'm guessing that the Raspbee II is not searching or connecting to the software.  I suspect I'm making some basic error and hope someone can help me.

thanks

JT

This is an extract from the log:
22:34:17:494 COM: /dev/ttyAMA0 / serialno: , RaspBee
22:34:17:502 device disconnected reason: 4, index: 0
22:34:18:405 wait reconnect 15 seconds
22:34:18:454 dev /dev/ttyAMA0
22:34:18:454 COM: /dev/ttyAMA0 / serialno: , RaspBee
22:34:18:954 dev /dev/ttyAMA0
22:34:19:406 wait reconnect 14 seconds
22:34:20:405 wait reconnect 13 seconds
22:34:20:905 failed to reconnect to network try=3
22:34:21:405 wait reconnect 12 seconds
22:34:22:405 wait reconnect 11 seconds
22:34:23:406 wait reconnect 10 seconds
22:34:24:406 wait reconnect 9 seconds
22:34:25:406 wait reconnect 8 seconds
22:34:25:905 failed to reconnect to network try=4
22:34:26:406 wait reconnect 7 seconds
22:34:27:405 wait reconnect 6 seconds
22:34:28:406 wait reconnect 5 seconds
22:34:28:985 dev /dev/ttyAMA0

**Comment by mikezwgr** [comment]
Hi 

I have the same problem - I tried to update the firmware (as described in the readme) - it seemed to work - 
but I still had problems - the solution than was to set the right ports (I wantet to use different ports than 80 and 443 do I just used -p 8001:80 but you also need -e DECONZ_WEB_PORT parmeter) 

` docker run -d \
--name=deconz \
--restart=always \
-p 8001:8001 \
-e DECONZ_WEB_PORT=8001 \
-p 4443:4443 \
-e DECONZ_WS_PORT=4443 \
-v /etc/localtime:/etc/localtime:ro \
-v /etc/deCONZ:/root/.local/share/dresden-elektronik/deCONZ \
--device=/dev/ttyACM0 \
-e DECONZ_DEVICE=/dev/ttyACM0 \
marthoc/deconz`

**Comment by Exhibit99** [comment]
Thanks, just updated the docker run command to be the same as what you pasted. It complained about /dev/ttyACM0, but that is because I think our device is on /dev/ttyAMA0 instead. 

This is our docker-compose:

`version: "2"
services:
  deconz:
    image: marthoc/deconz
    container_name: deconz
    ports:
      - "1066:1066/tcp"
      - "4443:4443/tcp"
    restart: always
    volumes:
      - /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyAMA0
    environment:
      - DECONZ_WEB_PORT=1066
      - DECONZ_WS_PORT=4443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_DEVICE=/dev/ttyAMA0`

It's up and running as far as the UI is concerned. It appears as an integration in Home Assistant but it cant get the API key when trying to authenticate. Nor can it find any of the lights...

Any other suggestions?

**Comment by alfagero** [comment]
I think this is more a problem of the Conbee stick. I have also  this problem for a while. Under windows everything works. but under linux, raspian or docker unfortunately not. that makes me very sad. A solution would be great

**Comment by Mimiix** [comment]
Could be various things. It can't join the network. Most of the time that's interference.

However: as the issue seems to be unrelated to docker, i suggest opening a issue [here](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/new/choose).
