### ISSUE TITLE
Reconnect previously deleted sensors doesn't work

### ISSUE THREAD

**Issue by ScumbagSteve** [marthoc/docker-deconz#352]
Reconnecting previously deleted sensors seems to be somehow buggy for me.
I use a Conbee II stick, when I search for the sensors it just doesn't find the sensors.

I noticed that when I change parameters of my zigbee network, the are instantly found when I search again.
Example for that was changing the extPanId or the zigbee channel.
I experienced it with Sensors of different brands. It's really weird and very annoying.

Any ideas what this could be?

**Comment by Mimiix** [comment]
This seems to be a issue unrelated to Docker. If it's still valid, please open one here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/new/choose
