### ISSUE TITLE
Lower resolution on deconz VNC session

### ISSUE THREAD

**Issue by MrMEScott** [marthoc/docker-deconz#353]
I'm running this package in Docker on a headless Raspberry Pi, so I've enabled the VNC session as described in the doc. I can connect to the display (I'm using Remmina on my Ubuntu laptop), but my problem is that the display resolution is too much for my poor laptop screen -- and for my eyesight! 
Is there anything I can do (perhaps via some `DECONZ_VNC_` environment setting in the docker-compose.yml file) to specify a lower display resolution?

**Comment by Jo-Be-Co** [comment]
@MrMEScott have a look this PR: #341.
So actually there is no option for you - but the issue is addressed.
