### ISSUE TITLE
Firmware - not connected

### ISSUE THREAD

**Issue by PeterGrilloF** [marthoc/docker-deconz#355]
I know this issue has been up before, but there has been no solution for me, so I'll try again.
I have a Conbee II running in Docker on a Synology DS218+
The Conbee is sitting in the /dev/ttyACM0 port with an extension-cort attached to it.

Last week, I updated the deconz to 2.09.02, and the firmware of the Conbee II to deCONZ_ConBeeII_0x26680700.bin.GCF
Since then, when logging in to the Phoscon app, the Firmware is "not connected", and I can't control any lights.

I have tried to startup a new container from scratch, but nothing is really helping.
Can anyone point me in the right direction?

Thank you in advance.

**Comment by Jo-Be-Co** [comment]
Two ideas on this:
# if the firmware-update didn't work your stick might not be seen as needed
# maybe the update of deconz does not work in /dev/ttyACM0. On other issues you can find some hints how you could make shure your device is mounted the right way. It would be something like `-device <local-long-name>:/dev/ttyACM0`.

Maybe I'll find some time to update my synology-docker-setup these days ...

**Comment by Jo-Be-Co** [comment]
Update has been done. But ...

After the first run I also got the state _"not connected"_. So I had to rerun the update. This time added some options for _timeout_ and _retries_ - in that case it worked out after the third run.
Note that I used an updated version of the script to add the options:
```
$ sudo -i docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys deconz/fw-test -x 1 -R 10 -t 60
-------------------------------------------------------------------

             marthoc/deconz Firmware Flashing Script

                       Version: 0.7

-------------------------------------------------------------------


Listing attached devices...

GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyACM0     | 0x1CF1 | 0x0030  |            | ConBee II

Enter the full device path, or press Enter now to exit.

Device path .: /dev/ttyACM0

-------------------------------------------------------------------

Firmware available for flashing:
deCONZ_ConBeeII_0x26660700.bin.GCF
deCONZ_ConBeeII_0x26680700.bin.GCF
deCONZ_RaspBeeII_0x26690700.bin.GCF
deCONZ_Rpi_0x26350500.bin.GCF
deCONZ_Rpi_0x26390500.bin.GCF

Enter the firmware file name from above, including extension.
Alternatively, you may enter the name of a firmware file to download
from http://deconz.dresden-elektronik.de/deconz-firmware/
or press Enter now to exit.

Firmware file: deCONZ_ConBeeII_0x26680700.bin.GCF

-------------------------------------------------------------------

Device path .: /dev/ttyACM0
Firmware file: deCONZ_ConBeeII_0x26680700.bin.GCF
Timeout .....: 60
Retries .....: 10
Loglevel ....: 1

Are the above values correct?
Enter Y to proceed, any other entry to exit: Y

Flashing...

GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device /dev/ttyACM0 (ConBee II)
00:43:23:320 RX 60 bytes ASCII
R21B18 Bootloader
Vers: 2.07
build: Jun 17 2019
, 08:48:53
 after 15 ms
R21B18 Bootloader
Vers: 2.07
build: Jun 17 2019
00:43:23:322 GCF_ResetDeviceDone
flashing 164373 bytes: |=============error: timeout flashing firmware after 3008 ms
Reboot device /dev/ttyACM0 (ConBee II)
00:43:33:857 device /dev/ttyACM0 not found
00:43:34:092 device /dev/ttyACM0 not found
Reboot device /dev/ttyACM0 (ConBee II)
00:43:34:495 RX 60 bytes ASCII
R21B18 Bootloader
Vers: 2.07
build: Jun 17 2019
, 08:48:53
 after 15 ms
R21B18 Bootloader
Vers: 2.07
build: Jun 17 2019
00:43:34:496 GCF_ResetDeviceDone
flashing 164373 bytes: |========error: timeout flashing firmware after 3002 ms
Reboot device /dev/ttyACM0 (ConBee II)
00:43:44:032 device /dev/ttyACM0 not found
00:43:44:260 device /dev/ttyACM0 not found
Reboot device /dev/ttyACM0 (ConBee II)
00:43:44:706 RX 60 bytes ASCII
R21B18 Bootloader
Vers: 2.07
build: Jun 17 2019
, 08:48:53
 after 15 ms
R21B18 Bootloader
Vers: 2.07
build: Jun 17 2019
00:43:44:707 GCF_ResetDeviceDone
flashing 164373 bytes: |==============================|
verify: .
SUCCESS
Wait 10 seconds until application starts
```

**Comment by ChalesGiron** [comment]
I have the same issue after having performed an update, exactly as described by 'PeterGrilloF'. I hadn't any luck with rerunning the update unfortunately. Any thoughts / suggestions?

**Comment by Mimiix** [comment]
This seems to be a issue unrelated to Docker. If it's still valid, please open one here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/new/choose

Please note that updating firmware is not recomended on VM's or Docker instalation. Please refer to this page for additional information : https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually
