### ISSUE TITLE
Phoscon 2.06.00 how to update to newer version? 

### ISSUE THREAD

**Issue by snhnic** [marthoc/docker-deconz#359]
I have Marthoc deconz installed on my synology. I finally managed to get the update firmware to 26660700. But I read about Sonic Boomerang ⋅ v2.7.1. What are all the differences versions????  On a Forum I saw 2.07.01 / 15.12.2020 with firmware 26390500.

I have 2.06.00 / 11/15/2020 with firmware 26660700. But I would like to have 2.07.01 since that one supports silvercrest motion detector. and how is this compared with 2.7.1??? I feel stupid not getting how this works

**Comment by Jo-Be-Co** [comment]
v2.9.3 just _"arrived"_ today. For an overview of the releases have a look at the [release page of the deconz-github](https://github.com/dresden-elektronik/deconz-rest-plugin).
I don't know if there are any infos about the firmware-updates. In most cases you should use the firmware coming with a new Phoscon (i.e. deconz-rest-plugin).
Maybe you could find additional infos and/or help in the [discord-user-group](https://discord.gg/APNK5TM)

**Comment by snhnic** [comment]
Oke but how do I install this with Marthoc on my synology?

**Comment by Jo-Be-Co** [comment]
As you would update any docker-image. I hope you have setup your container with a mounted volume. In that case your are safe to delete the container and install a new one (with the updated image).
As with any update you might backup this volume in advance.

You might also have a look at watchtower - if you have this (docker) running it will scan your container regularly and handle the full update. Especially with keeping all the settings.

**Comment by Mimiix** [comment]
As there hasn't been any new replies and as there are newer versions, i'm closing this issue. If this needs to be re-opened, please ping me :)

**Comment by snhnic** [comment]
> As you would update any docker-image. I hope you have setup your container with a mounted volume. In that case your are safe to delete the container and install a new one (with the updated image).
> As with any update you might backup this volume in advance.
> 
> You might also have a look at watchtower - if you have this (docker) running it will scan your container regularly and handle the full update. Especially with keeping all the settings.

Thanks for your reply, I will give it a try

**Comment by Jo-Be-Co** [comment]
Or as @phdelodder stated here:    [#346](https://github.com/marthoc/docker-deconz/issues/346#issuecomment-804271095)
`clear` should be the action to update your installation - have not tried it on my own though.
