### ISSUE TITLE
Time Incorrectly Reported - Request For Timezone TZ Environment Variable

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [marthoc/docker-deconz#36]
Hi,

The time is being incorrectly recorded in my container. I live in England, so my timezone would be Europe/London - At present, the time reported from the container is 1 hour behind which means that time sensitive logs and scenes need to be adjusted accordingly.

A standard practice for Docker containers seems to be a Timezone Environment Variable usually labelled as TZ that can then be fed in at build / load.

Can this be added?

Thanks,

Daniel

**Comment by marthoc** [comment]
It should just work if you try it - I’m pretty sure the base image I’m using supports this variable.

**Comment by danieledwardgeorgehitchcock** [comment]
Yes, this works.

Thanks!
