### ISSUE TITLE
schedules do not work

### ISSUE THREAD

**Issue by bluesailor45** [marthoc/docker-deconz#360]
Hello, 
on my QNAP NAS I have installed in the Container Station "marthoc/deconz". It is up and running. I can add Lights onto the app, am able to control the Lights, have set different scenes and actions (alarms). But unfortunately my schedules (call scene - set lights on at specific time / set light off at another specifiy time) do not work. 

I am not sure if this issue is due to the following strange messages i n the log !?

In the log of the running container I get the following infos in a continous loop:

CTRL got nwk update id 0
18:13:50:345 Device TTL 1620 s flags: 0x7
18:13:51:321 apsUseExtPanid is 0xDDDDDDDDDDDDDDDD but should be 0, start reconfiguration
18:13:51:321 Skip automatic channel change, TODO warn user
18:13:52:821 send permit join, duration: 0
18:14:01:321 apsUseExtPanid is 0xDDDDDDDDDDDDDDDD but should be 0, start reconfiguration
18:14:01:321 Skip automatic channel change, TODO warn user
18:14:11:321 apsUseExtPanid is 0xDDDDDDDDDDDDDDDD but should be 0, start reconfiguration
18:14:11:321 Skip automatic channel change, TODO warn user

How do I change apsUseExtPanid to 0 in my container ????

Thank you very much for any help.

**Comment by Mimiix** [comment]
This seems to be a issue unrelated to Docker. If it's still valid, please open one here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/new/choose
