### ISSUE TITLE
2nd conbee - cannot connect to webUI

### ISSUE THREAD

**Issue by eyalgin** [marthoc/docker-deconz#361]
Hi,
Have a strange one.
Up until now, I've had a single setup (docker) which works flawlessly.
Last week, I've added another setup, on a different physical location, docker is up and running, but when trying to log in with the pohscon web app, I'm getting a blank screen with the logo on top. when clicking the logo I'm getting:
"Please wait until the search for gateways has finished.
172.16.0.1 7 %172.16.1.1 15 %192.168.1.1 4 %"

The strange thin is that those IP addresses are of ny first setup, and for some reason these are being scanned.

Both setups are on different physical locations (different IPs of course), being accessed with a different domain (deconz.DOMAIN1, deconz.DOMAIN2) reversed proxied by traefik2.

Tried different browsers, incognito mode, reinstallation, nothing seems to change.

Appriciate any assistance with this.
TIA

**Comment by Mimiix** [comment]
This seems to be a issue unrelated to Docker. If it's still valid, please open one here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/new/choose
