### ISSUE TITLE
Enabling VNC zigbee mesh

### ISSUE THREAD

**Issue by madzur** [marthoc/docker-deconz#365]
Hello,

docker noob here, so I am trying to find an answer to an equally basic question.
I started my deconz docker container with the instructions listed here: https://github.com/marthoc/docker-deconz#command-line

I failed to realize, that if I want to access deconz over VNC, I need to add the following parameters:
https://github.com/marthoc/docker-deconz#environment-variables

Since my container is up and running with the original parameters, I am struggling to configure VNC.
If I try to run the initial command again, including the VNC-enabling parameters, I get the following error message:

> docker: Error response from daemon: Conflict. The container name "/deconz" is already in use by container "54e8625fa39ed01ca96550a4fa862738e9a1a5616efb73d554245b7c621b994d". You have to remove (or rename) that container to be able to reuse that name.
> See 'docker run --help'.

Please help?
Thank you.

**Comment by elaskar** [comment]
Hello madzur, try to stop your container and delete it then add the options to the docker command line

**Comment by madzur** [comment]
Hey Elaskar, thanks for the tip. This is a last-resort solution, which I was hoping to avoid.
I have several devices added to deConz and connected to Home Assistant, so I wanted to avoid configuring everything from scratch.
I was hoping to change a simple config file, to enable VNC, and I was not able to find such a file.
Would be grateful for any other tips that avoid a complete zigbee network reinstall and adding to HASS.

**Comment by elaskar** [comment]
https://stackoverflow.com/questions/27812548/how-to-set-an-environment-variable-in-a-running-docker-container could resolve your issue :)

**Comment by madzur** [comment]
Thanks for the tip. I actually ended up deleting the container and switched to running it through docker_compose. It's much easier to change parameters there. The Deconz readme contains instructions on setting it up this way, I just needed to read a bit further down on the page :). https://github.com/marthoc/docker-deconz#docker-compose
Thanks for your help.
