### ISSUE TITLE
deconz not working?!

### ISSUE THREAD

**Issue by jochristian** [marthoc/docker-deconz#37]
Hi,

Might not be an issue at all but not sure if my deconz setup is working.
So far I have not been able to pair any zigbee devices (aqara).
Running in docker on my ubuntu host.

When looking at gateway settings it says:

Vendor dresden elektronik
Product ConBee
Version 2.05.35 / 8/17/2018
Firmware 00000000

As you can see it says firmware 00000000.
When looking at docker logs deconz I can see this information:

This plugin does not support propagateSizeHints()
13:23:01:073 Device firmware version 0x26210500
13:23:01:089 unlocked max nodes: 200
13:23:01:376 Device protocol version: 0x0106
13:23:01:393 CTRL restore cached node 0x00212effff027c70
13:23:01:393 new node - ext: 0x00212effff027c70, nwk: 0x0000

So it does look like deconz sees the device. But does this mean that it should work.
Reason for asking is mainly the fact that the firmware says 00000000 and that I have not been able to pair any devices so far.

Thanks 

/Jo Christian

**Comment by kylegordon** [comment]
Hi,

I can't help much with your main problem, but I have also noted that my firmware says 00000000. I am also on 2.05.35 / 17/08/2018.

However... my Aqara zigbee sensors, Tradfri and Hue lights are all working as expected. 

Are you keeping your devices that are to be paired close to the USB stick? Only once they are paired can they be moved further away.

Good luck :-)
Kyle

**Comment by Kane610** [comment]
You can verify that Deconz sees your hardware by verifying that you have a network id and zigbee channel. You can see this under settings -> gateway -> advanced

ZigBee channel 25
Network id 0xc504

**Comment by jochristian** [comment]
Hi,
thanks for your fast reply's.
Seems to be fine then. I can see the network id and zigbee channel.
ZigBee channel 11
Network id 0x8156


Guess I need to test some more on the aqara sensors. Thanks again!

**Comment by Kane610** [comment]
Good to hear!

One thing that have solved hardware issues for people is to put the conbee on an extension cord moving it away from the computer. This might not be applicable to you, Conbee worked fine for me on my RPI2 but when I moved it to my server I got issues with unstable Zigbee mesh.

**Comment by jochristian** [comment]
OK,

Thanks again. I will try the "workaround" with the USB extension. 
I also got the Conbee on an neighbouring port to the Z-stick.

**Comment by Pumba2306** [comment]
I can confirm that using a usb extension cord works.
I had the conbee placed in a Intel Nuc on one side and a Aeotec Zwave on the other side.
If it was interference / noise from the Nuc og Zwave usb, i dont know.
I had until that moment tried more or less everything.

**Comment by marthoc** [comment]
@jochristian The next version of this docker image will support deCONZ's built-in "--dev" command line option through the environment variable "DECONZ_DEVICE" if you are using a Z-Wave stick it's possible that it is taking the port that deCONZ expects. Set "DECONZ_DEVICE" to the same string you are passing to the --device command and it will force deCONZ to use the specified device.
