### ISSUE TITLE
Devices lost sync after I plugged conbee2 into new port

### ISSUE THREAD

**Issue by Dweller** [marthoc/docker-deconz#372]
Very strange one I’ve had the issue half a dozen times when after around the time I reboot or reconfigure my Phoscon / deconz gateway it looses sync with existing devices.

I can see the devices in the Phoscon network app via VNC but they are unresponsive via deconz.

I’ve seen this issue reported many times with no conclusion.   Is it time to ditch deconz?

**Comment by Nicholaiii** [comment]
> Is it time to ditch deconz?

How often are you going to need to move the usb stick to another port? 🤨

**Comment by Dweller** [comment]
Ive seen the problem occur more often when I’m configuring/playing with nee hardware.    It’s rare for deconz to lose devices otherwise.     Let’s say I see a zigbee device disappear once a month.  

But when you have dozens of devices having to delete then and repair them every six months is very very time consuming.  

What’s worse is if you know it’s going to occur again and again.

which is why I’m not resetting any of my devices I’m just replacing them and I think after a year I can delete my docker-deconz container.

**Comment by Mimiix** [comment]
@Dweller It can take a while for the network to recover after a power loss.

**Comment by Dweller** [comment]
I can see all of my devices in the phoscon network display if I press light switches I can see them fire on the same display.  But the same device is not visible via the deconz API.  

The only way I have to resolving the issue is to delete them and re-pair them.

**Comment by Mimiix** [comment]
Could be all kinds of stuff. I suggest opening a git issue [Here](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/new?assignees=&labels=User+Question&template=user-question.md&title=). Make sure to add logs!

**Comment by senilio** [comment]
As already pointed out, this is not likely to be related to docker. Feel free to continue in the rest plugin repo.
