### ISSUE TITLE
Osram RGB Garden Spot not responding

### ISSUE THREAD

**Issue by netmanchris** [marthoc/docker-deconz#38]
Not sure if this is the right place to open this issue.

HassIO shows the Garden spot on the dashboard but Phoscon App is ignoring all controls ( on/off color change, brightness change) from the HassIO interface.

Vendor: OSRAM
Model:LIGHTIFY Gardenspot RGB
Version: 01020492

Confirmed that Nanoleaf Smart Ivy bulbs are acting as expected

Vendor:Nanoleaf
Model:NL08-0800
Version: 1.3.9

If this is the right place to open this issue, what data do you need from me?  No experience with debugging DeZonz or Home Assistant but more than happy to learn and do the work required.

thanks,

Chris

**Comment by Kane610** [comment]
If you are able to add devices to Deconz. Then it is not the container that is at fault. Try creating an issue with deconz github instead.

If you get a more complete failing of all lights the recommended solution is to add an extension cord for the conbee

**Comment by netmanchris** [comment]
thanks appreciate the pointer! I'll close out the issue as solved.
