### ISSUE TITLE
Docker doesn't start if power loss and vnc session active

### ISSUE THREAD

**Issue by solvisit** [marthoc/docker-deconz#380]
If there is a power loss and there is an active vnc connection the docker will not start because /tmp/.X0-lock remain in the /tmp directory.
Possible solution in start.sh

  # Cleanup previous VNC session data
  tigervncserver -kill "$DECONZ_VNC_DISPLAY"

 # HERE <-------------------------------------------------------------------
 rm -f /tmp/.X"$DECONZ_VNC_DISPLAY"-lock

  # Set VNC security
  tigervncserver -SecurityTypes VncAuth,TLSVnc "$DECONZ_VNC_DISPLAY"

**Comment by marthoc** [comment]
If you want to open a PR for this we can merge it.

**Comment by phdelodder** [comment]
I have test this with the current Improvements PR, it's removed by default now:

```
deconz    | Killing Xtigervnc process ID 25... which was already dead
deconz    | Cleaning stale pidfile '/root/.vnc/monkey47:0.pid'!
deconz    | Cleaning stale x11 lock '/tmp/.X0-lock'!
deconz    | Cleaning stale x11 lock '/tmp/.X11-unix/X0'!
```

**Comment by senilio** [comment]
As the fix is now implemented via #377, I'm closing this.

**Comment by solvisit** [comment]
It doesn't work....
the same error happened with the 2.11.05 version and comparing start.sh with the one in 2.12.03 I suppose the problem is still there.

I don't know if is important, but entering in docker console and manually launching:
tigervncserver -kill 0
or
tigervncserver -kill "0"

cause this error:

Can't exec "ssh": No such file or directory at /usr/bin/tigervncserver line 1315.
tigervncserver: Command 'ssh 0 tigervncserver '-kill'' failed: -1

the right syntax is:
tigervncserver -kill :0

Maybe it can help

Thank you

**Comment by solvisit** [comment]
But if I add the semicolon to the command docker restart continuosly
