### ISSUE TITLE
Not working with Raspbee 1 and fresh Ubuntu Server 20.04 on Raspberry Pi 4

### ISSUE THREAD

**Issue by mmichalko** [marthoc/docker-deconz#388]
Hi guys,

I am stuck for second day trying to set this up. When I start the container using the docker-compose configuration provided here in Readme (with device updated to ttyAMA0), I get logs:
```
16:45:43:967 wait reconnect 15 seconds
16:45:44:391 dev /dev/ttyAMA0
16:45:44:718 failed to reconnect to network try=1
16:45:44:967 wait reconnect 14 seconds
16:45:45:968 wait reconnect 13 seconds
16:45:46:968 wait reconnect 12 seconds
16:45:47:967 wait reconnect 11 seconds
16:45:48:967 wait reconnect 10 seconds
16:45:49:967 failed to reconnect to network try=2
16:45:49:968 wait reconnect 9 seconds
16:45:50:968 wait reconnect 8 seconds
16:45:51:968 wait reconnect 7 seconds
16:45:52:967 wait reconnect 6 seconds
16:45:53:967 wait reconnect 5 seconds
16:45:54:394 dev /dev/ttyAMA0
```

I had a working setup on Ubuntu Server 19.10, but since it has no support anymore I did a backup and fresh install of 20.04.

I have edited boot config:
`enable_uart=1`
`dtoverlay=pi3-miniuart-bt`

and removed `console=serial0,115200` from cmdline.txt

I also disabled 
`sudo systemctl mask serial-getty@ttyAMA0.service` and 
`sudo systemctl mask serial-getty@ttyS0.service`

I can see ` /dev/ttyAMA0` device.
I did Prerequisite setup - installed wiringpi and added my user and root user to dialout group.

Any suggestions or someone who has working setup with Ubuntu 20.04 would be appreciated.

**Comment by senilio** [comment]
Can you try add in a line to your docker-compose.yml?
```
privileged: true
```

I suspect that Apparmor is blocking access to the device.

**Comment by mmichalko** [comment]
Thanks for your answer, I didn't see it and gave up next day. Reinstalled back old Ubuntu, where it worked and in a hacky way managed to upgrade End-Of-Live 19.10 to 20.04. It works now.
