### ISSUE TITLE
After updating to 2.11.05 Phoscon GUI stopped working

### ISSUE THREAD

**Issue by pingelhoek** [marthoc/docker-deconz#400]
I’m running Deconz in a docker and this morning I updated Deconz with docker-compose to version 2.11.05. After the connection to Deconz is lost and de webgui looks like this:
![deconz](https://user-images.githubusercontent.com/63228678/118967434-01563c00-b96b-11eb-80b7-1dc72c4607fb.png)

Also the my lights/sensors in Deconz are unavailable in Homeassistant.  

How do I fix this?

**Comment by phdelodder** [comment]
6080 is the port for novnc, so make sure you go the correct URL of novnc: http://192.168.2.9:6080/vnc.html

**Comment by JamesB009** [comment]
I have the exact same issue, I lost the Phoscon GUI en Home Assistant does not see any deconz sensor / button.

**Comment by phdelodder** [comment]
Is there anything in the log?

**Comment by pingelhoek** [comment]
[_deconz_logs.txt](https://github.com/marthoc/docker-deconz/files/6515558/_deconz_logs.txt)

Not that i can see

**Comment by Mimiix** [comment]
@pingelhoek That log is really empty. Doesn't show a thing. 

To enable logging, open deCONZ and click Help. After that, click Debug View. The following debug levels need to be enabled for proper logging: INFO, ERROR,ERROR_L2,APS,APS_L2.

Be sure to capture at least a few minutes worth of logs. When sharing these logs, DO NOT attempt to paste them into a channel. Instead use a pastebin service such as this or this.

When done, don't forget to disable logging. This is especually important when running off an SD card, as it will cause unnessecary writes, and might shorten the life of the media.

@JamesB009 That's a different issue probably.

**Comment by JamesB009** [comment]
@Mimiix What I can see from @pingelhoek it is the exact same issue..

**Comment by Mimiix** [comment]
@JamesB009 Pingelhoek has Zigbee communication according to his log. You said you don't.

**Comment by JamesB009** [comment]
> @JamesB009 Pingelhoek has Zigbee communication according to his log. You said you don't.

My HA does not have connection, I can access it the same as Pingelhoek.

**Comment by phdelodder** [comment]
Please provide more details:
- full log file
- docker compose/run command

**Comment by Mimiix** [comment]
@pingelhoek nothin in that log. Can you check the HTTP box

**Comment by pingelhoek** [comment]
Log with the http box:
https://pastebin.com/LHWs6jTH

And the link to docker-compose run command:
https://pastebin.com/B0Rd2ZCv

**Comment by pingelhoek** [comment]
and also the docker-compose:

  # Deconz
  deconz:
    container_name: deconz
    image: marthoc/deconz:stable
    restart: unless-stopped
    network_mode: host
    environment:
      DECONZ_WEB_PORT: 6080
      DECONZ_WS_PORT: 6088
      DECONZ_VNC_MODE: 1
      DECONZ_VNC_PORT: 5910
      DECONZ_VNC_PASSWORD: "${VNC_PASSWORD}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/maindisk/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    ports: 
      - "5900:5910"

**Comment by phdelodder** [comment]
If you try novnc what do you get? Blank screen?

**Comment by pingelhoek** [comment]
![VNC](https://user-images.githubusercontent.com/63228678/118978983-459c0900-b978-11eb-9255-aa4984fdae29.PNG)

**Comment by Jo-Be-Co** [comment]
Looks like `NOVNC` is taking over the port you used for the web-gui ...
So either
1. disable NOVNC with `DECONZ_NOVNC_PORT=0`
2. use another port for DECONZ_WEB_PORT
3. use another port for DECONZ_NOVNC_PORT

**Comment by JamesB009** [comment]
Seems to be working for me as well, thanks all for the help and @Jo-Be-Co for the solution.

Isn't it weird that the novnc port by default is using a port which is configured?

**Comment by Jo-Be-Co** [comment]
And I wondered how you could use 6080 as port while pingelhoek has this one in use 😄
