### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by Garth6168** [marthoc/docker-deconz#404]
Trying to install on Unraid docker. Installs and starts ok. I am unable to access the web UI. I know Unraid uses port 80. Do I need to change this in deconz? I did try adding -e DECONZ_WEB_PORT=88 to the command line at install but that did not work. If I do need to change web port i do not know how to access the docker-compose.yml file. New to this setup, currently using HA and Deconz on a RPI 4.

**Comment by senilio** [comment]
You are correct trying to change the port for deCONZ, as it will not be able to bind to a port which is already in use by your host.

That said, I don't think this is the best place to ask for help with how to use docker. There are lots of resources on the internet that will explain that much better than I can.
