### ISSUE TITLE
2.12.02 - issue with key mapping

### ISSUE THREAD

**Issue by rayaar** [marthoc/docker-deconz#409]
Hi, After upgrading to 2.12.02 my xiaomi switches stopped working and I got an error on "no button map" for the switches. After some troubleshooting, I verified that the /usr/share/deCONZ/devices/button_maps.json file was there, and contained the correct mapping. I am not really sure what could cause this, but a downgrade to 2.12.01 it started working again. Not 100% sure if the error is in the Docker image or in the deconz application, but I figured Id start here in case other people experience the same.

**Comment by rayaar** [comment]
My docker compose file for reference 
`version: "2"
services:
  deconz:
    image: marthoc/deconz:2.12.01
    container_name: deconz
    network_mode: host
    volumes:
      - /home/$username/docker/deconz/config:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=3080
      - DECONZ_WS_PORT=3443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0i
      - TZ=Europe/Oslo
    restart: unless-stopped

`

**Comment by phdelodder** [comment]
I think this is related to the new version and not docker.

**Comment by phdelodder** [comment]
Perhapse this can help: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5117
