### ISSUE TITLE
Backup?

### ISSUE THREAD

**Issue by wuast94** [marthoc/docker-deconz#41]
When i start the container and map the folder: - ./deconz:/root/.local/share/dresden-elektronik/deCON
why the container don´t create any files ? so when i recreate the container my config is lost. 

i can backup manually yes but 1. it don´t work when i change my port and 2. i don´t want to create a new backup every time i change settings

**Comment by Kane610** [comment]
I recommend that you do absolute paths. It is possible that the resolution of . in your path might change.

/home/kane610/.local/share/dresden-elektronik/deCONZ:/root/.local/share/dresden-elektronik/deCONZ

**Comment by wuast94** [comment]
i have .. /mnt/user/appdata/deconz/:/root/.local/share/dresden-elektronik/deCON

**Comment by Kane610** [comment]
You're lacking a Z at the end

**Comment by marthoc** [comment]
@Kane610 is right, it seems you are missing a "Z" so you're mapping the wrong folder from the container to your host. Closing this.
