### ISSUE TITLE
Start container api-fehler-deconz failed: {"message":"error gathering device information while adding custom device \"/dev/ttyACM0\": no such file or directory"}.

### ISSUE THREAD

**Issue by tonibert** [marthoc/docker-deconz#412]
After updating to  Synology Dsm 7, I get the error when starting the Deconz container. 
I have already downloaded the latest version
What can i do?

**Comment by Mimiix** [comment]
If you've read the changelog of dsm you would've known:

USB devices (Wi-Fi dongle, Bluetooth dongle, 3G/4G dongle, USB DAC/speaker, and DTV dongle) are no longer supported. If your Synology NAS is currently connected via a wireless dongle, it will be disconnected after the update.

**Comment by tonibert** [comment]
I ‚ ve overlooked.
Thank you
