### ISSUE TITLE
Release 2.12.04 unable to open connection to USB device

### ISSUE THREAD

**Issue by petegallagher** [marthoc/docker-deconz#414]
After updating to 2.12.04 from Docker Hub deconz is unable to connect to the serial device and repeats the following error message continuously:

```
16:19:43:091 master open com error: /dev/ttyACM0
16:19:44:050 dev can't create file: /dev/ttyACM0 via mknod (missing permissions)
16:19:44:068 dev can't create file: /dev/ttyACM0 via mknod (missing permissions)
```

After reverting to the previous stable release (2.11.05) everything continues to work as normal.

**Comment by senilio** [comment]
This is a confirmed bug introduced in 2.12.4, and will be tracked in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5197
