### ISSUE TITLE
Asking for login password after initial installation

### ISSUE THREAD

**Issue by simonszu** [marthoc/docker-deconz#415]
I have a fresh install of the deconz docker container with a conbee II stick. After starting the container i have some slight issues:

1. The stick is not shown as a stick in the first web landingpage. Instead, a device is shown which looks like a cased Raspberry Pi.
2. After selecting this device, a login password is asked for. I did not specify a login password, and the password "delight" which seemed to be the default password for older versions of deconz is not working. 
3. A password reset is not working either. It is shown that one needs to wait max 10 minutes after boot up, but even if i try to do it quicker, it says failed and that i need to recently power cycle the controller. 

How will i be able to login to deconz and how will it be able to show the stick as the right device?

**Comment by senilio** [comment]
Pretty sure this is related to https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5197 ... pls try again once the new version is released.
Either way this it has nothing to do with the docker image, so I'm closing this issue.

**Comment by simonszu** [comment]
Not sure. I tried to downgrade the container like the initial post of the linked issue suggests. No success. I tried to explicitly specify the device in the container's ENV like the workaround posts in the linked issue suggests. No success. 

I have to add that i do not use the conbee II on a raspi, but an intel NUC, so there is no possibility for deconz to select the raspi itself as the wrong device. But you are right, this is a problem with deconz itself, i will ask there.

**Comment by Mimiix** [comment]
@simonszu are you using an extension cable?

**Comment by simonszu** [comment]
I tried with and without. I doubted that it would make a difference since an extension cable doesnt alter the bitstream between the host and the stick, and i was right.

**Comment by simonszu** [comment]
OK, next discovery: It has something to do with the traefik instance i am using to reverse proxy the traffic to my docker containers to. Accessing the deconz webUI directly is working very fine.
