### ISSUE TITLE
Firmware update cannot find stable or beta .cfg files

### ISSUE THREAD

**Issue by tt2g89** [marthoc/docker-deconz#419]
Hi,
I've updated to 2.12.02 a few weeks ago and to 2.12.06 a few minutes ago.
I'm using Raspbee II on Raspberry Pi 3.
Unfortunately it isn't possible to select another firmware version than those provided in the list.
Below you'll find the last try with marthoc/deconz:latest (2.12.06):

> root@loxberry:/opt/loxberry# docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz:latest
>
>-------------------------------------------------------------------
>
>             marthoc/deconz Firmware Flashing Script
>
>                       Version: 0.8
>
>-------------------------------------------------------------------
>
>
>Listing attached devices...
>
>GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
>Path             | Vendor | Product | Serial     | Type
>-----------------+--------+---------+------------+-------
>/dev/ttyS0       | 0x0000 | 0x0000  |            | RaspBee
>/dev/ttyUSB0     | 0x0403 | 0x6015  |            | ConBee
>
>Enter the full device path, or press Enter now to exit.
>
>Device path .: /dev/ttyS0
>
>-------------------------------------------------------------------
>
>Firmware available for flashing:
>deCONZ_ConBeeII_0x26660700.bin.GCF
>deCONZ_ConBeeII_0x26680700.bin.GCF
>deCONZ_RaspBeeII_0x26690700.bin.GCF
>deCONZ_Rpi_0x26350500.bin.GCF
>deCONZ_Rpi_0x26390500.bin.GCF
>
>Enter the firmware file name from above, including extension.
>Alternatively, you may enter the name of a firmware file to download
>from any of the following sources:
> - http://deconz.dresden-elektronik.de/deconz-firmware/         (stable)
> - http://deconz.dresden-elektronik.de/deconz-firmware/beta/    (beta)
>
>If you wish to exit, just hit Enter.
>
>Firmware file: deCONZ_RaspBeeII_0x26720700.bin.GCF
>
>
>Can't find 'deCONZ_RaspBeeII_0x26720700.bin.GCF' neither locally nor online. Exiting ...

**Comment by phdelodder** [comment]
@Jo-Be-Co could you please have a look at this?

**Comment by dicer** [comment]
You might have a network issue inside the container. One workaround I just tried is to create a folder on your host somewhere and put/download the GCF file there. Then mount that folder into the container with `-v /x/y/z/firmware:/usr/share/deCONZ/firmware/`

**Comment by tt2g89** [comment]
@dicer This workaround is working fine, many thanks!

So this must be some networking issue, as you said. But it is very strange, because on previous versions it was possible to download the GCF file and I didn't touch the container settings since then.
