### ISSUE TITLE
Password correct but not working in Phoscon app

### ISSUE THREAD

**Issue by chrisadas** [marthoc/docker-deconz#420]
Password had not been changed, but is not accepted by Phoscon app.

Password reset does not work and complained that it can only be done within 10 minutes of gateway power up. I have tried both re-starting the container and restarting the docker host. None of those work.

I tried connecting with Hue Essential app on Android. Using user: delight and my password, it is able to connect.

This seem to point to the password being correct, but somehow is rejected. The failed login does not show in the log that I can see in portainer. If there is other log I can provide, please let me know how.

**Comment by phdelodder** [comment]
This seems more of an issue for https://github.com/dresden-elektronik/deconz-rest-plugin

**Comment by chrisadas** [comment]
> This seems more of an issue for https://github.com/dresden-elektronik/deconz-rest-plugin

Thank you. I did not know about that. Their issues lead me to their forum. I have asked the question there and hope to get help on it.

Cheers
