### ISSUE TITLE
vnc access send raspberry 3 to it's heat death

### ISSUE THREAD

**Issue by checkup21** [marthoc/docker-deconz#422]
I'm using the latest stable image (as of now / 20210830).

When starting with VNC access, a raspberry 3 gets really hot and locks itself up after about 6h. Power supply is 2.5A. If vnc access is disabled, the system runs w/o problems.

**Comment by senilio** [comment]
🤔 

Do you see any VNC related processes running high on CPU?
What temps do you get without running VNC?

**Comment by checkup21** [comment]
I'm gonna check that the coming weekend.

**Comment by senilio** [comment]
We need proof that the VNC process burning your RPi3 CPU. Until then my only advice is to review your Pi airflow / cooling 🤷‍♂️

**Comment by checkup21** [comment]
Could not reproduce again. container is running since days incl. VNC and several client connections have been made since. CPU-usage is low (<5%).
The only difference i can think of, was that i was also using windows vncClients, which i haven't the last days. If i encounter the problem again and have proof what leads to the problem i will comment again.
