### ISSUE TITLE
Check for firmware update during start

### ISSUE THREAD

**Issue by akafester** [marthoc/docker-deconz#423]
Could it be possible to have a script running at the very start at starting the container up, checking for firmware, and pick the latest? A config file in the data folder could be used to select stable/beta if wanted.

**Comment by senilio** [comment]
What do you want the script to do with the firmware file, given that it downloads a newer one that is currently flashed?

**Comment by akafester** [comment]
I'm thinking something along the lines that could be decided with a variable. 

0 - Download if newer firmware is found and update on next start.
1 - Download but don't do anything with the file.
2 - Check if file is downloaded and update. Shut the container down afterwards (or if possible revert variable back to 1).

I'm not certain that above would be possible, but it sure would be a nice feature.

**Comment by Mimiix** [comment]
I think this causes more issues than it solves them tbh.

**Comment by akafester** [comment]
I mean, anything would be better than the current state with updating a firmware in Docker. 
The default state, if nothing else is set, would be 1, meaning it would behave much like today.

**Comment by Mimiix** [comment]
You mean in the form of a __opt-in__ . That would be okay, but it could cause issues. Docker on a VM for example would probably either brick the stick or doesn't work at all. Users that are not that familiar with docker/vm etc would break their own stuff. 

Either way, i'm not to decide here 😅

**Comment by senilio** [comment]
We have working update instructions here: https://github.com/marthoc/docker-deconz#updating-conbeeraspbee-firmware

Trying to implement some kind of auto flash feature is definitely out of scope for this project, and will just add complexity for very little gain.

**Comment by akafester** [comment]
> We have working update instructions here: https://github.com/marthoc/docker-deconz#updating-conbeeraspbee-firmware
> 
> Trying to implement some kind of auto flash feature is definitely out of scope for this project, and will just add complexity for very little gain.

That's a shame. I'm hoping that a more user friendly approach can be developed down the line.

**Comment by Jo-Be-Co** [comment]
The app is already checking if the firmware is up to date. But I don't know where it seeks for the newest version ...

So users could be informed by reading the log or looking at the web-page of their running instance.

I wouldn't recommend auto-updates as this process doesn't run flawless from inside the docker container. So just image powerloss, reboot, autoupdate and the result of an unusable stick!

On the other hand - if you know about an update which may be auto downloaded and you manually start the update process why shouldn't the firmware download happen now. Early download doesn't help that much and it would have to dl every new version for every type of device ...

**Comment by akafester** [comment]
Phoscon is already searching and knows when it's time to update. It's just that the container isn't handling that at all. 
This causes issues for those running Docker in a non standard environment, like HASS and Synology Docker.

I mean:
>Update in Docker
>
>If you are using marthoc's deCONZ Docker image the steps in this guide won't work.
>Please refer to the following guide, which describes how to update the firmware inside Docker.
>
>https://github.com/marthoc/docker-deconz#updating-conbeeraspbee-firmware
>
>This method cannot be used for the Home-Assistant add-on and no current workaround is known. This also includes the button >in Phoscon within the addon.

Can this really not get automated enough to fix the above? I refuse to believe that this is wanted behavior. 
The GCFFlasher is going to throw an error and not update if something is wrong anyhow, so why not take advantage of that?
