### ISSUE TITLE
dbg-error seems to be missing 

### ISSUE THREAD

**Issue by Mimiix** [marthoc/docker-deconz#424]
Hi,

It seems that the error passtrough (error and error_l2) is missing from the variable list:https://github.com/marthoc/docker-deconz#environment-variables

Deconz does have this:https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/deCONZ-debug-flags

Is this on purpose or just lacking in feature? Perhaps it would be usefull to also add the others.

**Comment by phdelodder** [comment]
It's just missing, I'll add them
