### ISSUE TITLE
Upgrade to 2_05_40 

### ISSUE THREAD

**Issue by eiaro** [marthoc/docker-deconz#46]
Upgrade to 2_05_40

[https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_40](url)

**Comment by tubalainen** [comment]
Cant wait, thank you for all your hard work @marthoc ! <3

**Comment by flavio20002** [comment]
2_05_41 :-)

**Comment by alexvandervegt** [comment]
Any updates? Waiting for version bump aswell

**Comment by o0shojo0o** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_42  ;)
