### ISSUE TITLE
After upgrading to 2.05.42 firmware update fails

### ISSUE THREAD

**Issue by ted1979** [marthoc/docker-deconz#49]
Hi,

I just upgraded deCONZ to 2.05.42 and now the firmware upgrade fails with the following message:

Enter C for Conbee, R for RaspBee, or press Enter now to exit: C

Listing attached devices...

rmmod: ERROR: Module ftdi_sio is in use
rmmod: ERROR: Module usbserial is in use by: ftdi_sio
GCFFlasher V2_11 (c) dresden elektronik ingenieurtechnik gmbh 2017/12/10
RaspBee: /dev/ttyAMA0 (default)

       1  FTDI device found

 device | vendor | product | serial  | description
--------|--------|---------|---------|----------------------
failed to open FTDI device (0) status = 3

**Comment by EvtK** [comment]
Hi there, 

I have exactly the same issue. I see this issue is instantly closed. Can the solution be shared?

Thanks!

**Comment by marthoc** [comment]
You need to close or unload any other programs that are using the USB bus - maybe a usb stick for ZWave - so that the flashing program can unload the relevant device drivers, which cannot be unloaded while the bus is in use.

**Comment by EvtK** [comment]
Thanks for your quick response. I'm running HomeAssistant with z-wave dongle indeed. I had already unplugged it and stopped HA.. turned out I had another process running. Firmware in progress now. Thanks again.
