### ISSUE TITLE
--net=host

### ISSUE THREAD

**Issue by anton-johansson** [marthoc/docker-deconz#5]
> --net=host: Uses host networking mode for proper uPNP functionality; by default, the web UIs and REST API listen on port 80 and the websockets service listens on port 443. If these ports conflict with other services on your host, you can change them through the environment variables DECONZ_WEB_PORT and DECONZ_WS_PORT described below.

I assume it won't work well without the `--net=host`, due to the uPNP you mention? I'd love to hide the deCONZ instance within Docker, and just link my Home Assistant container to the deCONZ container. I wouldn't have to worry about port collisions on my server. But if it won't work, then there's nothing to do about it. :)

I'm waiting for my ConBee stick to arrive, so I haven't been able to test yet.

**Comment by marthoc** [comment]
The only issue I’m thinking of this if deCONZ is only exposed to Home Assistant (I assume you’re thinking of the Sure, you should be able to do this by linking

**Comment by marthoc** [comment]
And since you can arbitrarily change the ports required with the environment variables, you shouldn’t have a collision problem - there’s more than 65000 to choose from. :)

**Comment by anton-johansson** [comment]
Hehe, of course, but I prefer using the standard ports for stuff, with isoltion. But we'll see, I'll mess around when I get my ConBee stick!

**Comment by oscar-b** [comment]
@anton-johansson did you get it running on an isolated network? Trying to run it behind Traefik, but it seems it is discovering the gateway with the non-accessible internal ip.

**Comment by oscar-b** [comment]
Hey @anton-johansson, did you figure out a solution for this? Just opened this related issue with problem with discovery 
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/702

**Comment by anton-johansson** [comment]
I forgot to check back in here... But it's working fine for me without `--net=host`. :)

[Home Assistant package](https://github.com/anton-johansson/home/blob/master/home-assistant/packages/lights.yaml)
[Docker compose](https://github.com/anton-johansson/home/blob/master/docker-compose.yaml#L15)
