### ISSUE TITLE
Specify whether DeCONZ is beta or not

### ISSUE THREAD

**Issue by RudolfRendier** [marthoc/docker-deconz#50]
Would it be possible to make it clear to addon-users that the DeCONZ-version is beta, as is shown here:
https://github.com/dresden-elektronik/deconz-rest-plugin/releases

Unsure if the addon-version is free format, maybe something like this:

deCONZ 2.05.42 (beta) is available
You are currently running version 2.05.39 

Or a small note in the changelog:

Changed
    Bump deCONZ to 2.05.42 (beta).

I appreciate the fact that you update this awesome addon for betas, but running beta software for my lights/sensors is not (always) what I want, but having a choice is good. 👍

**Comment by marthoc** [comment]
Well the only problem is that deCONZ is essentially beta software, I’m not even sure of the last “stable” release, but for a long time it was 2.04.35, which quickly became horribly out of date and beta releases were being made very frequently.

As with any software, my advice is not to update if everything is working for you, and only to update if there’s a bug fix that applies to your situation or if there’s new device support you can’t live without.

**Comment by marthoc** [comment]
And generally speaking, people start clamouring for a new version of this image the second a new version is released, beta or not. The only suggestion I could make is to have a separate “beta” tag and have the latest tag track only the latest stable release. But this would be a breaking change anyway. 

For the Hassio addon, I would need to create two addons - one for stable, one for beta. 

Or as I said, you could follow the releases and only update your addon once the point release is to a “stable” one.
