### ISSUE TITLE
hassio - conbee not recognized?

### ISSUE THREAD

**Issue by Mariusthvdb** [marthoc/docker-deconz#53]
HI,

setting up a new usb Conbee device, it won't get recognized. Hardware shows /dev/ttyAMA0 to be available but I am not sure the Conbee is powered? Shouldn't there be a led or so on the stick.

Anyways, I have the add-on installed and get to the 8080 page but nothing is found, and integration/deconz aborts.

these are my settings:

```
{
  "deconz_device": "/dev/ttyAMA0",
  "web_port": 8080,
  "websockets_port": 8443,
  "debug_info": 1,
  "debug_aps": 0,
  "debug_zcl": 0,
  "debug_zdp": 0,
  "debug_otau": 0
}
```
ad this is diplayed in the add-on log:

```
[Hass.io] Starting deCONZ Hass.io Addon...
[Hass.io] Current deCONZ version: 2.05.44
[Hass.io] Web UI port: 8080
[Hass.io] Websockets port: 8443
[Hass.io] deCONZ device: /dev/ttyAMA0
libpng warning: iCCP: known incorrect sRGB profile
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
```

btw when i go to the phoscon page I need to manually edit the link, because that uses the domain on duckdns directly, while I have 2 hassio instances on that domain and use individual ports for each system. Using `hassio.local:8080 `does work.

Also, in that login page, I can see in the top right corner it scans 192.168.1.1, which isn't the hassio.local ip, but my main router ip address. Is that correct?

![schermafbeelding 2018-11-07 om 09 40 13](https://user-images.githubusercontent.com/33354141/48120017-2a14fb00-e271-11e8-98bc-4861e7c2d957.jpg)

What can I do?
Ive set debug mode for deconz, but nothing is logged...(yet)

thx,
Marius

**Comment by marthoc** [comment]
The Conbee will very likely be /dev/ttyUSB0 (ttyAMA0 is for RaspBee).

**Comment by Mariusthvdb** [comment]
yes thank you, Ive tried usb to, but the thing is, if I check hardware in the hassio system, no usb is listed? 

![schermafbeelding 2018-11-07 om 16 47 41](https://user-images.githubusercontent.com/33354141/48142311-de804280-e2ac-11e8-91d1-54573b1108bf.jpg)

and about the scan: should it list the trusted networks / router address, or should it scan the Rpi's address.
Its all a bit confusing, especially since the Conbee doesn't show anything, no sing of live> Im not even sure the Usb ports are live..?

**Comment by marthoc** [comment]
I think your problem is that ttyUSB0 is not recognized by HassOS - and I’m not sure how to help with that... it should show up under hardware.

**Comment by Mariusthvdb** [comment]
well yes, that might it.. rather a fundamental issue....
hoping to get some answers soon though, thanks for helping
