### ISSUE TITLE
Using ConBee with a custom /dev path

### ISSUE THREAD

**Issue by hassrasp** [marthoc/docker-deconz#54]
Hi,
I use a ConBee dongle with a Raspberry Pi and have a problem using more than one USB device. After a reboot the ConBee dongle is not always reachable at /dev/ttyUSB0 but e.g. at /dev/ttyUSB1. So I tried to use it with a custom path like /dev/ConBee. After setting up /dev/ConBee with udev, I tried to run the following commands, unfortunately without success:

~$ sudo docker rm --force /deconz marthoc/deconz
~$ sudo docker run -d --name=deconz --net=host --restart=always -v /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ --device=/dev/ConBee marthoc/deconz

So is the image only supposed to work with /dev/USB0 or is there also the possibility to select a custom /dev path?

Thanks,
Ben

**Comment by Kane610** [comment]
See discussion here https://github.com/marthoc/docker-deconz/issues/29

**Comment by Kane610** [comment]
Lets mark this as resolved then. 👍
