### ISSUE TITLE
HTTPS behind reverse proxy

### ISSUE THREAD

**Issue by anton-johansson** [marthoc/docker-deconz#63]
This is probably very related to:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/659

I'm just wondering if anyone has been able to run the latest version behind a reverse proxy (NGINX or Traefik for example) and using HTTPS?

Same goes for enabling proper WS (WebSockets) behind a reverse proxy. I can't seem to get it to work  (maybe this should be a separate issue). The `DECONZ_WS_PORT` environment variable seems to control which port the web app tries to connect to over the WS protocol. However, which port should it be routed to in the actual application in the container?

**Comment by oscar-b** [comment]
There's some more info here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/702

With the latest changes there, it's working, but without wss. Haven't had time to investigate on how to set it up any further, but it might need more changes to `deconz-rest-plugin` (`ws://` vs `wss://`).

**Comment by anton-johansson** [comment]
Nice! Thanks, I'll try those temporary fixes as well, and I've subscribed to that issue and will report back here.

**Comment by anton-johansson** [comment]
Awesome @manup, thanks for the heads up!

**Comment by DisasteR** [comment]
@anton-johansson can you share your compose with traefik label to have it working ?

**Comment by anton-johansson** [comment]
@DisasteR, oooh, that was a long time ago. I've moved on from Docker and Traefik. Sorry. :(

**Comment by pavel-pi** [comment]
@oscar-b hey! is deconz still working for you behind a reverse proxy? i have some issues because it always wants to reach out for the APIs IP address instead of the URL.

**Comment by oscar-b** [comment]
> @oscar-b hey! is deconz still working for you behind a reverse proxy? i have some issues because it always wants to reach out for the APIs IP address instead of the URL.

Sorry, haven't been using deCONZ in a while, so I don't know about the current state.
