### ISSUE TITLE
Can't discover devices | Edit: Front USB working, back USB not!

### ISSUE THREAD

**Issue by DaJansenGit** [marthoc/docker-deconz#65]
##### Problem:
I'm not able to discover any devices with the deconz stick inside the docker. 
##### Setup: 
- Debian server with current docker version installed
- conbee stick from Dresden electronic
- upgraded firmware of stick on windows pc (because didn't work on linux)
- deconz stick is discovered correctly in Phoscop web app (see image)
![image](https://user-images.githubusercontent.com/27726960/49327299-23bc2b00-f560-11e8-907c-cbe2d0dd16fc.png)

##### command used to start docker:
docker run -d --name=deconz --net=host --restart=always -v /etc/localtime:/etc/localtime:ro -v /docker/deconz:/root/.local/share/dresden-elektronik/deCONZ --device=/dev/ttyUSB0 -e DECONZ_WEB_PORT=8084 marthoc/

### Edit:
Ok everything is working fine if I use the front usb ports of my server, with each of the 4 ports in the back it's not working like descibred above. Any idea what the problem is? The stick is discovered correctly even at the back ports at /dev/ttyUSB0 and also in the phoscon web ui...

##### Log information:
> [marthoc/deconz] Starting deCONZ...
[marthoc/deconz] Current deCONZ version: 2.05.47
[marthoc/deconz] Web UI port: 8084
[marthoc/deconz] Websockets port: 443
libpng warning: iCCP: known incorrect sRGB profile
11:45:05:824 HTTP Server listen on address 0.0.0.0, port: 8084, root: /usr/share/deCONZ/webapp/
11:45:05:829 CTRL. 3.16.211:45:05:876 ZCLDB init file /root/.local/share/dresden-elektronik/deCONZ/zcldb.txt
11:45:05:977 parent process /bin/sh
11:45:05:977 gw run mode: normal
11:45:05:981 DB sqlite version 3.16.2
11:45:05:982 DB PRAGMA page_count: 0
11:45:05:982 DB PRAGMA page_size: 4096
11:45:05:982 DB PRAGMA freelist_count: 0
11:45:05:982 DB file size 0 bytes, free pages 0
11:45:05:982 DB PRAGMA user_version: 0
11:45:05:982 DB upgrade to user_version 1
11:45:06:043 DB write sqlite user_version 1
11:45:06:046 DB PRAGMA user_version: 1
11:45:06:046 DB upgrade to user_version 2
11:45:06:052 DB write sqlite user_version 2
11:45:06:056 DB PRAGMA user_version: 2
11:45:06:056 DB upgrade to user_version 6
11:45:06:065 DB write sqlite user_version 6
11:45:06:076 DB PRAGMA user_version: 6
11:45:06:076 DB cleanup
11:45:06:076 DB create temporary views
11:45:06:077 don't close database yet, keep open for 900 seconds
11:45:06:078 don't close database yet, keep open for 900 seconds
11:45:06:079 started websocket server at port 443
11:45:06:080 create default username and password
11:45:06:083 discovery updated announce interval to 10 minutes
11:45:06:084 GW firmware update not supported on x86 linux headless
11:45:06:086 found node plugin: libde_rest_plugin.so - REST API Plugin
11:45:06:088 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
11:45:06:114 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
11:45:06:216 Device firmware version 0x261F0500
11:45:06:232 unlocked max nodes: 200
11:45:06:520 Device protocol version: 0x0106
11:45:06:537 new node - ext: 0x00212effff02a48a, nwk: 0x0000
11:45:06:712 Current channel 11
11:45:06:776 CTRL ANT_CTRL 0x02
11:45:06:888 Device protocol version: 0x0106
11:45:07:080 Current channel 11
11:45:07:144 CTRL ANT_CTRL 0x02
11:45:07:433 DB save zll database items 0x00000888
11:45:07:445 DB saved in 12 ms
11:45:07:447 don't close database yet, keep open for 900 seconds
11:45:07:965 don't close database yet, keep open for 900 seconds
11:45:08:126 don't close database yet, keep open for 900 seconds
11:45:08:229 ZDP discovery done in 268 ms11:45:11:715 Announced to internet
11:45:18:515 CTRL db store gui node 00:21:2e:ff:ff:02:a4:8a
11:45:18:520 saved node state in 0 ms
11:45:19:798 sync() in 1277 ms
11:45:21:513 DB save zll database items 0x00000008
11:45:21:525 DB saved in 12 ms
11:45:21:525 don't close database yet, keep open for 900 seconds
11:45:21:972 created username: 314636F616, devicetype: Phoscon#B1920x938
11:45:26:013 Set bridgeid to 00212EFFFF02A48A
11:45:26:722 DB save zll database items 0x0000000C
11:45:26:734 DB saved in 11 ms
11:45:26:734 don't close database yet, keep open for 900 seconds
11:45:31:076 Updated password hash: $1$8282jdkm$COVKzHivErU9KDVc8E8uY.
11:45:31:096 created username: 700133C00D, devicetype: Phoscon#B1920x938
11:45:32:313 New websocket 192.168.178.34:55180 (state: 3)
11:45:36:318 DB save zll database items 0x0000000C
11:45:36:328 DB saved in 10 ms
11:45:36:328 don't close database yet, keep open for 900 seconds
11:45:38:013 send permit join, duration: 59
11:45:38:827 Websocket disconnected 192.168.178.34:55180 (state: 0)
11:45:47:260 found gateway 192.168.178.42:80
11:45:56:765 Invalid admin password hash: $1$8282jdkm$w.o6XjJEGLzAYkVqLPAYx1
11:45:57:517 scan finished
11:46:00:172 reuse recently created auth username: 700133C00D, devicetype: Phoscon#B1920x938
11:46:00:172 apikey username: 700133C00D, devicetype: Phoscon#B1920x938 already exists
11:46:01:404 New websocket 192.168.178.34:55295 (state: 3)
11:46:02:571 Websocket disconnected 192.168.178.34:55295 (state: 0)
11:46:03:698 New websocket 192.168.178.34:55313 (state: 3)
11:46:05:574 Current channel 11
11:46:07:119 Websocket disconnected 192.168.178.34:55313 (state: 0)
11:46:08:192 New websocket 192.168.178.34:55327 (state: 3)
11:46:11:160 Websocket disconnected 192.168.178.34:55327 (state: 0)
11:46:12:473 DB save zll database items 0x00000008
11:46:12:482 DB saved in 9 ms
11:46:12:482 don't close database yet, keep open for 900 seconds
11:46:13:269 New websocket 192.168.178.34:55344 (state: 3)
11:46:18:352 Websocket disconnected 192.168.178.34:55344 (state: 0)
11:46:19:468 New websocket 192.168.178.34:55371 (state: 3)
11:46:39:013 send permit join, duration: 59
11:47:03:953 Websocket disconnected 192.168.178.34:55371 (state: 0)
11:47:05:064 New websocket 192.168.178.34:55470 (state: 3)
11:47:05:559 Websocket disconnected 192.168.178.34:55470 (state: 0)
11:47:05:573 Current channel 11
11:47:10:839 New websocket 192.168.178.34:55497 (state: 3)
11:47:11:677 Websocket disconnected 192.168.178.34:55497 (state: 0)
11:47:12:786 New websocket 192.168.178.34:55506 (state: 3)
11:47:13:748 Websocket disconnected 192.168.178.34:55506 (state: 0)
11:47:14:821 New websocket 192.168.178.34:55511 (state: 3)
11:47:18:687 Websocket disconnected 192.168.178.34:55511 (state: 0)
11:47:19:785 New websocket 192.168.178.34:55526 (state: 3)
11:47:21:577 Websocket disconnected 192.168.178.34:55526 (state: 0)
11:47:24:801 New websocket 192.168.178.34:55547 (state: 3)
11:48:05:571 Current channel 11
11:48:47:784 Websocket disconnected 192.168.178.34:55547 (state: 0)
11:48:49:061 New websocket 192.168.178.34:55757 (state: 3)
11:49:05:586 Current channel 11
11:49:12:013 send permit join, duration: 59
11:50:05:584 Current channel 11

**Comment by marthoc** [comment]
Conbee in particular is sensitive to interference and this isn't the first report I've heard of the device not working in certain USB ports, especially attached to a large server. Other users have gotten rid of the problem by using a USB extension cable to get the USB stick away from the server altogether (which may also improve the range of the Conbee).

Closing as this isn't a docker-specific issue.
