### ISSUE TITLE
Raspbee on Pi3

### ISSUE THREAD

**Issue by camlog** [marthoc/docker-deconz#7]
Just a quick note to say many thanks for your work on this.

I was really struggling to get the Raspbee working on my Pi3 until I discovered a couple of config.txt lines from gjong at https://community.home-assistant.io/t/deconz-for-hass-io/41165/3 about disabling Bluetooth to allow the GPIO serial lines to work properly.
Might be a good addition to your README.

**Comment by marthoc** [comment]
Thanks for the suggestion! Since it’s not a piece of info unique to running deCONZ in Docker, I didn’t think to include it, but I will add it to the README. Thanks again!
