### ISSUE TITLE
Wrong timezone set when using env variable

### ISSUE THREAD

**Issue by chbndrhnns** [marthoc/docker-deconz#73]
I expect the timezone be set to 'Europe/Berlin' when using `TZ=Europe/Berlin"` in my docker-compose file.
Instead, I see `{"timezone": "Etc/GMT-1"}` in when querying the REST API at  `host:port/api/KEY/config`.

**Comment by marthoc** [comment]
To be honest, I'm not sure how deCONZ picks up the timezone from the host system. I would have expected it to query the host settings and set accordingly. Seemingly, it doesn't do that. Not sure I can fix it from my end, it's maybe a deCONZ issue.

**Comment by chbndrhnns** [comment]
You could link to https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1056 if you believe that it is not an issue with the dockerized version.
