### ISSUE TITLE
Power-on behavior

### ISSUE THREAD

**Issue by TimmyUll** [marthoc/docker-deconz#74]
When updating and change power-on behavior on Hue-lights to "last uses color and brightness". Then connect them to conbee again. The Power-on behavior changes back to 100% White light regardless what previous state was.

**Comment by TimmyUll** [comment]
When updating and change power-on behavior on Hue-lights to "last uses color and brightness". Then connect them to conbee again. The Power-on behavior changes back to 100% White light regardless what previous state was.

**Comment by marthoc** [comment]
I think this is a deCONZ issue - pinging @manup

**Comment by manup** [comment]
Likely the settings are lost when the light is brought back to factory settings, which could be expected.

We may implement configuring this feature in future versions.
