### ISSUE TITLE
Not able to upgrade FW on conbee with latest version 2.5.54 

### ISSUE THREAD

**Issue by nicklas1988** [marthoc/docker-deconz#82]
Hi,

I have a new conbee stick and need to update the FW (it seems the current fw have problem adding light).

But when I follow the guide on upgrading FW i don´t get any GCF file specified in the logs as specified in step 1.

I have no problem accessig the deconz page, but when trying to add an IKEA trådfri E14 nothing happens (I have followed all steps, and tried resetting the lamp). So my only option now is to first update the FW on conbee stick, and if that don´t work. Return the lamp.

Here are the logs:

deconz           | [marthoc/deconz] Starting deCONZ...
deconz           | [marthoc/deconz] Current deCONZ version: 2.05.54
deconz           | [marthoc/deconz] Web UI port: 8880
deconz           | [marthoc/deconz] Websockets port: 8443
deconz           | libpng warning: iCCP: known incorrect sRGB profile
deconz           | 08:40:18:616 HTTP Server listen on address 0.0.0.0, port: 8880, root: /usr/share/deCONZ/webapp/
deconz           | 08:40:18:618 CTRL. 3.16.208:40:18:640 ZCLDB init file /root/.local/share/dresden-elektronik/deCONZ/zcldb.txt
deconz           | 08:40:18:704 parent process /bin/sh
deconz           | 08:40:18:704 gw run mode: docker
deconz           | 08:40:18:704 GW sd-card image version file does not exist: /root/.local/share/dresden-elektronik/deCONZ/gw-version
deconz           | 08:40:18:705 DB sqlite version 3.16.2
deconz           | 08:40:18:705 DB PRAGMA page_count: 0
deconz           | 08:40:18:705 DB PRAGMA page_size: 4096
deconz           | 08:40:18:705 DB PRAGMA freelist_count: 0
deconz           | 08:40:18:705 DB file size 0 bytes, free pages 0
deconz           | 08:40:18:705 DB PRAGMA user_version: 0
deconz           | 08:40:18:705 DB upgrade to user_version 1
deconz           | 08:40:18:730 DB write sqlite user_version 1
deconz           | 08:40:18:731 DB PRAGMA user_version: 1
deconz           | 08:40:18:731 DB upgrade to user_version 2
deconz           | 08:40:18:733 DB write sqlite user_version 2
deconz           | 08:40:18:734 DB PRAGMA user_version: 2
deconz           | 08:40:18:735 DB upgrade to user_version 6
deconz           | 08:40:18:738 DB write sqlite user_version 6
deconz           | 08:40:18:739 DB PRAGMA user_version: 6
deconz           | 08:40:18:739 DB cleanup
deconz           | 08:40:18:739 DB create temporary views
deconz           | 08:40:18:740 don't close database yet, keep open for 900 seconds
deconz           | 08:40:18:741 don't close database yet, keep open for 900 seconds
deconz           | 08:40:18:741 started websocket server at port 8443
deconz           | 08:40:18:742 create default username and password
deconz           | 08:40:18:743 discovery updated announce interval to 10 minutes
deconz           | 08:40:18:743 GW firmware update not supported on x86 linux headless
deconz           | 08:40:18:744 found node plugin: libde_rest_plugin.so - REST API Plugin
deconz           | 08:40:18:744 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
deconz           | 08:40:18:750 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
deconz           | This plugin does not support propagateSizeHints()
deconz           | This plugin does not support propagateSizeHints()
deconz           | This plugin does not support propagateSizeHints()
deconz           | 08:40:18:851 Device firmware version 0x260B0500
deconz           | 08:40:18:883 unlocked max nodes: 200
deconz           | 08:40:19:171 Device protocol version: 0x0104
deconz           | 08:40:19:189 new node - ext: 0x00212effff029ebc, nwk: 0x0000
deconz           | 08:40:19:234 New websocket 10.0.0.81:49370 (state: 3)
deconz           | 08:40:19:379 Current channel 15
deconz           | 08:40:19:443 CTRL ANT_CTRL 0x02
deconz           | 08:40:19:571 Device protocol version: 0x0104
deconz           | 08:40:19:763 Current channel 15
deconz           | 08:40:19:827 CTRL ANT_CTRL 0x02
deconz           | 08:40:20:132 DB save zll database items 0x00000888
deconz           | 08:40:20:142 DB saved in 10 ms
deconz           | 08:40:20:144 don't close database yet, keep open for 900 seconds
deconz           | 08:40:20:696 don't close database yet, keep open for 900 seconds
deconz           | 08:40:20:840 don't close database yet, keep open for 900 seconds
deconz           | 08:40:20:939 ZDP discovery done in 247 ms08:40:21:232 New websocket <IP-Adress>:49371 (state: 3)
deconz           | 08:40:24:031 Announced to internet
deconz           | 08:40:30:784 CTRL db store gui node 00:21:2e:ff:ff:02:9e:bc
deconz           | 08:40:30:788 saved node state in 0 ms
deconz           | 08:40:30:815 sync() in 26 ms
deconz           | 08:40:33:786 DB save zll database items 0x00000008
deconz           | 08:40:33:796 DB saved in 10 ms
deconz           | 08:40:33:796 don't close database yet, keep open for 900 seconds
deconz           | 08:40:38:783 Set bridgeid to 00212EFFFF029EBC
deconz           | 08:40:43:783 DB save zll database items 0x00000008
deconz           | 08:40:43:792 DB saved in 10 ms
deconz           | 08:40:43:793 don't close database yet, keep open for 900 seconds
deconz           | 08:40:56:386 scan finished

**Comment by nicklas1988** [comment]
I am using docker-compose btw

**Comment by nicklas1988** [comment]
> You can skip that step and go true and in the last step specify the fw version you want

Where can I find what the latest fw version is? It isn´t so clear from the dresden-elektronik webpage.

**Comment by Gnaget2** [comment]
I would recommend using 262F0500

**Comment by nicklas1988** [comment]
When I try to do as you suggest, i get the following error message:
error opening firmware file /usr/share/deCONZ/firmware/deCONZ_Rpi_0x262F0500.bin.GCF

**Comment by nicklas1988** [comment]
I have via the windows deconz GUI managed to upgrade the FW to 261F0500. But that does not help. I did not find any never version of deconz software for windows than 2.5.20, suppose thats why I cannot upgrade to a never FW..

**Comment by nicklas1988** [comment]
@marthoc do you have any ideas what could be the issue? I saw that there was some out-commented code in the firmware-update.sh regarding getting the firmware update files. Is that related?

**Comment by avraham** [comment]
I had the same issue. It looked like the latest FW wasn't available. The solution for me was to update the docker deconz first.

Have you tried that?
[https://github.com/marthoc/docker-deconz/issues/77](url)

**Comment by nicklas1988** [comment]
@avraham 
I previously tried pulling the latest docker deconz image, but with no improvment. But now there seems to be a better version. 

Still the fw-version is not displayed in the logs. But when i run the firmware tool as described, there was 4 or 5 versions that I could choose from. And that worked and now I have a new version.

Thank you for your tip! :)

Note though that it was not the latest fw-version being displayed, but the second latests fw and older.

According to this page deCONZ_Rpi_0x26300500.bin.GCF should be available. But i only found deCONZ_Rpi_0x262f0500.bin.GCF among the suggestions.
https://www.dresden-elektronik.de/rpi/deconz-firmware/?C=M;O=D

-------------------------------------------------------------------

       marthoc/deconz Conbee/RaspBee Firmware Flashing Script

                       Version: 0.3

-------------------------------------------------------------------

Enter C for Conbee, R for RaspBee, or press Enter now to exit: C

Listing attached devices...

GCFFlasher V2_11 (c) dresden elektronik ingenieurtechnik gmbh 2017/12/10

       1  FTDI device found

 device | vendor | product | serial  | description
--------|--------|---------|---------|----------------------
   0    | 0x0403 | 0x6015  | XXXXXXX| FT230X Basic UART

Enter the Conbee device number, or press Enter now to exit.

Device Number : 0

-------------------------------------------------------------------

Firmware available for flashing:

deCONZ_Rpi_0x261f0500.bin.GCF
deCONZ_Rpi_0x26290500.bin.GCF
deCONZ_Rpi_0x262c0500.bin.GCF
deCONZ_Rpi_0x262e0500.bin.GCF
deCONZ_Rpi_0x262f0500.bin.GCF

Enter the firmware file name from above, including extension,
or press Enter now to exit.

File Name : deCONZ_Rpi_0x262f0500.bin.GCF

-------------------------------------------------------------------

Conbee Device Number: 0

Firmware File: deCONZ_Rpi_0x262f0500.bin.GCF

Are the above device and firmware values correct?
Enter Y to proceed, any other entry to exit: Y

Flashing...

GCFFlasher V2_11 (c) dresden elektronik ingenieurtechnik gmbh 2017/12/10
using firmware file: /usr/share/deCONZ/firmware/deCONZ_Rpi_0x262f0500.bin.GCF
reset via FTDI

flashing 125788 bytes: |=============================|
verify: ....
SUCCESS

**Comment by marthoc** [comment]
The firmware versions that are displayed by the firmware flashing script is totally dependent on the deconz version, since the firmware files are distributed with the deconz binary. This is why updating to a new deconz version gave you more firmware files to choose from.

**Comment by nicklas1988** [comment]
@marthoc 
Thank you for your response.

But my old firmware of the conbee (at the beginning of the issue) was from 28-Sep-2016 (0x260B0500)..

And my deconz version was new at the time of creating the issue (2.05.54). So there should have been multiple newer firmware. 

Anyways, it is working now. So I am happy :)

**Comment by grishmanCH** [comment]
@marthoc for me, newly created latest version of container doesn't show any devices. Phosconn app have Conbee II identified. Installation is on the QNAP NAS. Where could the issue lie? 
-------------------------------------------------------------------
 
       marthoc/deconz Conbee/RaspBee Firmware Flashing Script
 
                       Version: 0.3
 
-------------------------------------------------------------------
 
Enter C for Conbee, R for RaspBee, or press Enter now to exit: c
 
Listing attached devices...
 
GCFFlasher V3_02 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
 
Enter the Conbee device number, or press Enter now to exit.
 
Device Number :
