### ISSUE TITLE
Exception running 2.05.55

### ISSUE THREAD

**Issue by carlioth** [marthoc/docker-deconz#91]
Can't start this addon since latest release. 
Getting the following: 

<img width="638" alt="screen shot 2019-01-15 at 22 56 29" src="https://user-images.githubusercontent.com/908670/51213055-59538280-191a-11e9-91ff-444290a62366.png">

This is likely an issue with double equal sign. 
POSIX sh doesn't understand == for string equality, as that is a bash-ism. Use = instead.

**Comment by SirJMD** [comment]
Updated to 2.05.55.1 and the issue still persists.
